### ISSUE TITLE
Add framework for Sphinx User's Guide

### ISSUE THREAD

**Issue by JulieSchramm** [ufs-community/ufs-mrweather-app#1]
A docs/UsersGuide directory will be added that includes an introduction page with links to other UFS MR Weather App resources.

**Comment by ligiabernardet** [comment]
While it is a good idea to put links to external documentation (ESMF, FV3, CCPP, etc.) at the GitHub wiki level, we thought the links could also be mentioned in the UFS MR Weather App Users Guide so the guide provides a complete resource to users.

**Comment by ligiabernardet** [comment]
Agree.

**Comment by ligiabernardet** [comment]
The framework for the Sphinx User's Guide has been committed to https://github.com/ufs-community/ufs-mrweather-app/tree/documentation/docs/UsersGuide. The content is under development and will be committed to this location before the release.
