### ISSUE TITLE
Initial Chgres tests with grib2 data

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-mrweather-app#10]
Initial tests using chgres and grib2 data to run a forecast model. 

Model runs being done in two stages -- stage 1 grib2 atmosphere data with nemsio surface files ; stage 2 grib 2 atmosphere data with grib2 surface files

**Comment by arunchawla-NOAA** [comment]
Hi. Can you provide a status of this ticket?

**Comment by LarissaReames-NOAA** [comment]
We believe that we have the last of the loose bugs tied up and fixed. We're implementing one more change that addresses some of the earlier bugs more efficiently and effectively. The code should be ready for testing within a couple of days.

**Comment by arunchawla-NOAA** [comment]
@GeorgeGayno-NOAA @LarissaReames-NOAA @BinLiu-NOAA Can you provide a status update?

**Comment by GeorgeGayno-NOAA** [comment]
> 
> 
> @GeorgeGayno-NOAA @LarissaReames-NOAA @BinLiu-NOAA Can you provide a status update?

We have run chgres using grib2 data from GFS v14, v15.1, v15.2 and v16 (Russ' current parallel).  We don't see any obvious errors in any of the surface fields.  However, I just ran the regression tests on Hera and they failed.  Looking at the branch code, the soil moisture rescaling code (for soil type differences) was turned off.  That is likely why the tests failed.  We can't rescale the soil moisture because the grib 2 data does not contain a soil type record.  So we will need to add some logic to either rescale or not based on the input data type.

**Comment by arunchawla-NOAA** [comment]
@GeorgeGayno-NOAA @LarissaReames-NOAA @BinLiu-NOAA  can you provide a status for chgres using grib2? Do we have some initial results that we can look at? At this moment we can only hope to have a few results. If you have sample grib2 and nemsio files that you are using for testing please provide them to @KateFriedman-NOAA so we can put them in the ftp directory

**Comment by BinLiu-NOAA** [comment]
@arunchawla-NOAA  and All,

I got instructions from @LarissaReames-NOAA and @GeorgeGayno-NOAA last Friday that the chgres code (in the feature/chgres_cube_grib2_release branch) was ready for conducting tests of producing both atm and sfc initial conditions by using GFS grib2 files. So far, I have successfully compiled the latest version of the code on Hera, and generated the atm and sfc IC files by using the GFS grib2 files for the 2019082900 forecast cycle on Hera for the C96/C192/C384/C768 configurations. I am starting running the actual forecasts by using these generated ICs now. So, depending upon how busy Hera is, I should be able to finish this set of tests by end of this week. So, you can expect another update from me early next week.

Bin

**Comment by BinLiu-NOAA** [comment]
Dear All,

Just another update that the tests using both atm and sfc IC files generated by chgres using grib2 format GFS input files have went through successfully for the C96/C192/C384/C768 configurations for the 2019082900 forecast cycle on Hera. 

BTW, Keqin is working on producing some simple figures comparing the results from the three C768 runs.

Bin
