### ISSUE TITLE
Plan to put final tags on and make sure tags and links are correct in all documentation

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#105]
We need a plan to put the final tags on (v1.0.0 and latest_release) and review to make sure the NCEPLIBS, WM, and app documentation has the correct links throughout.

**Comment by ceceliadid** [comment]
For example, currently I see the app UG pointing to all the "latest" versions of documentation, which needs to be changed.

**Comment by ligiabernardet** [comment]
Yes, this is in my radar. But we need the final tags to be created first.
Need a status update of that.

**Comment by llpcarson** [comment]
The following documentation pages need to be configured to point to the static (non-updating) release tag in readthedocs.

https://ufs-mrweather-app.readthedocs.io/en/ufs-v1.0.0
https://ufs-utils.readthedocs.io/en/ufs-v1.0.0
https://ufs-weather-model.readthedocs.io/en/ufs-v1.0.0
 https://ccpp-techdoc.readthedocs.io/en/v4.0.0
https://stochastic-physics.readthedocs.io/en/ufs-v1.0.0
https://upp.readthedocs.io/en/ufs-v1.0.0

Once these tags and versions are ready, we'll update the MRWeather Users Guide to reflect the release versions of the documents.

Cecelia - do all of these also need "latest_release" versions?  or, just the top-level docs (referenced externally)?

**Comment by fossell** [comment]
UPP tag ufs-v1.0.0  has been built and is available (https://upp.readthedocs.io/en/ufs-v1.0.0/)

**Comment by ceceliadid** [comment]
@llpcarson my proposal was that we put ufs-latest-release on ufs weather model, ufs medium range weather app, and nceplibs/nceplib-external and make sure the practice is useful and working well. We can always expand the usage later if we want. @arunchawla-NOAA are you okay wth that?

**Comment by llpcarson** [comment]
Sounds good to me - since the NCEPLIBS (and -externals) docs are all on the
github wikis and in README's, there isn't a readthedocs version needed (but
a repository tag)

Laurie

**Comment by ligiabernardet** [comment]
I believe we also need to settle on the final URLs for the NEMS and FV3 dycore documentation.
NEMS is currently at https://noaa-emc.github.io/NEMS_doc/index.html. Should this be https://noaa-emc.github.io/NEMS_doc_ufs-v1.0.0/index.html? 
FV3 is at https://noaa-emc.github.io/FV3_Dycore_v1.0/html/index.html. Should this be 
https://noaa-emc.github.io/FV3_Dycore_ufs-v1.0.0/html/index.html?

**Comment by arunchawla-NOAA** [comment]
@MinsukJi-NOAA and @valbonakunkel-noaa can we move the NEMS_doc and the FV3_dycore docs in these places? We should do it by hand so that this version gets frozen and the automatic update then goes to the regular place.

**Comment by MinsukJi-NOAA** [comment]
NEMS_doc_ufs-v1.0.0 folder was created:
https://noaa-emc.github.io/NEMS_doc_ufs-v1.0.0/index.html

**Comment by jedwards4b** [comment]
Any objections to creating the ufs-v1.0.0 tag on ufs-mrweather-app now?

**Comment by climbfuji** [comment]
I have not seen any reports of testing on a wide range different platforms other than the work I did (C96 GFSv15p2 only). Can folks please populate https://docs.google.com/document/d/1V86BetD4is9SF-p9C_KMcchGli1moH3BPCTlVyJXMAM/edit?ts=5e60da6f <https://docs.google.com/document/d/1V86BetD4is9SF-p9C_KMcchGli1moH3BPCTlVyJXMAM/edit?ts=5e60da6f> ? Seems like I have been testing most across platforms.

**Comment by ligiabernardet** [comment]
DTC is working on app documentation and will do a commit later this
afternoon with what could be the final version. However, it would be great
if CIME folks and all could take a look at this documentation over the next
few days because we always need another set of eyes.

**Comment by jedwards4b** [comment]
@ligiabernardet It's not entirely clear to me how that works since the ufs-weather-model tag ufs-v1.0.0 has already been created.

**Comment by ligiabernardet** [comment]
We already finalized the ufs-weather-model documentation.
We are currently finalizing the app documentation at
https://github.com/ufs-community/ufs-mrweather-app/tree/documentation. We
are working on branch documentation. But thi sbranch will have to be merged
in before the final tag is created.
We will have a stable doc later this afternoon.

**Comment by jedwards4b** [comment]
@ligiabernardet thanks for clarifying

**Comment by ceceliadid** [comment]
@ligiabernardet @rsdunlapiv @jedwards4b Could you please send what will be the final URLS for the app code and app UG? 
What time do you all think these will be ready today?

**Comment by ligiabernardet** [comment]
Ligia and @llpcarson will have their changes committed by 3 PM. @jedwards4b has additional changes coming in. Then someone need to merge branch documentation onto the main branch. Will @jedwards4b do the merge? It would be great for others to look the documentation before creating the tag. Does @ceceliadid have bandwidth?
Code for doc will be in https://github.com/ufs-community/ufs-mrweather-app (master branch, directory doc)
URL will be https://ufs-weather-model.readthedocs.io/en/ufs-v1.0.0

**Comment by jedwards4b** [comment]
@ligiabernardet I can do the merge.  Should I plan to make the tag on Monday to give folks the weekend to review the docs?

**Comment by ceceliadid** [comment]
Thank you, I will start propagating that tag even if the links are broken. I don't think I should spend much time checking docs before the tag, it's probaly best to focus on changes to the website while Bhavana is still around this week.
Could someone ( @jedwards ?) please confirm final app code tag?

**Comment by ceceliadid** [comment]
Sorry, did not mean to close that. @jedwards4b my vote is to please put the tag on this week so we can make changes to the Portal/wikis and check them. For complicated reasons it gets hard to make corrections esp. to the Portal after Monday morning.

**Comment by jedwards4b** [comment]
I need to make the tag before the docs are finalized but the docs must be finalized before I make the tag?  @ceceliadid @ligiabernardet please clarify.  The tag name will be ufs-release-v1.0.0

**Comment by climbfuji** [comment]
Chicken and egg problem! The documentation must be finalized, anticipating a tag named `ufs-release-v1.0.0` or whatever the correct name is, and then the tag can be created.

**Comment by arunchawla-NOAA** [comment]
Jim 

Just create the tag. If there are documentation updates we can force the tag creating again. Just to be on the safe side do it just before leaving for the day so we have all the changes in. If we need to address further changes then we will deal with it on Monday.

**Comment by ceceliadid** [comment]
@jedwards4b  the tag convention is ufs-v1.0.0
not
ufs-release-v1.0.0

Please confirm. The full URL for the tagged app code will be:
https://github.com/ufs-community/ufs-mrweather-app/tree/ufs-v1.0.0

Correct?

**Comment by jedwards4b** [comment]
sure

**Comment by ligiabernardet** [comment]
All, I am fine with creating the tag.
W should all know that there will be typos/issues to be found as the people start looking more at the documentation and exercising the code. Just being realistic.

**Comment by jedwards4b** [comment]
Ladies and gentlemen - the ufs-v1.0.0 tag of the ufs-mrweather-app has been created.
Have a nice weekend.

**Comment by rsdunlapiv** [comment]
Drops mic.
