### ISSUE TITLE
Need a list of known bugs

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#106]

**Comment by rsdunlapiv** [comment]
Cecelia provided a place to collect known bugs.  If you are aware of any please go ahead and add it to the document now, then we can review and consolidate @climbfuji @jedwards4b @uturuncoglu @arunchawla-NOAA @llpcarson @pjpegion @ligiabernardet @mark-a-potts

https://docs.google.com/document/d/1A_NOEHVYqtzS6iKoWd758h_rpk7QmlN2VtRcY-Vc_qU/edit?usp=sharing

**Comment by ceceliadid** [comment]
I removed the google doc.

Known bugs for the app are here:
https://github.com/ufs-community/ufs-mrweather-app/wiki/All-Releases:-Release-Notes-and-Known-Bugs

Known bugs for nceplibs & nceplibs-external are here:
https://github.com/NOAA-EMC/NCEPLIBS-external/wiki/All-Releases%3A-Release-Notes-and-Known-Bugs

The app KBs point to the lib KBs.

Please put additional bugs on these pages. Write if want to do something different.

@junwang-noaa what do you think about a known bugs page on the WM wiki for releases?

**Comment by junwang-noaa** [comment]
So far I haven't heard any known bugs from the model side. I prefer to set
up a WM wiki page once we know there are some bugs in the model.

**Comment by ceceliadid** [comment]
Thanks @junwang-noaa I think this ticket can be closed then. @jwolff-ncar the links you would reference for KB pages are earlier in this ticket. I don't think the communication/coordination and maintenance questions surrounding the wikis & forums are all answered but this ticket is probably not going to answer them.
