### ISSUE TITLE
Create area for release notes for app (and wm?)

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#109]
There should be an area, maybe on the wiki, for release notes, so people can see a summary of capabilities delivered and when the next release comes out, what capabilities were added. The known bugs/limitations listing could also be in this area.

**Comment by arunchawla-NOAA** [comment]
who is taking this on? @ceceliadid @mvertens @lbnance @rsdunlapiv ?

**Comment by ceceliadid** [comment]
I created a page here: https://github.com/ufs-community/ufs-mrweather-app/wiki/All-Releases:-Release-Notes-and-Known-Bugs
Probably need a call to fill in the known bugs.

**Comment by ceceliadid** [comment]
@arunchawla-NOAA @rsdunlapiv @mvertens How do you want to deal with getting release notes and known bugs together and reviewed?

**Comment by rsdunlapiv** [comment]
@ceceliadid can you please create a blank "known bugs" Google Doc that we can circulate to collect a list?  (unless you already have this?)  Also, can this be added to the agenda for the Friday call?

**Comment by ceceliadid** [comment]
https://docs.google.com/document/d/1A_NOEHVYqtzS6iKoWd758h_rpk7QmlN2VtRcY-Vc_qU/edit?usp=sharing

I don't think it makes sense to try to collect RNs and KBs during the Friday call, that call is more about release communications and will have comms people on it. I would suggest setting up a separate call to work through the KBs, probably with more of the build team on it.

**Comment by rsdunlapiv** [comment]
@ceceliadid thank you - I circulated this so we can start collecting

**Comment by ceceliadid** [comment]
@arunchawla-NOAA I think this is done as much as it is going to be done w/o talking about future roles & responsibilities for wikis and forums.
