### ISSUE TITLE
Portal review for release

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#110]
The release team leads should probably take a look at how the release will be presented on the UFS Portal and make sure all relevant info is accurate and easy to find.

**Comment by arunchawla-NOAA** [comment]
@ceceliadid the timeline for the release on the portal still states Feb 28th. It is now March 11th.

**Comment by ceceliadid** [comment]
Yes - I will get it updated.

**Comment by ceceliadid** [comment]
Here is the dev portal site where we are making changes for the release - new highlights, link to support, new section for getting involved, other parts of the site like the FAQ updated. Still changing pretty rapidly, people are working on it this week. This would go live the day of the release:
http://ufs-dev.rap.ucar.edu/

**Comment by ceceliadid** [comment]
@ligiabernardet @arunchawla-NOAA @rsdunlapiv @mvertens @lbnance Here is the google document with the text changes for the Portal for review:
https://docs.google.com/document/d/1hAjadW3KkTBJU6WKztX1Fq8JCEJNFfdiJ-gJQ7b_P1Y/edit?usp=sharing

**Comment by ceceliadid** [comment]
Just had this review.
