### ISSUE TITLE
hera build of cprnc not working

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-mrweather-app#113]
https://github.com/ESMCI/cime/issues/3425

**Comment by jedwards4b** [comment]
I think that I have a fix for this but need a tester with access to hera.

**Comment by jedwards4b** [comment]
@pjpegion Are you available to try this again?

**Comment by pjpegion** [comment]
@jedwards4b I cloned a new instance of ufs-mrweather-app pointed Externals.cfg to your branch (hash e156445) of your fork of cime (https://github.com/jedwards4b/cime.git), ran ./manage_externals/checkout_externals.  And when I run create_test, I still get the same error.
I also was careful to delete my old test directories.

**Comment by jedwards4b** [comment]
@pjpegion sorry - try the latest ufs-mrweather-app

**Comment by pjpegion** [comment]
Same error, but I now see this in the CMakeError.log file:

The Fortran compiler identification could not be found in "/scratch2/BMC/gsienkf/Philip.Pegion/ufs-test5/ERS_Lh11.C96.GFSv16beta.hera_intel.try5/bld/intel/cprnc/CMakeFiles/3.16.3/CompilerIdFortran/CMakeFortranCompilerId.optrpt" and I have attached that file.
[CMakeFortranCompilerId.optrpt.txt](https://github.com/ufs-community/ufs-mrweather-app/files/4277011/CMakeFortranCompilerId.optrpt.txt)

**Comment by jedwards4b** [comment]
@pjpegion @rsdunlapiv  just tried this and it worked fine - are you sure you are up to date?
cime hash is 035f22da1 

please attach the cprnc.bldlog

**Comment by pjpegion** [comment]
I am using:
commit 035f22da16016afcde3c1c2af8e95800606b93d7 (HEAD, origin/ufs_release_v1.0)
Author: Jim Edwards <jedwards@ucar.edu>
Date:   Sun Mar 1 14:20:42 2020 -0700

    make paths consistant, remove cprnc and log is attached.  I do see this error in there:
-- Configuring incomplete, errors occurred!
[cprnc.bldlog.200302-174535.txt](https://github.com/ufs-community/ufs-mrweather-app/files/4277156/cprnc.bldlog.200302-174535.txt)

**Comment by jedwards4b** [comment]
Please try once more with cime hash 6c4b7875a

**Comment by pjpegion** [comment]
same error,  I'm using commit 6c4b7875a79ba0ec24d0f7255271ebc6f309051f

CMakeError.log :  The Fortran compiler identification could not be found in "/scratch2/BMC/gsienkf/Philip.Pegion/ufs-test5/ERS_Lh11.C96.GFSv16beta.hera_intel.try5/bld/intel/cprnc/CMakeFiles/3.16.3/CompilerIdFortran/CMakeFortranCompilerId.optrpt"

I have attached the cmake output log, and a snapshot of my environment. 
[CMakeOutput.log.txt](https://github.com/ufs-community/ufs-mrweather-app/files/4277309/CMakeOutput.log.txt)
[phil_env.txt](https://github.com/ufs-community/ufs-mrweather-app/files/4277310/phil_env.txt)

**Comment by pjpegion** [comment]
@rsdunlapiv I'm curious about your environment and node you compiled on.

**Comment by rsdunlapiv** [comment]
@pjpegion - @jedwards4b and I just resolved the issue on Hera and the ufs-mrweather-app was updated.  (It turns out I was using the CIME master branch before, which I should not have been.)  The cprnc build issue should now be resolved with fresh checkout of the app.

**Comment by llpcarson** [comment]
Good to hear, I was just going to add my notes - I was able to build and run on hera, using the ufs_release_v1.0 of CIME.

**Comment by pjpegion** [comment]
@rsdunlapiv trying to get the latest to test, but github keeps on timing out. I will try again soon.

**Comment by pjpegion** [comment]
@jedwards4b and @rsdunlapiv working now.  Thank you for all your help.
