### ISSUE TITLE
old app tag being tested if using app quick start as a testing guide 

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#115]
Hi @ligiabernardet  and @llpcarson , I found when I was using the quick start that the git clone command that it starts with points you to an old tag of the app:git clone -b ufs-v1.0.0.alpha02 https://github.com/ufs-community/ufs-mrweather-app.git my_ufs_sandbox

That meant I was missing pretty major recent changes that prevented me from building on Stampede. To get the latest app code the quick start should instead use somethig like:
git clone https://github.com/ufs-community/ufs-mrweather-app.git my_ufs_sandbox  
I don't know if people in DTC who are testing are already aware of this, but if they are really using the quickstart guide as a starting point as the doc sheet says I don't think they are testing what's going to get tagged as 1.0.0.

**Comment by ligiabernardet** [comment]
Thanks for pointing this out. I have updated the MRW App UG to change the cloning instruction accordingly.

**Comment by ceceliadid** [comment]
Thank you! I see the change and will close this.

**Comment by llpcarson** [comment]
Cecelia - this was actually updated a week or more ago ---- but it requires
the user (me and you!) to refresh our browser cache to see it, an
unfortunate gotcha!  Each chapter is a new browser page, needs to be
refreshed individually.

**Comment by ceceliadid** [comment]
Interesting, though I don't think that has been my experience. On the call Friday I'm pretty sure I was seeing changes as they were being made and I saw a change this morning without refreshing my browser cache. Probably worth some more experimentation...

**Comment by llpcarson** [comment]
It doesn't seem consistent, but I was looking at the HTML and the
.rst files this morning --- and thought there must be a readthedocs-build
error, but no, so not quite sure.  Refresh seems to clear up the issue,
though.

**Comment by llpcarson** [comment]
I think the readthedocs is not triggering a new build on commits... I just
pushed an update to documentation and no new readthedocs build.  That's why
I cloned the updated repo, but the pages were still old (so I thought they
were cached)?

**Comment by ligiabernardet** [comment]
There was a problem with the MRW App GitHub notifications to RTD that I
introduced yesterday when re-creating the RTD project to comply with our
newly decided name for the RTD project. This should be fixed now.
