### ISSUE TITLE
Various wrt chgres_cube documentation

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#117]
@arunchawla-NOAA @GeorgeGayno-NOAA @valbonakunkel-noaa @llpcarson 

a) Throughout the documentation text, we are sometime referring to "chgres" and sometimes to "chgres_cube". I would like to standardize this. Should we always use chgres_cube?

b) The ReadTheDocs project that will be used to display the chgres_cube documentation is connected to repository https://github.com/NOAA-EMC/UFS_UTILS. Do you anticipate that in the future this documentation will be expanded to include additional UFS_UTILS tools? Should the ReadTheDocs project be called chgres_cube or UFS_UTILS? It is better to decide this now because future changes may result in broken links.

c) Once we decide on a) and b) above, I will set up the ReadTheDocs project. In order to enable auto-updates to display the "latest" documentation, I will need a UFS_UTILS repository administrator to go to settings -> webhooks and enter a URL I will provide.

**Comment by arunchawla-NOAA** [comment]
Ligia

We will be adding additional documentation for the other tools in time.

**Comment by arunchawla-NOAA** [comment]
chgres_cube is used to distinguish from original chgres and denotes it working with the FV3 code. @GeorgeGayno-NOAA do you want to refer to it by this name for life?

**Comment by GeorgeGayno-NOAA** [comment]
> 
> 
> chgres_cube is used to distinguish from original chgres and denotes it working with the FV3 code. @GeorgeGayno-NOAA do you want to refer to it by this name for life?

On Friday, I thought I updated the google doc to only use 'chgres_cube'.

For now, I would use 'chgres_cube'.  That is consistent with the directory and executable names.  I admit it is not a great name.  We should probably come up with something better for the next public release.

**Comment by ligiabernardet** [comment]
@GeorgeGayno-NOAA You said "I would use 'chgres_cube'." I noticed that in the documentation you have in GitHub the program is referred to as CHGRES_CUBE. Elsewhere, .g., in the MR Weather App documentation, it is in lower case (chgres_cube). I would like to standardize this. Is it okay if we use lower case throughout the documentation?
I created a PR to the UFS_UTILS repo (https://github.com/NOAA-EMC/UFS_UTILS/pull/83) to add the structure for RTD to build the Sphinx rst files - please take a look. Tks

**Comment by GeorgeGayno-NOAA** [comment]
> 
> 
> @GeorgeGayno-NOAA You said "I would use 'chgres_cube'." I noticed that in the documentation you have in GitHub the program is referred to as CHGRES_CUBE. Elsewhere, .g., in the MR Weather App documentation, it is in lower case (chgres_cube). I would like to standardize this. Is it okay if we use lower case throughout the documentation?

Lower case is fine.

> I created a PR to the UFS_UTILS repo ([NOAA-EMC/UFS_UTILS#83](https://github.com/NOAA-EMC/UFS_UTILS/pull/83)) to add the structure for RTD to build the Sphinx rst files - please take a look. Tks

**Comment by ligiabernardet** [comment]
The chgres_cube documentations is now available in ReadTheDocs at https://ufs-utils.readthedocs.io/en/latest/. 
@GeorgeGayno-NOAA Please go to the UFS_UTILS repo -> settings -> and add this webhook: https://readthedocs.org/api/v2/webhook/ufs-utils/113718/
After this is done, we should expect to see auto-updates. 
I will submit a follow up PR to change chgrs_cube to lower case. We now can all review the documentation content together.

**Comment by GeorgeGayno-NOAA** [comment]
> 
> 
> The chgres_cube documentations is now available in ReadTheDocs at https://ufs-utils.readthedocs.io/en/latest/.
> @GeorgeGayno-NOAA Please go to the UFS_UTILS repo -> settings -> and add this webhook: https://readthedocs.org/api/v2/webhook/ufs-utils/113718/
> After this is done, we should expect to see auto-updates.
> I will submit a follow up PR to change chgrs_cube to lower case. We now can all review the documentation content together.

Just added the webhook.

**Comment by ligiabernardet** [comment]
Final User's Guide is now available at https://ufs-utils.readthedocs.io/en/latest/.
