### ISSUE TITLE
Use CMake from ufs-weather model in CIME build

### ISSUE THREAD

**Issue by mvertens** [ufs-community/ufs-mrweather-app#12]
Currently this is working on cheyenne and hera. 
Currently this is on a fork: https://github.com/ESCOMP/ufs-mrweather-app/tree/jpe_fv3_build
@arunchawla-NOAA @mark-a-potts  - 
  - this does not work with GNU is because NCEPLIBS does not compile with gnu on cheyenne - this is dependent on https://github.com/ufs-community/ufs-mrweather-app/issues/7

**Comment by arunchawla-NOAA** [comment]
@jedwards4b Any update on this ? The nceplibs should build with gnu now. Adding @climbfuji and @mark-a-potts to comment

**Comment by jedwards4b** [comment]
@arunchawla-NOAA I am at a conference today and then off until after christmas.

**Comment by climbfuji** [comment]
I am still working through a few issues building on macOS with GNU. I am testing different scenarios, a build that finds nothing but compiler and mpi library (i.e. builds the entire software stack), versus builds that find several to all of the required 3rd party libraries and build only what is missing.

**Comment by uturuncoglu** [comment]
@jedwards4b Couple of observations about the build that might create an issue,

- When i try to use existing build directory during creating a new case, the case.build command compiles everything from scratch. 
- In this case, CCPP suit v15p2 is the default and if the existing build directory is compiled with v16beta we need to change the CCPP_SUITES option and namelist accordingly.

**Comment by arunchawla-NOAA** [comment]
@jedwards4b @mvertens @rsdunlapiv Is this still an issue? Are you able to build the model through CIME?

**Comment by jedwards4b** [comment]
This issue has been resolved.
