### ISSUE TITLE
Update release description for latest changes

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#123]
@arunchawla-NOAA @ligiabernardet @rsdunlapiv @lbnance 

I think there have been some changes that need to get updated in the release description, for the physics suites available and output formats.

My understanding is that there will be 4 supported physics and no lat-lon outputs.

Could you please make those changes in the release description and review the final overall:
https://docs.google.com/document/d/1e9XaF2snfV1j_HBDCQ9T2TNVNWY0uWFr-R8r6jCm_bE/edit

**Comment by ligiabernardet** [comment]
I cannot edit this document. Can others open it?

**Comment by JulieSchramm** [comment]
I cannot open this file.

**Comment by pjpegion** [comment]
@ligiabernardet I cannot open it from the link abover, but in the e-mail version that I get from github, I can open it.  There are some junk characters in the end of the url.  Try this: https://docs.google.com/document/d/1e9XaF2snfV1j_HBDCQ9T2TNVNWY0uWFr-R8r6jCm_bE/edit

**Comment by arunchawla-NOAA** [comment]
@ceceliadid and @ligiabernardet I reviewed the document. This looks good

**Comment by ceceliadid** [comment]
@arunchawla-NOAA @ligiabernardet There was a clarification to the wording from Ligia that Bhavana is putting in today. I can close this after that.

**Comment by ceceliadid** [comment]
Bhavana put this in, we can close this.
