### ISSUE TITLE
URL for FV3 dycore documentation needs to change

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#124]
@valbonakunkel-noaa 
Please change the URL from
https://noaa-emc.github.io/FV3_Dycore_v1.0/html/index.html
to
https://noaa-emc.github.io/FV3_Dycore_ufs-v1.0.0/html/index.html
Thanks!

**Comment by pjpegion** [comment]
@valbonakunkel-noaa and please let me know how to do this so I can do the same for the stochastic_physics.

**Comment by valbonakunkel-noaa** [comment]
I changed the folder name in my branch, and i did 'git add file' with a new name and 'git commit'.

**Comment by ligiabernardet** [comment]
Thanks!
