### ISSUE TITLE
Location of CIME Documentation

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#125]
Need final location of CIME documentation for inclusion in MR W App doc by midday tomorrow (3/6). Will it point to a specific tag or release to identify that it is tied to this app release?
@mvertens welcome back!

**Comment by mvertens** [comment]
@ligiabernardet - the final location of the CIME documentation is here: http://esmci.github.io/cime/versions/ufs_release_v1.0/html/index.html - please have a look and let me know if things look okay to you.

**Comment by ligiabernardet** [comment]
Looks good to me. Tks
