### ISSUE TITLE
Final check of CIME machine configs against NCEPLIBS-external instructions

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#127]
The CIME machine configs contain module load commands that need to match the instructions for preconfigured/supported platforms in NCEPLIBS-external/doc/. We need to conduct a final check that these match.

**Comment by jedwards4b** [comment]
I have cross-checked all level1 and level2 systems.

**Comment by climbfuji** [comment]
Awesome! Thanks very much.
