### ISSUE TITLE
Determine set of platforms to test full workflow on

### ISSUE THREAD

**Issue by mvertens** [ufs-community/ufs-mrweather-app#13]
We need to determine the following:
- the list of platforms where we will be running out of the box tests for the full release workflow. 
- the list of compilers and versions for the target platforms
- what tests need to be run (we will be using the CIME testing capability to do this) - for example - exact restart tests, etc.
- the different configurations of the model that we want to have out of the box (e.g. 2 different CCPP suites and 4 different resolutions) - C96, C192, C384, C768 with 64 vertical levels)

**Comment by mvertens** [comment]
Here is a strawman that @climbfuji and @mvertens are suggesting:
Should also see https://github.com/ufs-community/ufs-weather-model/wiki/Platform-and-Compiler-Support
   
- Release Supported Machines must have the following:
   - NCEPLibs has been built
   - ESMF has been built
   - CIME supports this machine out of the box for the build
   - The fixed files have been downloaded on disk
   - At least one initial condition is available on disk
   - Any system that is listed as Tier 1 or Tier 2 will fulfill these requirements
 
- Suggested list of machines and compilers
   - cheyenne with gnu and intel
   - hera with intel
   - jet with intel
   - stampede with intel
   - gaea with intel ? 
   - orion with intel ? 
   - SuperMUC at LRZ (Leibniz Rechenzentrum) ???

- Generic linux or MacOS will be "supported" if the detailed instructions accompanying the release are followed

**Comment by ligiabernardet** [comment]
Also on the list of configurations to test: with/without stochastic
processes.

**Comment by climbfuji** [comment]
To follow up: we also need to decide about the versions of the software stack to support/preconfigure on which machine (mostly which compiler versions, but also which library versions).

**Intel:** I brought the question up at today's Intel Developer telecon. There was an overall notion that the latest Intel 19.0.5 is favored over Intel 18.x.y, because (a) this version fixes several bugs that Intel 18 and previous version of Intel 19 have, (b) the Intel compiler team will only be following up on bug reports that are with the latest version of the compiler. Currently, ufs-weather-model is tested most extensively with Intel 18.0.5.274 (hera, jet, ...) and with 19.0.2.187 (cheyenne). Both hera and cheyenne have the latest 19.0.5.281 installed. I suggest to keep Intel 18.0.5.274 on the NOAA RDHPC platforms, test 19.0.5.281 on cheyenne instead of 19.0.2.187 and update if all looks good. Other specific machines? For generic platforms, I would consider only the two versions 18.0.5.274 and 19.0.5.281 as supported.

GNU: I would suggest to test and support 8.3.0 and 9.1.0.

**Comment by arunchawla-NOAA** [comment]
Dom this sounds reasonable to me. Please confer with the build team and
update the platform support document accordingly.
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Ph: 301-683-3740
Fx: 301-683-3703
------------------------------------------------------------

**Comment by arunchawla-NOAA** [comment]
Do we have clarity on testing plans now? Suggest coordinate with @pjpegion and the testing team and then close issue

**Comment by pjpegion** [comment]
@mvertens I see you have a suggest list of machines above,  is this a list of platforms that the build team and workflow teams have access so they can do internal testing?  I have additional platforms in my test team recommendations documentation, but I think those platforms will be tested after this initial list of platforms have been tested.

**Comment by mvertens** [comment]
@Philip Pegion <philip.pegion@noaa.gov> - I think you are raising a
definite problem area. The workflow team has access to cheyenne, stampede
and for just one of us - hera. I know that Dom has access to cheyenne - but
am not sure who else. What is the best way to determine the access to those
platforms for everyone that will require the access?

**Comment by climbfuji** [comment]
I have access to all machines (orion account is still in the making) and I am willing to fill in for testing on the platforms that others cannot access.

**Comment by pjpegion** [comment]
@mvertens I just created a [google document](https://docs.google.com/spreadsheets/d/122uasMhD8aF_s6jUpy7t_Io5JSNGYOmBddtT6kh0dSQ/edit#gid=0) that has a list of platforms,  we need to get people from the build team and test team to fill it out (I will add the test team column)

**Comment by climbfuji** [comment]
I added a "working document" section to https://github.com/ufs-community/ufs-mrweather-app/wiki/MR-Weather-App-Platform-and-Compiler-Support

**Comment by mvertens** [comment]
@Dominikus Heinzeller - NOAA <dom.heinzeller@noaa.gov> - thank you! This is
great.

**Comment by ligiabernardet** [comment]
@climbfuji This is very helpful. Can we define what "maintained" means for
the purposes of the public release? For example (please modify as
necessary): "Code has been tested prior to the release and patches will be
provided if needed in case of system upgrades".

Note that for the MR Weather app User's Guide we are already working with
two concepts: 1) Supported platform (users can expect the app to run
there); and 2) Pre-configured platform (CIME, NCEPLibs, pre- and post
already installed and available to the user).

**Comment by climbfuji** [comment]
@ligiabernardet The concept fits nicely with the two tables I created, everything in the first table falls under 2), pre-configured platform, everything in the second/lower table falls into 1) - except the possible AWS image (which would be a pre-configured platform as well). I will add a statement regarding the meaning of "maintained" as you suggested.
