### ISSUE TITLE
xmlquery error on generic linux

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#131]
```
[ec2-user@ip-172-31-53-139 c192-gfsv16beta-gnu]$ ./xmlquery --listall
ERROR: Unexpected elem 'batch_system' for /home/ec2-user/sandpit/ufs-mrweather-app/c192-gfsv16beta-gnu/env_batch.xml, attrs {'type': 'none'}
```
This seems to be a problem on systems that do not have batch systems configured.

**Comment by rsdunlapiv** [comment]
If this is indeed an issue, then we will need to list it as a known bug.

**Comment by jedwards4b** [comment]
It works fine on macos, I'm trying to find a difference that would cause it to fail on linux.

**Comment by jedwards4b** [comment]
I have a fix, it's in the latest update to ufs_release_v1.0 - I can include it when I make the release tag.

**Comment by climbfuji** [comment]
Thanks! I'll try it when it the final tag is created.

**Comment by climbfuji** [comment]
Yay, ./xmlquery --listall now works on my Linux Amazon instance. Thanks!
