### ISSUE TITLE
Cannot change charge account?

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#132]
Not sure if this is a software bug or a user error.
```
./xmlchange CHARGE_ACCOUNT=G-81589
./xmlquery CHARGE_ACCOUNT
./case.setup --reset
./case.build
./case.submit
...
Submitting job script ssh login1.stampede2.tacc.utexas.edu 'cd /work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-mrweather-app-20200306/c96-gfsv15p2 ; sbatch --time 1:00:00 -p skx-normal --account TG-ATM190009 .case.chgres '
ERROR: Command: 'ssh login1.stampede2.tacc.utexas.edu 'cd /work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-mrweather-app-20200306/c96-gfsv15p2 ; sbatch --time 1:00:00 -p skx-normal --account TG-ATM190009 .case.chgres '' failed with error 'To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.


-----------------------------------------------------------------
          Welcome to the Stampede2 Supercomputer
-----------------------------------------------------------------

No reservation for this job
--> Verifying valid submit host (login1)...OK
--> Verifying valid jobname...OK
--> Enforcing max jobs per user...OK
--> Verifying availability of your home dir (/home1/06146/tg854455)...OK
--> Verifying availability of your work dir (/work/06146/tg854455/stampede2)...OK
--> Verifying availability of your scratch dir (/scratch/06146/tg854455)...OK
--> Verifying valid ssh keys...OK
--> Verifying access to desired queue (skx-normal)...OK
--> Verifying job request is within current queue limits...OK
--> Checking available allocation (TG-ATM190009)...
ERROR: User tg854455 is not associated with project TG-ATM190009 (in accounting_check_prod.pl).

Please report this problem:
U. of TX users contact (https://portal.tacc.utexas.edu/consulting)
FAILED' from dir '/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-mrweather-app-20200306/c96-gfsv15p2'
```

**Comment by jedwards4b** [comment]
If PROJECT or CHARGE_ACCOUNT is set in the environment this will take precedence over the setting in the xml file.   If PROJECT and CHARGE_ACCOUNT are both set in xml PROJECT gets precedent.

**Comment by climbfuji** [comment]
```
login1(637)$ export | grep PROJECT
login1(638)$ export | grep CHARGE_ACCOUNT
login1(639)$
```

**Comment by climbfuji** [comment]
I see. This doesn't fit with what is written in the FAQ https://ufs-mrweather-app.readthedocs.io/en/latest/faq.html#how-can-i-change-the-project-account-that-will-be-used-to-submit-jobs 

I could change PROJECT to something else (which isn't a valid account, but that's a different problem). I wonder if we should replace all <PROJECT> settings in the UFS machine config file with <CHARGE_ACCOUNT> so that the FAQ gives the correct answer?

**Comment by jedwards4b** [comment]
@ligiabernardet can we fix the FAQ on this.  The correct way to change charge account in a case  is
./xmlchange PROJECT=<account project>

**Comment by ligiabernardet** [comment]
Is this correct? Pls confirm and I'll make the change.

cd $CASEROOT./xmlchange PROJECT=[PROJECT ID] --subgroup case.chgres

**Comment by climbfuji** [comment]
Looks good to me, but wait for confirmation from the CIME team.

Do we need to add a section to the known bugs/limitations describing this confusion between PROJECT and CHARGE_ACCOUNT? It seems the latter is completely unnecessary, given that PROJECT can be set and overrides CHARGE_ACCOUNT.

**Comment by jedwards4b** [comment]
You don't need subgroup - just 
cd $CASEROOT./xmlchange PROJECT=[PROJECT ID]

On gaea CHARGE_ACCOUNT is used because the env variable PROJECT is used for something else - this is the only system that sets or requires the CHARGE_ACCOUNT variable.

**Comment by climbfuji** [comment]
> You don't need subgroup - just
> cd $CASEROOT./xmlchange PROJECT=[PROJECT ID]
> 
> On gaea CHARGE_ACCOUNT is used because the env variable PROJECT is used for something else - this is the only system that sets or requires the CHARGE_ACCOUNT variable.

If I understand correctly, people can still use PROJECT on gaea to overwrite CHARGE_ACCOUNT, right? They don't need to set the environment variable, because they can change it with ./xmlchange PROJECT=... and this will override CHARGE_ACCOUNT. If my understanding is correct, then the suggested change to the FAQ will work on all systems.

**Comment by jedwards4b** [comment]
Unfortunately no because on gaea the PROJECT environment variable takes precedent over a PROJECT xml variable set in the case.

**Comment by climbfuji** [comment]
omg what a mess. Then let's do this: change the gaea cime config to use PROJECT instead of CHARGE_ACCOUNT. And add to the documentation that users need to unset PROJECT environment variables if set.

**Comment by jedwards4b** [comment]
@climbfuji NO I don't think that would be acceptable to gaia users - here is how I changed the faq:
```
.. note::

   On machine GAIA the PROJECT environment variable is used for a different purpose,
   to change project account on this system use the CHARGE_ACCOUNT variable in the same way
   as the PROJECT variable is used above. 
```

**Comment by climbfuji** [comment]
As a matter of fact, I believe that PROJECT is something a group of people have decided to use on gaea, not something the admins have imposed. Should the group of people (including myself) just change their behavior? This could happen on any other machine, too.

**Comment by climbfuji** [comment]
I will make this change back to PROJECT, and it would be good to change the FAQ to mention that any existing PROJECT variable will interfere with the workflow and must be unset. Sorry for the back and forth, but we should make it as easy as possible for the users.

**Comment by climbfuji** [comment]
Note that the machine is called gaea and not gaia (guess how many times I spelled it wrong).

**Comment by climbfuji** [comment]
CIME config changes made in https://github.com/ESMCI/cime/pull/3438, need to wait for updated documentation to close this issue.

**Comment by climbfuji** [comment]
I see that the FAQ contains the correct information in https://ufs-mrweather-app.readthedocs.io/en/latest/faq.html#how-can-i-change-the-project-account-that-will-be-used-to-submit-jobs, including the note, and does not mention gaea/gaia or CHARGE_ACCOUNT anymore. Thanks!
