### ISSUE TITLE
Error in documentation: $WORK/NCEPLIBS-ufs-v1.0.0.beta04/bin/setenv_nceplibs.sh

### ISSUE THREAD

**Issue by MuayScience** [ufs-community/ufs-mrweather-app#138]
On the getting started page:
https://github.com/ufs-community/ufs-mrweather-app/wiki/Getting-Started

In the Prepare to Build section the documentation says:
source $WORK/NCEPLIBS-ufs-v1.0.0.beta04/bin/setenv_nceplibs.sh

It should be: $WORK/NCEPLIBS-ufs-v1.0.0/bin/setenv_nceplibs.sh

**Comment by arunchawla-NOAA** [comment]
Got it! Thanks!! Fixed
