### ISSUE TITLE
Missing step in https://github.com/NOAA-EMC/NCEPLIBS-external/blob/master/doc/README_stampede_intel.txt ?

### ISSUE THREAD

**Issue by MuayScience** [ufs-community/ufs-mrweather-app#140]
In working through the README for stampede2 it seems like there is a missing step between the nceplibs and model section. In the "How to Build the Model" section you eventually run ./build.sh, but there is nothing to tell youbuild.sh is in $WORK/my_ufs_sandbox/src/model. Or if it is it is well-hidden; I had to use find to track it down. 

There should be some step in README_stampede_intel.txt to put you into the right directory.

**Comment by climbfuji** [comment]
Thanks for your report. This is not a mistake, but maybe it could be explained better in the documentation. The `build.sh` script is only used when compiling the ufs-weather-model standalone, i.e. when not using the ufs-mrweather-app. In the latter, the CIME workflow builds the model as part of the "case".

**Comment by climbfuji** [comment]
I tried to clarify this, see here: https://github.com/NOAA-EMC/NCEPLIBS-external/pull/42

**Comment by climbfuji** [comment]
@MuayScience addressed in https://github.com/NOAA-EMC/NCEPLIBS-external/pull/42, if satisfied please close the issue. Thanks!

**Comment by MuayScience** [comment]
I think that takes care of it, thanks!
