### ISSUE TITLE
Runs fail to start on stampede2

### ISSUE THREAD

**Issue by MuayScience** [ufs-community/ufs-mrweather-app#141]
I was able to run through the instructions to build and submit on stampede2, but my jobs failed to run because they could not find certain NCEPLIBS_DIR and UFS_INPUT. So far as I can tell they are set correctly - output is below:

login1(1182)$ cat chgres.DORIAN_C96_GFSv15p2 
NCEPLIBS_DIR needs to be set! Exiting ...
login1(1183)$ echo $NCEPLIBS_DIR
/work/02441/bcash/stampede2/NCEPLIBS-ufs-v1.0.0
login1(1184)$ cat run.DORIAN_C96_GFSv15p2 
ERROR: Undefined env var 'UFS_INPUT'
login1(1185)$ echo $UFS_INPUT
/scratch/02441/bcash/inputs

**Comment by MuayScience** [comment]
Update: I just saw #137 which explains this problem, but I am going to leave this open as (at least) a documentation issue since if I hadn't happened to look at that closed issue I don't think I would have been likely to stumble across it.

**Comment by ceceliadid** [comment]
@MuayScience the Getting Started does say you need to source that script in your .bashrc or equiv and gives you the line to put in there, but I can make it more noticeable.

**Comment by ceceliadid** [comment]
@MuayScience do you think the bold makes it visible enough?

**Comment by MuayScience** [comment]
@ceceliadid - That's much better, thanks!

**Comment by uturuncoglu** [comment]
Hi Ben,

You need to set those environment variables as well as source command for nceplibs in your .bashrc. It is know problem related with TACC systems. You could find information in QuickStart guide in app documentation.

—Ufuk
