### ISSUE TITLE
checking out v1.0.0

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#143]
@jedwards4b @ligiabernardet @arunchawla-NOAA So this is confusing me. While updating the wikis for the new tag I noticed that nothing in the app 1.0.0 UG quickstart actually references the tag.
It's clone the repo:
git clone https://github.com/ufs-community/ufs-mrweather-app.git my_ufs_sandbox
cd my_ufs_sandbox
and then
./manage_externals/checkout_externals

 Is this really the latest version of the doc and not 1.0.0? If this is the right version of the doc, where is the tag getting specified?

**Comment by jedwards4b** [comment]
No, it's really 1.0.0 - apparently we missed that.  Currently the head of master and the tag point to the same place so there is no immediate consequence, but we should figure out how we want to fix that.

**Comment by ceceliadid** [comment]
Okay, thanks. That seems like it should get fixed before it goes out.

**Comment by jedwards4b** [comment]
@ligiabernardet is there any way to decouple the documentation from the code?  I think that we need to be able to make minor fixes in the docs more easily.

**Comment by ceceliadid** [comment]
Makes sense in the longer term but for this release maybe we just accept that bc of the chicken and egg issue there will be a little iteration over a couple days post-tagging to get the docs squared away?

**Comment by ligiabernardet** [comment]
For the documentation to auto-update in RTD, we need to have RTD point to a
branch and not a tag. Then we can keep updating it.
*Currently*: If we put updates to documentation in branch "documentation",
it will appear in RTD under the "latest" tab.
*Can be setup*: create a branch called whatever (e.g., ufs-v1.0.0), it will
appear in the RTD under the "whatever (e.g., ufs-v1.0.0)" tab. That seems
like a good idea but I don't know if it is possible to have a branch with
the name we already gave to a tag.
I am open to other ideas.

**Comment by jedwards4b** [comment]
The branch is called ufs-release-v1.0, can we have the release documentation point to that?

**Comment by ceceliadid** [comment]
@ligiabernardet @jedwards Please do not change the URL to the app documentation now.

Since this is the first release, I think this is the very hardest that it will be to get the documentation together and it will get easier after this. 

Once the couple major things are taken care of with the doc v1.0.0 tag, like people are pointed to the right download, the other minor updates could go on the head of the release branch and be put out with the next patch.

**Comment by ceceliadid** [comment]
@ligiabernardet @jedwards4b ... bc I bet a code patch v1.0.1 will be needed for something or other in the next couple months.

**Comment by jedwards4b** [comment]
@ligiabernardet I've corrected the doc and moved the tag - please do the rtd thing.

**Comment by ceceliadid** [comment]
I think before changing the strategy for just the app doc tag there should be more discussion and some thinking about the implications. Presumably you would want all the components (like the WM) to agree to the same doc strategy. If you create a v1.0.0 branch for the docs, the docs for 1.0.0 and 1.0.21 could be distinguished. If you instead point to something like the 1.0 release branch, the distinction in the docs is going to be lost between releases 1.0.0 and 1.0.21.

So I really think it's better to decide on a new strategy with more people engaged.

**Comment by ceceliadid** [comment]
Post-release.

**Comment by ligiabernardet** [comment]
The RTD is now pointing to the revised ufs-v1.0.0 tag and the cloning instructions are clear.
No further action needed here until a) more issues are found with doc, or b) we start on post-release work. Can we close this issue?

**Comment by ceceliadid** [comment]
It seems okay to me. Moving the WM tag for the build & run doc change shouldn't affect this app tag, right?

**Comment by ligiabernardet** [comment]
The app tag is pointing to a hash of the WM. Once we retag the WM, if
someone downloads the app, they will get the previous version of the WM
documentation. It does not seem like a big deal, because if they will use
the app they do not need the stand alone clone and build for the WM.

**Comment by llpcarson** [comment]
I just checked this same thing, Ligia, and see that the app tag is using a
WM tag in Externals.cfg.  So, this should work OK, as long as WM submodules
are not involved.

Laurie

**Comment by ceceliadid** [comment]
@ligiabernardet I've cleared cache but I still don't see the change in the live 1.0.0 UG?

**Comment by ligiabernardet** [comment]
Hmm... I reconnected RTD to the tag again. Pls try now. Looks okay here.
Make sure you are looking at the documentation version for ufs-v1.0.0 (not
latest).

**Comment by ceceliadid** [comment]
That did it, thanks. Will close.
