### ISSUE TITLE
WM UG missing directions to get WM code?

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#144]
@ligiabernardet @arunchawla-NOAA As far as I can tell, there is nowhere in the WM UG that tells you how to get the 1.0.0 release before you get to the instructions for building it, or has a link to the 1.0.0 repo. When I rewrote section 3 I think I probably expecting that to have been in a prior section. To me this would be a good candidate for making a change on Monday as well. 

I don't love the idea of making changes now to the doc & adjusting the tag, but I think both the WM and app UG should have the right directions for getting the codes from the repos.

**Comment by ligiabernardet** [comment]
OK, we can add the tag for WM on Monday.

**Comment by ceceliadid** [comment]
@ligiabernardet Would you like me to write up the change for the build & run section? I feel like it's my bad. If the tag for this gets moved on Monday that shouldn't change the app tag at all, right?

**Comment by ligiabernardet** [comment]
Do not worry about blame, everyone is working hard here! If you can write
this, it would be awesome.
Then we someone will have to re-tag the WM (Jun?).
I think we can leave the App tag as is.

**Comment by ceceliadid** [comment]
@ligiabernardet @llpcarson Here are the changes, with yellow sections to be added:
https://docs.google.com/document/d/1rmzzdSdHyEY0rhgEldJSte-O9nJ39FIOZ6lwWP-GtpQ/edit?usp=sharing

**Comment by ligiabernardet** [comment]
A PR was submitted.

**Comment by ceceliadid** [comment]
@ligiabernardet I think there was another change in that doc that was missed toward the end of the page, under the Building the Model secction. It basically just tells you to go into the ufs-weather-model directory that you created in the download commands to run ./build.sh

**Comment by ligiabernardet** [comment]
OK, I will create a PR for this.

**Comment by ligiabernardet** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/81

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet and @ceceliadid , @junwang-noaa merged these pull requests in. Can we confirm we are seeing this in the weather model guide. Are we ready to create a new tag?

**Comment by ligiabernardet** [comment]
Wait a sec. I need to update the RTD to point to the new tag.

**Comment by ligiabernardet** [comment]
RTD is working now. All looks good to me.
https://ufs-weather-model.readthedocs.io/en/ufs-v1.0.0/

**Comment by ceceliadid** [comment]
@ligiabernardet Looks good to me too. Close?
