### ISSUE TITLE
Ambiguity in UG create a case section

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#145]
In section 5.2:

If running on a supported machine, that machine will normally be recognized automatically and therefore it is not required to specify the --machine argument to create_newcase.

We don't have a definition for "supported." This sentence should be stated in terms of pre-configured, configurable, etc. as defined here: 
https://github.com/ufs-community/ufs/wiki/Supported-Platforms-and-Compilers

Even if people decide to change the UG after the release, could @jedwards (sorry Jim) or someone else please clarify which of the defined levels require the --machine argument and which do not, so I can put the correct thing on the wiki Getting Started? 

Thanks -

**Comment by ceceliadid** [comment]
I think it would be correct to change this sentence to:

**If running on a preconfigured or configurable machine, that machine will normally be recognized automatically and therefore it is not required to specify the --machine argument to create_newcase.**

Maybe @jedwards4b or @uturuncoglu could confirm?

**Comment by jedwards4b** [comment]
Yes, that would be more accurate.

**Comment by ligiabernardet** [comment]
I will make this change.

**Comment by jedwards4b** [comment]
@ligiabernardet - I already made it, but haven't updated the tag.

**Comment by ligiabernardet** [comment]
Got it, tks.

**Comment by ceceliadid** [comment]
This is a small thing, but along the same lines - at the beginning of the quick start, it should probably be:

**The following quick start guide is applicable to versions of the UFS Medium-Range Weather Application that are on preconfigured or configurable machines as listed here.**

Instead of just preconfigured, since there are special instructions for Stampede2.

**Comment by ligiabernardet** [comment]
I have made this change but did not recreate the tag

**Comment by ceceliadid** [comment]
Closing this too.
