### ISSUE TITLE
Website for raw ICs has been down for a couple weeks

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#152]
The MRW App relies on raw initial conditions that can be auto-downloaded by CIME or pre-staged by the user. In both cases, the raw ICs come from https://nomads.ncdc.noaa.gov/. However, this site has been down for the last couple of weeks (except for a few brief moments) making it impossible to run the App (except for the single case served via ftp or for those with access to NOAA HPSS).
Does anybody know what is going on with this website? Is it coming back to life or do we need to come up with a Plan B?
@arunchawla-NOAA @lbnance @mvertens @jwolff-ncar

**Comment by arunchawla-NOAA** [comment]
The https link is no longer available. See here

https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-data-assimilation-system-gdas

**Comment by ligiabernardet** [comment]
From Arun: Long and short is that the data can be accessed from here: https://www.ncei.noaa.gov/data/global-forecast-system/access/. Their is the current archive and the historical archive, that separation seems to be based on the day when the transfer was done. There were some gaps that have been taken care off. The only issue is that it does not go far back enough. It will stay here for the next two years when the archive will then be moved to the cloud. 

Does anybody know if there is still a way to access public NEMSIO files?

**Comment by ligiabernardet** [comment]
I am closing this issue since it has been superseded by https://github.com/ufs-community/ufs-mrweather-app/issues/161.
