### ISSUE TITLE
See if documentation needs to be improved with respect to changes to input.nml

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#153]
There were numerous comments about how the approach to changing the input.nml seemed un-intuitive from the GST respondents.

**Comment by ligiabernardet** [comment]
@ceceliadid Can you pls share the GST results again? I think you shared before but I can't find it now.

**Comment by ceceliadid** [comment]
On the website, ufscommunity.org, go to Research-Operations tab, go to GST
page.

**Comment by ligiabernardet** [comment]
We have upgraded the App documentation in this respect. There will be a PR soon with multiple App documentation updates.
