### ISSUE TITLE
Add documentation to CIME regarding new workflow capabilities

### ISSUE THREAD

**Issue by mvertens** [ufs-community/ufs-mrweather-app#16]
Need to coordinate this with @ligiabernardet .

**Comment by ligiabernardet** [comment]
@mvertens @jedwards4b @uturuncoglu Please review the proposed outline for MR Weather App User's Guide at [https://docs.google.com/document/d/15AxwnLl0PJzXLc9F4cylSswwReEWwkhWp0o4YfMGp2w/edit].  DTC will start populating this User's Guide as soon as we have more information about the build system, workflow, and datasets. It is a Google Doc now, later it will Sphinx and ReadtheDocs. Please comment on that Google Doc regarding any issues you see with the organization of the document. Note that it is complemented by separate User's Guide for the Weather Model, chgres, and UPP.

**Comment by mvertens** [comment]
@ligiabernardet - I would recommend setting up a sphinx top level guide as soon as possible. We can easily switch the order in that doc. But having something to look at sooner rather than later would be great. We also need to sort out details of version control of that doc and other issues. It might be good to have @bertinia give us input as to how we did this for CESM.

**Comment by ligiabernardet** [comment]
A very barebones Sphinx guide is here
https://github.com/ufs-community/ufs-mrweather-app/tree/documentation/docs/UsersGuide.
Its HTML is displayed here https://ufs-mrapp.readthedocs.io/en/latest/. The
recommendation from the documentation team was to iterate on Google Docs
for faster development, and then convert the files to Sphinx once we have a
first draft. The Google folder with the chapters (easy to switch the order)
is here:
https://drive.google.com/drive/u/0/folders/1m-oCBjAYbwyFd8PeFBo5VbrH5Xm5kEmr
.

**Comment by rsdunlapiv** [comment]
Documentation is being assembled on this branch:
https://github.com/ufs-community/ufs-mrweather-app/tree/documentation/docs/UsersGuide

**Comment by mvertens** [comment]
Actually the documentation is being assembled in the ESCOMP fork of the app:
https://github.com/ESCOMP/ufs-mrweather-app.git
When the documentation is done on the fork a PR will be done to the branch
you listed.

**Comment by ligiabernardet** [comment]
@mvertens Can you please clarify the nature of this issue. Title says _Add documentation to CIME_. Does anything need to be added to CIME itself? Or does this refer to adding CIME-related information to the UFS MR W App UG? The later is under development at https://github.com/ufs-community/ufs-mrweather-app/tree/documentation/docs/UsersGuide with display at https://ufs-mrapp.readthedocs.io/en/latest/index.html.

**Comment by ligiabernardet** [comment]
@mvertens @jedwards4b  Can you please clarify the nature of this issue. Title says Add documentation to CIME. Does anything need to be added to CIME itself? Or does this refer to adding CIME-related information to the UFS MR W App UG? The later is under development at https://github.com/ufs-community/ufs-mrweather-app/tree/documentation/docs/UsersGuide with display at https://ufs-mrapp.readthedocs.io/en/latest/index.html.

**Comment by arunchawla-NOAA** [comment]
@rsdunlapiv and @jedwards4b where are we with this issue?

**Comment by arunchawla-NOAA** [comment]
@rsdunlapiv and @jedwards4b can we close this issue?
