### ISSUE TITLE
Need to confirm solution for acquiring raw ICs

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#161]
Can the release leads please confirm if this is the solution we will use?
@arunchawla-NOAA @mvertens @lbnance 

**GRIB2**
_Manual and auto downloads of GRIB2 0.5 degree. Manual download of GRIB2 1.0 degree_.
https://www.ncei.noaa.gov/thredds/model/gfs.html
This data server has two locations -- historical and current data
https://www.ncei.noaa.gov/thredds/catalog/model-gfs-004-files-old/catalog.html
and 
https://www.ncei.noaa.gov/thredds/catalog/model-gfs-004-files/catalog.html

**NEMSIO**
_Manual download only from same location as v1.0 release)_
 https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/

**NetCDF**
_No public archives. 
Sample data will be provided in the EMC ftp site (site needs to be updated).
Manual download only._
https://ftp.emc.ncep.noaa.gov/EIB/UFS/

**Comment by arunchawla-NOAA** [comment]
@rsdunlapiv 

Need help from CIME team to confirm the update to using the different server for grabbing 0.5 deg GRIB files. There is a cut off date that switches between historical and current (the date has been set to the time when they moved this)

**Comment by rsdunlapiv** [comment]
@uturuncoglu @jedwards4b in order to handle the two different FTP sites (historical and current) is this as simple as listing both of them in the config_inputdata.xml?  i.e., if a particular date is not found in the "current" FTP site, it would then try the "historical" site that is next in the list?

**Comment by jedwards4b** [comment]
Yes, as long as the files within the two sites have the same naming convention that would work.

**Comment by uturuncoglu** [comment]
Yes, I already defined them. I'll testing them after implementation of setting that defines the file prefix based on selected resolution (1.0 and 0.5 deg.).

**Comment by rsdunlapiv** [comment]
Okay, great - thanks @uturuncoglu !

**Comment by ligiabernardet** [comment]
It was decided that we will NOT have autodownloads for release v1.1 due to the naming inconsistencies in the NCEI website. This topic has moved to https://github.com/ufs-community/ufs-mrweather-app/issues/176.
