### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-mrweather-app#163]
Confirm that documentation matches with all suggested changes

Example

Suggestion from Neil via @climbfuji: I think in Section 2.1 (quick start) there needs to be a note and link to section 5.2 regarding what to add/do when trying this on a supported-but-not-preconfigured platform.

**Comment by ligiabernardet** [comment]
The documentation has ben changed to address the suggestion from Neil (as part of https://github.com/ufs-community/ufs-mrweather-app/pull/187).

**Comment by climbfuji** [comment]
Fixed with #187.
