### ISSUE TITLE
Fix calculation of STOP_OPTION in buildnml (CIME)

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#165]
@rsdunlapiv This is listed as a known bug of the UFS MRW App v1.0 in https://github.com/ufs-community/ufs-mrweather-app/wiki/All-Releases%3A-Release-Notes-and-Known-Bugs. Will it be fixed for v1.1 or do we carry it forward as a known bug? 

If a user sets STOP_OPTION as “nseconds” using xmlchange command, the stop time of the simulation is calculated incorrectly. Actually, it is a bug in buildnml and STOP_N needs to be divided by 3600 rather than 60.

**Comment by uturuncoglu** [comment]
@ligiabernardet @rsdunlapiv this is fixed as apart of unification of UFSATM CIME interface and it will be available in the v1.1.

**Comment by ligiabernardet** [comment]
Great, thanks.
