### ISSUE TITLE
Review wikis

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#166]
The wikis for all components needs to be reviewed to see if updates are needed for the v1.1 release.

**Comment by climbfuji** [comment]
I reviewed and updated the NCEPLIBS-external and NCEPLIBS wikis today.

**Comment by climbfuji** [comment]
There is also an issue for documentation updates, which may overlap with this issue: https://github.com/ufs-community/ufs-mrweather-app/issues/163

**Comment by climbfuji** [comment]
How do we handle https://github.com/ufs-community/ufs/wiki/Supported-Platforms-and-Compilers for different releases? Version numbers and a few other details differ between MRW v1.0.0 and v1.1.0.

**Comment by climbfuji** [comment]
> How do we handle https://github.com/ufs-community/ufs/wiki/Supported-Platforms-and-Compilers for different releases? Version numbers and a few other details differ between MRW v1.0.0 and v1.1.0.

Regarding this page, should we configure orion as level-2 platform, and remove Redhat 7 from the level-3 platforms? We definitely need to update some of the compiler versions on this page for release 1.1.

**Comment by climbfuji** [comment]
@ligiabernardet please see https://github.com/ufs-community/ufs/wiki/Supported-Platforms-and-Compilers for an update for release v1.1 and the link to the previous version.

**Comment by ligiabernardet** [comment]
@climbfuji Looks great, thanks for his update. I made a small change for more clear words in the status (no change in content).

**Comment by ligiabernardet** [comment]
The [Getting Started](https://github.com/ufs-community/ufs-mrweather-app/wiki/Getting-Started) instructions in the wiki have been updated. They are good to go, except that the release tag for v1.1.0 is not available yet. If anybody sees a problem with the instructions, please report here.
