### ISSUE TITLE
Update Getting Started and Announcement forums

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-mrweather-app#168]
UFS forums: https://forums.ufscommunity.org/
The Getting Started forum links (https://forums.ufscommunity.org/forum/getting-started) need to be updated for v1.1.0. We can keep the v1.0.0 links and just add another one for the v1.1.0 release (and so on for future releases).

An Announcement needs to be added to that forum (https://forums.ufscommunity.org/forum/announcements) for v1.1.0.

**Comment by ligiabernardet** [comment]
Done
