### ISSUE TITLE
Need documentation for chgres_cube as part of UFS MR Weather app release

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#17]
We are putting together a Users' Guide for the UFS Medium-Range Weather Application that will explain the basics of how to build and run the chgres_cube + model + post using the CIME Workflow. We need additional information about chgres_cube pertaining to the aspects below. Note that the documentation on the various aspects can be combined onto a cohesive document (so not necessarily four separate documents).

1) User’s Guide - get code, build, run/modify various configurations (application-agnostic, that is, usable with any UFS app that invokes chgres)
2) Developer’s guide – code management for contributing development
3) Technical Documentation – code structure, architecture, how to add capabilities
4) Scientific Documentation – scientific aspects of the code

Given the tight timeline for the release, it is possible that we can accomplish only a subset of this, which can be augmented in future releases.

Regarding the framework for preparing and displaying the documentation, we understand that the UFS is a diverse system and that individual community software packages. In case chgres_cube does not yet have documentation, please consider the following:

- The documentation is housed the same repository as the code (in this case, ufs-utils)
- Doxygen for Fortran-embedded documentation.
- Sphinx for rest of documentation. 
- ReadTheDocs to display the HTML.

The documentation release team is available to help with the logistics if you need.
@JeffBeck-NOAA
@LarissaReames-NOAA 
@arunchawla-NOAA 
@GeorgeGayno-NOAA

**Comment by arunchawla-NOAA** [comment]
George will work with Larissa to create a google doc version. We will work on  converting that to rst form once it reaches a level of maturity

**Comment by arunchawla-NOAA** [comment]
@GeorgeGayno-NOAA and @LarissaReames-NOAA we wish to have some form of documentation ready for an external test by the end of January.

**Comment by ligiabernardet** [comment]
@GeorgeGayno-NOAA and @LarissaReames-NOAA Can you pls provide a brief update on the status of the chgres_cube documentation? Can we meet the end-of-January deadline proposed by @arunchawla-NOAA? Do you need anything from us?

**Comment by llpcarson** [comment]
Draft provided in GoogleDoc for review

**Comment by llpcarson** [comment]
@LarissaReames-NOAA @GeorgeGayno-NOAA Can you provide an update on your draft documentation?  Do you have a timeline to put it into RST?  Thanks!

**Comment by arunchawla-NOAA** [comment]
Laurie

We are finalizing the google document and then will be asking @Valbona
Kunkel - NOAA Affiliate <valbona.kunkel@noaa.gov> to help us move it to RST
form. Should begin happening this week.
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Comment by ligiabernardet** [comment]
Status update: The Google Doc has been translated to .rst by @valbonakunkel-noaa. I have added the files that enable the compilation with Sphinx (https://github.com/valbonakunkel-noaa/UFS_UTILS/pull/1). The resulting HTML is here: https://prototype-chgres-cube.readthedocs.io/en/latest/. Content still needs to be updated. @GeorgeGayno-NOAA Can you please take a look? Also, documentation needs to be moved to authoritative repository.

**Comment by arunchawla-NOAA** [comment]
documentation complete
