### ISSUE TITLE
NEMS repository: need tag and update of github.io doc display

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#172]
A release tag, called ufs-v1.1.0, needs to be created in repository https://github.com/NOAA-EMC/NEMS, branch release/public-v1.  A documentation website called https://noaa-emc.github.io/NEMS_doc_ufs-v1.1.0 needs to be created. 
@arunchawla-NOAA Do you have someone at EMC that can do this?

**Comment by ligiabernardet** [comment]
@MinsukJi-NOAA Pls remove the hash from the title.

**Comment by MinsukJi-NOAA** [comment]
A release tag [ufs-v1.1.0](https://github.com/NOAA-EMC/NEMS/tree/ufs-v1.1.0) has been created in the [NEMS](https://github.com/NOAA-EMC/NEMS) branch [release/public-v1](https://github.com/NOAA-EMC/NEMS/tree/release/public-v1).

**Comment by MinsukJi-NOAA** [comment]
Documentation website https://noaa-emc.github.io/NEMS_doc_ufs-v1.1.0 has been created.

**Comment by ligiabernardet** [comment]
Looks great. Thanks @MinsukJi-NOAA
