### ISSUE TITLE
CIME needs to recognize standardized names for raw ICS

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#176]
For v1.1 the user will have to stage the raw ICs on disk by themselves - autodownloads will not be supported.
The user will stage their raw IC with file name atm.input.ic.grb2 or atm.input.ic.nemsio or  atm.input.ic.nc according to the file format (GRIB2, NEMSIO, or netCDF, respectively). CIME will prepare the input for chgres_cube accordingly.

**Comment by uturuncoglu** [comment]
The files need to be named as follows;

* NEMSIO - atm.input.ic.nemsio and sfc.input.ic.nemsio
* GRIB2 - atm.input.ic.grb2
* NETCDF - atm.input.ic.nc and sfc.input.ic.nc

**Comment by ligiabernardet** [comment]
@uturuncoglu Just to confirm. We are also turning off the autodownload of raw ICs from the ftp site, correct? So, even for the default date for the App, users will do the manual staging of data. Pls confirm.

**Comment by uturuncoglu** [comment]
@ligiabernardet yes, i have just implemented it and i am testing now. So, user need to download IC manually (even for the default date) but other static files can be still retrieved automatically by CIME

**Comment by llpcarson** [comment]
But, for pre-configured platforms, the default case is already staged,
correct?  i.e. cheyenne at $CESMDATAROOT/ufs_inputdata/icfiles/?

Or is that changing with this change?  The Getting-Started and GST doc may
need to be updated, too, in that case.

Laurie

**Comment by uturuncoglu** [comment]
@llpcarson yes, that is correct and the default initial conditions must be in those platforms. But, when we decide not to get files automatically from server and assign them a static name like atm.input.ic.grb2, the existing files will not work anymore unless we link the IC files using new name convention.

**Comment by ligiabernardet** [comment]
This work is complete and ready for testing.
