### ISSUE TITLE
Raw ICs staged on preconfigured platforms need to be updated

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#178]
On Cheyenne directories $CESMDATAROOT/ufs_inputdata/icfiles/201909/20190829 (App’s default) and 202002/20200202 have been updated to have ICs with the new name required by the App (atm.input.ic.format_of_file). I believe similar updates are necessary on the other preconfigured platforms (Hera, Jet, and Gaea). 

On Hera, the directories are owned by @Rocky Dunlap. Can @rsdunlapiv  make these changes for Hera and can the person with permissions make the same changes for Jet and Gaea? 

Can the person with permissions update Jet and Gaea? Is that @climbfuji ?

**Comment by climbfuji** [comment]
I am not aware of having such powers, but maybe I do. Unfortunately I can't find where/how `UFS_INPUT` is defined for cheyenne or gaea in the CIME config. File `cime/config/ufs/machines/config_machines.xml` says
```
<DIN_LOC_ROOT>$ENV{UFS_INPUT}/ufs_inputdata</DIN_LOC_ROOT>
```
for both platforms.

**Comment by ligiabernardet** [comment]
I see. I guess a platform (Jet, Gaea) be preconfigured without having input datasets and fix files staged in centralized locations.

So, the only update needed is for Hera.

**Comment by rsdunlapiv** [comment]
@ligiabernardet 
On hera we have:
`/scratch1/NCEPDEV/stmp2/CIME_UFS/ufs_inputdata/icfiles/201908/20190829/gfs_4_20190829_0000_000.grb2`
So this needs to be:
`/scratch1/NCEPDEV/stmp2/CIME_UFS/ufs_inputdata/icfiles/201908/20190829/atm.input.ic.grb2`
?

How would we support multiple input files if we rename it in the ufs_input directory?  Shouldn't the standard name `atm.input.ic.grb2` be used just in the run directory?

**Comment by uturuncoglu** [comment]
@rsdunlapiv yes. that is correct. we are using following convention to keep different data formats in the same directory.

NEMSIO - atm.input.ic.nemsio and sfc.input.ic.nemsio
GRIB2 - atm.input.ic.grb2
NETCDF - atm.input.ic.nc and sfc.input.ic.nc

but, you could store only 00Z files (or only single time) in the same directory because we don't have hour information in the file and directory naming.

**Comment by rsdunlapiv** [comment]
Okay, I just made this change:
```
[Rocky.Dunlap@hfe04 20190829]$ pwd
/scratch1/NCEPDEV/stmp2/CIME_UFS/ufs_inputdata/icfiles/201908/20190829
[Rocky.Dunlap@hfe04 20190829]$ ls -la
total 88476
drwxr-sr-x 2 Rocky.Dunlap stmp     4096 Aug 31 22:02 .
drwxr-sr-x 3 Rocky.Dunlap stmp     4096 Mar  2 21:10 ..
lrwxrwxrwx 1 Rocky.Dunlap stmp       28 Aug 31 22:02 atm.input.ic.grb2 -> gfs_4_20190829_0000_000.grb2
-rw-rw-r-- 1 Rocky.Dunlap stmp 90590853 Mar  2 21:10 gfs_4_20190829_0000_000.grb2
```

**Comment by ligiabernardet** [comment]
OK, that should do it. Tks
