### ISSUE TITLE
Need documentation for UPP as part of UFS MR Weather app release

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#18]
The UPP team already has a robust document at https://github.com/NOAA-EMC/EMC_post/tree/ufs_public_release. This will need to be finalized for the UFS MR Weather app public release. 
@fossell

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet who all are working on this?

**Comment by ligiabernardet** [comment]
@fossell and Hui-ya Chuang

**Comment by fossell** [comment]
@ligiabernardet @valbonakunkel-noaa @arunchawla-NOAA - DTC has updated documentation in ufs_public_release branch of EMC_post, it's beginning to take shape but will require some tweaking as things move forward.  We have pinged EMC contributors to begin making modifications as well.  We welcome any input from UFS teams to address missing content, organization, etc.

**Comment by llpcarson** [comment]
@fossell Hi Kate - can you provide a quick update on the UPP documentation for the UFS MRW release?  Is there a draft ready for review, or a link to the current version?  Thanks!

**Comment by fossell** [comment]
@llpcarson A decent draft has been prepared by @hertneky and she will be pushing it to the release/public-v8 branch of EMC_post today.  Draft as it stands now can be found at [this link](https://ufs-public-release.readthedocs.io/en/release-public-v4/index.html), but note this will change once merged to newly established branch name (public-v8).  We have not created the "latest" link at this point.

**Comment by arunchawla-NOAA** [comment]
documentation complete
