### ISSUE TITLE
Planned tests and instructions for testing

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#180]
The DTC proposes that we use this [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1nlSC8eOemcFMeiOFnyoi7VPzj2IbIEpWJBGiH6uL_oo/edit#gid=0
) to list the necessary pre-release tests. It has two tabs: Tests and Instructions. Please feel free to add/comment on both tabs or on this issue. 
For now we are using branch  ufs-release-v1.1 for the tests. Once a few more problems are ironed out, the code will go to release/public-v1 for  the final round of tests.
Att @climbfuji: The instructions explain where to get the raw ICs for the tests.

**Comment by ligiabernardet** [comment]
Phase 2 of tests is ready to begin (there were several updates to the App which hopefully solve previous problems). The [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1nlSC8eOemcFMeiOFnyoi7VPzj2IbIEpWJBGiH6uL_oo/edit#gid=349889550) has been updated as follows:

- All tests conducted so far moved to a tab called _Old Phase 1 Tests_.
- A Tab called _Phase 2 Tests_ was created with the new tests to be conducted (att: @panll @climbfuji @llpcarson). These tests are ready to start.
- The tab with _General Instructions_ was updated to say that the code should be checked out from branch release/public-v1,
- A new tab with _Instructions for Regression Test_ was added. I would appreciate if @rsdunlapiv, @uturuncoglu, and all could review/improve these instructions. They will later be incorporated in the [App's User's Guide Chapter 6](https://ufs-mrweather-app.readthedocs.io/en/ufs-v1.0.0/testing.html).

**Comment by ligiabernardet** [comment]
@pjpegion We are ready for more testing. Please contribute as you can. If you enter your tests in the spreadsheet, that would be great. See more details in earlier comment.

**Comment by climbfuji** [comment]
There is no better place for this, as far as I can see, so I put it here. I copied the `ufs_inputdata` directory from hera to jet and to gaea.

On gaea:
```
/lustre/f2/pdata/esrl/gsd/ufs/ufs-release-v1.1/CIME_UFS/ufs_inputdata
```

On jet:
```
/lfs4/HFIP/hfv3gfs/ufs-release-v1.1/CIME_UFS/ufs_inputdata
```

**Comment by panll** [comment]
Thanks, Dom! I'll update the documentation. @climbfuji

**Comment by ligiabernardet** [comment]
We have no failures and are proceeding with the release today (10/6/2020).
