### ISSUE TITLE
Update to UPP documentation

### ISSUE THREAD

**Issue by fossell** [ufs-community/ufs-mrweather-app#185]
UPP team has some updated tables for the UPP documentation (includes tables of output fields for MRW app) that could be of interest for v1.1.  Mods would only be to doc (rst) files, however would require recreating the v1.1.0 tag so Readthedocs points to the proper tag. This would mean inconsistent hashes between preinstalled UPP tags already established on supported systems and new hash on the UPP repo for the ufs-v1.1.0 release.  These mods are not crucial, just extra information, so it can wait until next release if needed.  An alternative could be to make Readthedocs point to release/public-v1 branch instead of specific release tags, but that may be inconsistent with what other components are doing and I know we were previously directed to make sure we have a v1.1.0 version on Readthedocs to integrate into MRW documentation.  

We know this is a last minute mod, so it's a-ok if not included this go around. Please advise and I'll move forward accordingly.

**Comment by ligiabernardet** [comment]
My inclination is to delay this update to a future release in favor of not
having to re-tag and re-deploy NCEPLIBS..
As Kate mentioned, a decision was made to point doc to tags, not to head of
release branches. The rationale is that the top of release branches could
be receiving more updates (e.g., for v 1.1.1 or v1.2.0) and be inconsistent
with v1.1.0.

**Comment by climbfuji** [comment]
> My inclination is to delay this update to a future release in favor of not having to re-tag and re-deploy NCEPLIBS.. As Kate mentioned, a decision was made to point doc to tags, not to head of release branches. The rationale is that the top of release branches could be receiving more updates (e.g., for v 1.1.1 or v1.2.0) and be inconsistent with v1.1.0.

I am ok either way, but if I had to choose I would follow @ligiabernardet because it is less work (for me ;-) ).

**Comment by fossell** [comment]
Thanks for the input @ligiabernardet and @climbfuji.  We will wait to push this documentation update for a future release.  The information will be available for SRW release and in general UPP user version, so we can point users there as needed.
