### ISSUE TITLE
Help for installing NCEPLIBS on Stampede

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-mrweather-app#186]
@ligiabernardet @climbfuji I am trying to install NCEPLIBS on TACC, Stampede but NCEPLIBS-external gives error in the wgrib step as following

```
[ 18%] Performing configure step for 'wgrib2'
cd /work/01118/tg803972/stampede2/UFS/NCEPLIBS-external.1.1.0/build-all/wgrib2 && /opt/apps/cmake/3.16.1/bin/cmake -DUSE_NETCDF4=ON -DUSE_IPOLATES=0 -DUSE_SPECTRAL=OFF -DMAKE_FTN_API=ON -DUSE_PNG=ON -DUSE_JASPER=ON -DCMAKE_INSTALL_PREFIX=/work/01118/tg803972/stampede2/UFS/NCEPLIBS-external.1.1.0/build-all/install -DCMAKE_C_COMPILER=/opt/apps/intel18/impi/18.0.2/bin/mpicc -DCMAKE_Fortran_COMPILER=/opt/apps/intel18/impi/18.0.2/bin/mpif90 -DCMAKE_PREFIX_PATH=/work/01118/tg803972/stampede2/UFS/NCEPLIBS-external.1.1.0/build-all/install "-GUnix Makefiles" /work/01118/tg803972/stampede2/UFS/NCEPLIBS-external.1.1.0/wgrib2
Re-run cmake no build system arguments
[ 56%] Built target esmf
CMake Error at /opt/apps/cmake/3.16.1/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find NetCDF (missing: NetCDF_INCLUDE_DIRS)
Call Stack (most recent call first):
  /opt/apps/cmake/3.16.1/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/Modules/FindNetCDF.cmake:281 (find_package_handle_standard_args)
  CMakeLists.txt:89 (find_package)
```

In this case, I am using following steps

```
source /opt/apps/lmod/lmod/init/sh
module purge
module load TACC python/2.7.15 intel/18.0.2 cmake
module rm mvapich2
module load impi/18.0.2 pnetcdf/1.11.0
module load netcdf/4.6.2
module load cmake
module load hdf5/1.10.4

git clone --recursive -b release/public-v1 https://github.com/NOAA-EMC/NCEPLIBS-external.git NCEPLIBS-external.1.1.0
cd NCEPLIBS-external.1.1.0/
mkdir build-all
cd build-all
NETCDF=$TACC_NETCDF_DIR CC=mpicc FC=mpif90 CXX=mpicxx cmake -DBUILD_MPI=OFF -DBUILD_NETCDF=OFF -DBUILD_PNG=OFF -DBUILD_JASPER=OFF -DMPITYPE=intelmpi -DCMAKE_INSTALL_PREFIX=$PWD/install ..
make -j 4
```

I also try to set NETCDF include path by adding following option (`-DNetCDF_INCLUDE_DIRS=$TACC_NETCDF_INC`)to cmake command but it is also failing with same way. The same steps was working with the version that is used in the 1.0 release. Any suggestion?

**Comment by climbfuji** [comment]
Please follow the instructions in https://github.com/NOAA-EMC/NCEPLIBS-external/blob/release/public-v1/doc/README_stampede_intel.txt and use the same modules in CIME.

**Comment by panll** [comment]
i have a successful installation on stampede for nceplib-v1..1:  /work/06145/tg854445/stampede2/tools/NCEPLIBS-ufs-v1.1.0
@uturuncoglu

**Comment by uturuncoglu** [comment]
@panll Thanks for your help. I am getting permission error from that directory. If it is possible, could you adjust the access rights?

**Comment by uturuncoglu** [comment]
@climbfuji Currently testing those steps. I'll let you know about the progress.

**Comment by climbfuji** [comment]
> @climbfuji Currently testing those steps. I'll let you know about the progress.

I tested every single of the `doc/README_*.txt` installations about three weeks ago, so hopefully they all still work!

**Comment by uturuncoglu** [comment]
@climbfuji i confirm that I could install externals with the instructions that you gave me. I'll try to install NCEPLIBS now.

**Comment by uturuncoglu** [comment]
@climbfuji @panll Thanks for your great help. Now, i could run the model on Stampede. The instruction in `doc/README_*.txt` seems working.
