### ISSUE TITLE
failed with GFSv16beta on Hera

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-mrweather-app#189]
Failed with GFSv16beta on Hera with NEMSIO C384, here is the error message:

hfe12:/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/cime/scripts/ufs-mrweather-app-workflow.c384>./case.build 
Building case in directory /scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/cime/scripts/ufs-mrweather-app-workflow.c384
sharedlib_only is False
model_only is False
Setting Environment ESMF_RUNTIME_PROFILE=ON
Setting Environment ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
Generating component namelists as part of build
Creating component namelists
  2020-09-09 16:49:36 atm 
   Calling /scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/cime/cime_config/buildnml
Checking /scratch2/BMC/det/lpan/hera/test/mrw//ufs_inputdata/icfiles/202008/20200831 directory to find raw input files ...
Found 'atm.input.ic.nemsio' in input directory
Found 'sfc.input.ic.nemsio' in input directory
CHGRES namelist option 'input_type' is set to gaussian_nemsio
CHGRES will use /scratch2/BMC/det/lpan/hera/test/mrw//ufs_inputdata/icfiles/202008/20200831/atm.input.ic.nemsio
CHGRES will use /scratch2/BMC/det/lpan/hera/test/mrw//ufs_inputdata/icfiles/202008/20200831/sfc.input.ic.nemsio
	Linking input namelist for ufsatm
Using /scratch1/BMC/gmtb/software/NCEPLIBS-ufs-v1.1.0/intel-18.0.5.274/impi-2018.0.4/share/postxconfig-NT-GFS.txt for post-processing
Using /scratch1/BMC/gmtb/software/NCEPLIBS-ufs-v1.1.0/intel-18.0.5.274/impi-2018.0.4/share/postxconfig-NT-GFS-F00.txt for post-processing
	Creating INPUT and RESTART directory
/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app-workflow.c384/run/INPUT/C384.2020-08-31_06.gfs_ctrl.nc
CHGRES task count and tasks per node are modified! task_count = 24 tasks_per_node = 6
NCEP Post task count is changed to 160!
UFS_DRIVER is set to nems
         - Building atm Library 
Building atm with output to /scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app-workflow.c384/bld/atm.bldlog.200909-164935
/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(226): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <REAL_KIND_CON> <REAL_CONSTANT> <DBLPRC_CONSTANT> <DBLPRC_KIND_CON> <QUAPRC_CONSTANT> ...

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(243): error #5082: Syntax error, found REAL_CONSTANT '3200E-5' when expecting one of: => = / , [ ( * <END-OF-STATEMENT> ;

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(279): error #5082: Syntax error, found IDENTIFIER 'INTEGER' when expecting one of: => = / , [ ( * <END-OF-STATEMENT> ;

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(283): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <IDENTIFIER> %FILL

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(284): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <IDENTIFIER> %FILL

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(285): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <IDENTIFIER> %FILL

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(285): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(290): error #5082: Syntax error, found '(' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(290): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE DOUBLECOMPLEX ...

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(296): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(296): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(298): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(298): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(300): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [g]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [e]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [r]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [:]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [e]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [r]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [o]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [s]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [o]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(307): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(307): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(226): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <REAL_KIND_CON> <REAL_CONSTANT> <DBLPRC_CONSTANT> <DBLPRC_KIND_CON> <QUAPRC_CONSTANT> ...

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(243): error #5082: Syntax error, found REAL_CONSTANT '3200E-5' when expecting one of: => = / , [ ( * <END-OF-STATEMENT> ;

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(279): error #5082: Syntax error, found IDENTIFIER 'INTEGER' when expecting one of: => = / , [ ( * <END-OF-STATEMENT> ;

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(283): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <IDENTIFIER> %FILL

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(284): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <IDENTIFIER> %FILL

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(285): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: <IDENTIFIER> %FILL

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(285): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(290): error #5082: Syntax error, found '(' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(290): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE DOUBLECOMPLEX ...

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(296): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(296): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(298): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(298): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(300): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [g]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [e]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [r]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(302): error #5149: Illegal character in statement label field  [:]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(303): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [e]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [r]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [o]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [s]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(304): error #5149: Illegal character in statement label field  [o]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(307): error #5149: Illegal character in statement label field  [-]

/scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app/src/model/FV3/ccpp/physics/physics/radiation_aerosols.f(307): error #5149: Illegal character in statement label field  [-]

Component atm build complete with 256 warnings
ufsatm built in 130.701385 seconds
ERROR: BUILD FAIL: ufsatm.buildlib failed, cat /scratch2/BMC/det/lpan/hera/test/mrw/09092020/ufs-mrweather-app-workflow.c384/bld/atm.bldlog.200909-164935

**Comment by uturuncoglu** [comment]
@panll Yes, this is the know issue and Jim and I trying to find the reason. It seems that CIME interface related but we are not sure yet. I'll update when we find something. This is also linked to issue https://github.com/ufs-community/ufs-mrweather-app/issues/169

**Comment by panll** [comment]
Thanks! @uturuncoglu

**Comment by ligiabernardet** [comment]
This is a build failure that hopefully was resolved with the last App update. I am closing this issue, please report if other problems arise.
