### ISSUE TITLE
case.build does not work with anaconda python on hera

### ISSUE THREAD

**Issue by pjpegion** [ufs-community/ufs-mrweather-app#192]
On hera, I tried to run a C768 case.  My first attempt failed because I downloaded the wrong input file (grib1 not grib2).  I then dowloaded the correct file, and tried to run case.run again. But that failed with the an error about cannot modiy case, read_only. I then then tried case.setup -r, and then case.run, and got same error.  Then case.build --clean, same error. 
I am now getting the cannot modify case when trying to generate a new case with a new case name.

**Comment by pjpegion** [comment]
More detailed output/error from case.build -d
[case.build.error.debug.txt](https://github.com/ufs-community/ufs-mrweather-app/files/5220144/case.build.error.debug.txt)

**Comment by pjpegion** [comment]
@uturuncoglu The issue is that after my 1st failed run, I loaded anaconda3 to see what was wrong with my input file.
Since this was still loaded at compile time, it looks like CIME is using the python in anaconda3 and CIME is either not compatible with that, or there is some other conflict.

**Comment by uturuncoglu** [comment]
@pjpegion I am glad that you solved the problem. I am not sure why it happened in the first time. lets is wait for @jedwards4b comment about that.

**Comment by arunchawla-NOAA** [comment]
Since it was not a clear test we are going to close this and will open another issue if there is a problem with anaconda python
