### ISSUE TITLE
Python3 error: cheyenne

### ISSUE THREAD

**Issue by llpcarson** [ufs-community/ufs-mrweather-app#193]
@uturuncoglu - here is the error I'm getting on cheyenne when I use python3

Creating component namelists
  2020-09-14 11:07:52 atm
   Running /glade/scratch/carson/ufs/mrw.test/ufs-mrweather-app.p3/src/model/FV3/cime/cime_config/buildnml
File "/glade/scratch/carson/ufs/mrw.test/ufs-mrweather-app.p3/src/model/FV3/cime/cime_config/buildnml", line 394
    print f
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(f)?

This looks like a different error than the one reported/fixed earlier.

**Comment by uturuncoglu** [comment]
@llpcarson i fixed it it is just a debug command that I put and forget in the interface. I delete it and it will be available in the next update. Thanks for catching it.

**Comment by llpcarson** [comment]
Thanks, I'll pull this into my clone and re-test.

**Comment by llpcarson** [comment]
Fixed.
