### ISSUE TITLE
C768 RT failed on orion

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-mrweather-app#194]
There are several failures for C768 tests:
1) SMS_Lh3.C768r.HAFS.orion_intel and ERS_Lh11.C768r.HAFS.orion_intel. 

No input file/s found locally! Need files under ufs_inputdata/regional/bcond/2019090118 

2) SMS_Lh3_D.C768.GFSv16beta.orion_intel
  failed at chgres
   ERROR: Command: 'sbatch --time 12:00:00 -q batch --account gmtb  --dependency=afterok:380631 .case.test --skip-preview-namelist' failed with error 'sbatch: error: QOSMaxWallDurationPerJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)' from dir '/work/noaa/gmtb/lpan/test/09112020/scratch/SMS_Lh3_D.C768.GFSv16beta.orion_intel.G.20200911_235539_bp53ie'

3)SMS_Lh3_D.C768.GFSv15p2.orion_intel (Overall: FAIL) details:
ERROR: Command: 'sbatch --time 12:00:00 -q batch --account gmtb  --dependency=afterok:380630 .case.test --skip-preview-namelist' failed with error 'sbatch: error: QOSMaxWallDurationPerJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)' from dir '/work/noaa/gmtb/lpan/test/09112020/scratch/SMS_Lh3_D.C768.GFSv15p2.orion_intel.G.20200911_235539_bp53ie'

The working directory can be found at  /work/noaa/gmtb/lpan/test/09112020/scratch

**Comment by climbfuji** [comment]
If orion is the same as other RDHPC platforms, the maximum walltime is 8h.

**Comment by ligiabernardet** [comment]
@Linlin Pan - NOAA Affiliate <linlin.pan@noaa.gov> Did you follow the
instructions in Tab "RT Instructions" in the spreadsheet that say you must
use  --xml-category prealpha_p1, p2, p3? If you do not do that, all tests
will be launched. This will cause two problems: launching of HAFS tests
(which we do not want for MRW App) and too many jobs in the queue. Please
look at the instructions for RT tes on Orion, and see if you need to rerun
the test.

**Comment by panll** [comment]
Thanks, Ligia! I'll double check that. @ligiabernardet

**Comment by uturuncoglu** [comment]
@ligiabernardet prealpha_p1, p2, p3 is only for Stampede, the other need to use prealpha only.

**Comment by ligiabernardet** [comment]
OK, my bad. @panll : we updated the instructions today for all platforms (beyond Stampede): it is necessary to add  --xml-category prealpha, otherwise HAFS tests will be triggered. Sorry that the instructions did not include that last week. Pls try again including  --xml-category prealpha.

**Comment by panll** [comment]
Thanks, Ligia and ufuk!  @ligiabernardet @uturuncoglu

**Comment by panll** [comment]
Yes, the file testlist.xml needs to be changed for Orion @climbfuji

**Comment by uturuncoglu** [comment]
@panll @ligiabernardet I adjusted wallclock time for C768 debug tests to be consistent of max wallclock time on Orion. The max wall clock time in the tests is now 8 hours. Those changes will be available in next update but until that time src/model/FV3/cime/cime_config/testlist.xml  can be edited and 12:00:00 hours can be changed to 08:00:00.

**Comment by panll** [comment]
Thanks, ufuk! @uturuncoglu @ligiabernardet  I redo the tests with 8 hours, all passed except one test: SMS_Lh3.C768.GFSv16beta.orion_intel. This test crashed at chgres_cube:

 - IOSTAT IS:            0
[Orion-12-43:290491:0:290491] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
rd_inventory: stdin truncated, longer than INV_STRING_SIZE (600)
rd_inventory: stdin truncated, longer than INV_STRING_SIZE (600)
 - FATAL ERROR: READING GRIB2 FILE
 - IOSTAT IS:            0
[Orion-12-46:355841:0:355841] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
 - FATAL ERROR: READING GRIB2 FILE
 - IOSTAT IS:            0
[Orion-12-45:346249:0:346249] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
rd_inventory: stdin truncated, longer than INV_STRING_SIZE (600)
 - FATAL ERROR: READING GRIB2 FILE
 - IOSTAT IS:            0
[Orion-12-43:290489:0:290489] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
rd_inventory: stdin truncated, longer than INV_STRING_SIZE (600)
 - FATAL ERROR: READING GRIB2 FILE
 - IOSTAT IS:            0
[Orion-12-44:243255:0:243255] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
rd_inventory: stdin truncated, longer than INV_STRING_SIZE (600)
 - FATAL ERROR: READING GRIB2 FILE
 - IOSTAT IS:            0
[Orion-12-46:355843:0:355843] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
rd_inventory: stdin truncated, longer than INV_STRING_SIZE (600)

**Comment by ligiabernardet** [comment]
@climbfuji @uturuncoglu Do you have any suggestion as to how the environment (stack size etc.) could be modified for Orion?

**Comment by uturuncoglu** [comment]
@panll I think that setting stack size is not helping. it could be the same issue that is explained in here https://github.com/ufs-community/ufs-mrweather-app/issues/190.

**Comment by panll** [comment]
Thanks for checking that! @uturuncoglu

**Comment by arunchawla-NOAA** [comment]
should be ok with changes to ufs_utils
