### ISSUE TITLE
C768 test hanging on Jet

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-mrweather-app#196]
The C768 test with netcdf input does not pass. The job has been in pending status for more than one day. It stuck in the model running part.

fe3:/lfs4/HFIP/hfv3gfs/lpan/test/mrw/09112020/ufs-mrweather-app/cime/scripts/ufs-mrweather-app-workflow.c768>squeue | grep Linlin
  36353819 kjet       run.ufs-mrweather-app-wo Linlin.Pan       PENDING      0:00    1:00:00    69 (Resources)
  36353820 kjet       gfs_post.ufs-mrweather-a Linlin.Pan       PENDING      0:00    1:00:00     4 (Dependency)

@uturuncoglu @ligiabernardet @climbfuji

**Comment by uturuncoglu** [comment]
@panll if you check the INPUT directory and see the files that are produced by the CHGRES. It would be okay. It is just an issue related with the system. So, It seems that the queue is full.

**Comment by panll** [comment]
Yes, the CHGRES part is fine, but it stuck in the model run part. @uturuncoglu

**Comment by uturuncoglu** [comment]
@panll okay that is great. let's wait for the run.

**Comment by uturuncoglu** [comment]
@panll do you have any update about the issue?

**Comment by panll** [comment]
Model can run after long time waiting. Thanks for asking! @uturuncoglu

**Comment by uturuncoglu** [comment]
@panll okay. that is great. can we close the ticket at this point?

**Comment by panll** [comment]
ok, thanks!
