### ISSUE TITLE
UFS MRW App v1.1 User's Guide ready to review

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#199]
The [User's Guide](https://ufs-mrweather-app.readthedocs.io/en/latest/index.html) is complete except for Chapter 6 (regression tests - which will be enhanced in the next few days). Pls report any problems.
@pjpegion @llpcarson @panll @uturuncoglu @rsdunlapiv @mvertens @arunchawla-NOAA

**Comment by rsdunlapiv** [comment]
@ligiabernardet 

In 3.1  "CIME CSS" should be "CIME Case Control System" or just "CIME"

**Comment by ligiabernardet** [comment]
The UG has been finalized at https://ufs-mrweather-app.readthedocs.io/en/ufs-v1.1.0/
