### ISSUE TITLE
Need to update the URL for CIME Documentation

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#201]
Please update the URL that says v1.1.0
http://esmci.github.io/cime/versions/ufs_release_v1.0/html/index.html
@uturuncoglu @jedwards4b

**Comment by uturuncoglu** [comment]
@ligiabernardet I created the new CIME doc. The link is http://esmci.github.io/cime/versions/ufs_release_v1.1/html/index.html
