### ISSUE TITLE
Default walltime too short on Gaea?

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#206]
When running a C768 case on gaea, I need issue the following sequence of commands. I believe these are all expected except the adjustment of the walltime for the actual model run. Can we set the default walltime to 1 hour on gaea? The debug queue on gaea has a walltime limit of 1 hour, i.e. no changes required to the queue configuration.
```
./cime/scripts/create_newcase --case GFSv16betaC768 --compset GFSv16beta --res C768 --workflow ufs-mrweather
cd GFSv16betaC768/
./case.setup 2>&1 | tee log.setup
./case.build 2>&1 | tee log.build
./xmlchange STOP_OPTION=nhours
./xmlchange STOP_N=24
./case.submit 2>&1 | tee log.submit
squeue -u $USER
> JOBID       CLUSTER  PARTITION  QOS         USER                STATE    TIME_LEFT   NODES  NAME
> 268693351   c4       batch      debug       Dom.Heinzeller      PENDING  0:30:00     171    run.GFSv16betaC768
> 268693352   c4       batch      debug       Dom.Heinzeller      PENDING  1:00:00     4      gfs_post.GFSv16betaC
> 268693350   c4       batch      debug       Dom.Heinzeller      RUNNING  57:45       3      chgres.GFSv16betaC76
scontrol update jobID=268693351 TimeLimit=01:00:00
> JOBID       CLUSTER  PARTITION  QOS         USER                STATE    TIME_LEFT   NODES  NAME
> 268693351   c4       batch      debug       Dom.Heinzeller      PENDING  1:00:00     171    run.GFSv16betaC768
> 268693352   c4       batch      debug       Dom.Heinzeller      PENDING  1:00:00     4      gfs_post.GFSv16betaC
> 268693350   c4       batch      debug       Dom.Heinzeller      RUNNING  57:35       3      chgres.GFSv16betaC76
```

**Comment by ligiabernardet** [comment]
@uturuncoglu Can you make this update?

**Comment by uturuncoglu** [comment]
@ligiabernardet @climbfuji of course we could set a default value for it but it requires CIME PR. You could also adjust them using following commands easily,

```
./xmlchange JOB_WALLCLOCK_TIME=00:30:00
./xmlchange USER_REQUESTED_WALLTIME=00:30:00
```

So, if you still need it (and also other changes in CIME side if you need), let me know.

**Comment by climbfuji** [comment]
> @ligiabernardet @climbfuji of course we could set a default value for it but it requires CIME PR. You could also adjust them using following commands easily,
> 
> ```
> ./xmlchange JOB_WALLCLOCK_TIME=00:30:00
> ./xmlchange USER_REQUESTED_WALLTIME=00:30:00
> ```
> 
> So, if you still need it (and also other changes in CIME side if you need), let me know.

I don't know what is better, updating CIME again (it hasn't been tagged yet anyway) or adding more documentation.

**Comment by uturuncoglu** [comment]
@climbfuji since it is one line command, i think that we could add it to the doc and note but it is up to you.

**Comment by ligiabernardet** [comment]
OK, we can add it to the documentation. I think a FAQ would work - unless
you have a better idea.

Since we are talking about this, could you explain why two variables are
needed to change the wall clock? What is the difference between
JOB_WALLCLOCK_TIME and USER_REQUESTED_WALLTIME, and under what
circumstances would they have different values?

**Comment by uturuncoglu** [comment]
@ligiabernardet Sorry for the confusion. We just need to change the `JOB_WALLCLOCK_TIME`.

**Comment by ligiabernardet** [comment]
@uturuncoglu What is USER_REQUESTED_WALLTIME?

**Comment by uturuncoglu** [comment]
@ligiabernardet USER_REQUESTED_WALLTIME is an internal value that should not be changed by the user. 
it's just used internally to keep track. Sorry for confusion.

**Comment by ligiabernardet** [comment]
@panll Can you please add this FAQ and remove USER_REQUESTED_WALLTIME from User's Guide?

**Comment by climbfuji** [comment]
Closed via https://github.com/ufs-community/ufs-mrweather-app/pull/213
