### ISSUE TITLE
Update EMC_post in ufs-mrweather-app Externals.cfg

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#208]
We need to update EMC_post in the ufs-mrweather-app `Externals.cfg` to point to the following hash/tag:
```
commit d2723e09028c4d14d89048c8682a012822f700f3 (HEAD, tag: ufs-v1.1.0, origin/release/public-v1)
Merge: bc6074f f88c7e9
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Tue Sep 29 08:52:34 2020 -0600

    Merge pull request #191 from climbfuji/find_netcdf_bugfix_release_public_v1

    release/public-v1: bugfix for finding NetCDF
```

**Comment by uturuncoglu** [comment]
We were already point this tag for the app. The current entry in the External.cfg is

```
[emc_post]
tag = ufs-v1.1.0
protocol = git
repo_url = https://github.com/NOAA-EMC/EMC_post.git
local_path = src/post
required = True
```

**Comment by uturuncoglu** [comment]
@climbfuji did you retag it?

**Comment by climbfuji** [comment]
> @climbfuji did you retag it?

Yes I did. But since you are pointing to the tag explicitly (I forgot that `manage_externals` can do that, as opposed to Git submodules), we don't need to change anything. I'll close the PR. Thanks for the reminder about how `manage_externals` handles those dependencies.
