### ISSUE TITLE
Finalize CCPP Scientific Documentation for the MR Weather app release

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#21]
The CCPP Scientific Documentation is in good shape for the upcoming release [https://github.com/NCAR/ccpp-physics/tree/ufs_public_release/physics/docs]. However, a few finishing touches are needed:

- Update doc for PBL scheme satmedmfvdifq @grantfirl
- Update doc for unified GWD scheme @bluefinweiwei with input from Valery Yudin
- Update doc for suites GFS v15.2 and GFS v16beta, including description of new namelist parameters @mzhangw
- Update front page for release @mzhangw

**Comment by ligiabernardet** [comment]
Just a reminder to us all that the ufs_public_release of ccpp_physics still needs to be updates with these changes

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet Are there any assignees for this task ?

**Comment by ligiabernardet** [comment]
They are all DTC people listed on the first message when the ticket was created. This activity is advanced and no problem anticipated.
