### ISSUE TITLE
How to run CIME regression on Stampede?

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#214]
I can't successfully run the regression tests on Stampede. If I do:
```
./create_test --xml-testlist ../../src/model/FV3/cime/cime_config/testlist.xml --xml-machine stampede2-skx --generate 20200904-intel --baseline-root /work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch --workflow ufs-mrweather_wo_post -j 4 --walltime 03:00:00 --xml-category prealpha_p1
```
all tests fail with the following error messages:
```
login3.stampede2(1115)$ cat /scratch/06146/tg854455/SMS_Lh3.C96.GFSv16beta.stampede2-skx_intel.G.20200929_185804_pe3jpg/chgres.SMS_Lh3.C96.GFSv16beta.stampede2-skx_intel.G.20200929_185804_pe3jpg
NCEPLIBS_DIR needs to be set! Exiting ...
```
However, `NCEPLIBS_DIR` is set (and everything else that `source /work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/bin/setenv_nceplibs.sh` sets):
```
login3.stampede2(1117)$ export | grep NCEP
declare -x BACIO_LIB4="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/lib/libbacio_v2.2.0_4.a"
declare -x ESMFMKFILE="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/lib64/esmf.mk"
declare -x LD_LIBRARY_PATH="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/lib64:/opt/apps/intel18/netcdf/4.6.2/x86_64/lib:/opt/apps/intel18/impi18_0/pnetcdf/1.11.0/lib:/opt/apps/intel18/python3/3.7.0/lib:/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/lib:/opt/intel/debugger_2018/libipt/intel64/lib:/opt/intel/debugger_2018/iga/lib:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64:/opt/apps/gcc/6.3.0/lib64:/opt/apps/gcc/6.3.0/lib:/opt/apps/libfabric/1.7.0/lib"
declare -x NCEPLIBS_DIR="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0"
declare -x NEMSIO_INC="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/include"
declare -x NEMSIO_LIB="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/lib/libnemsio_v2.3.0.a"
declare -x PATH="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/bin:/opt/apps/xalt/xalt/bin:/opt/apps/intel18/netcdf/4.6.2/x86_64/bin:/opt/apps/intel18/impi18_0/pnetcdf/1.11.0/bin:/opt/apps/intel18/python3/3.7.0/bin:/opt/apps/intel18/impi/18.0.2/bin:/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin:/opt/apps/cmake/3.16.1/bin:/opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64:/opt/apps/gcc/6.3.0/bin:/opt/apps/autotools/1.1/bin:/opt/apps/git/2.24.1/bin:/opt/apps/libfabric/1.7.0/bin:/home1/06146/tg854455/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/dell/srvadmin/bin:."
declare -x SP_LIBd="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/lib/libsp_v2.1.0_d.a"
declare -x W3EMC_LIBd="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/lib/libw3emc_v2.5.0_d.a"
declare -x W3NCO_LIBd="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/lib/libw3nco_v2.1.0_d.a"
```

**Comment by climbfuji** [comment]
I'll be out for a run for an hour or so.

**Comment by uturuncoglu** [comment]
@climbfuji this is fixed in new version of interface. So, it won't exit anymore. Could you try with `ufs-release-v1.1` branch of FV3 interface.

**Comment by uturuncoglu** [comment]
A smile command to run test suit (at least part of it) is `./create_test --xml-testlist ../../src/model/FV3/cime/cime_config/testlist.xml --xml-machine stampede2-skx --workflow ufs-mrweather_wo_post -j 4 --walltime 01:00:00 --xml-category prealpha_p1` so you could change category part to `prealpha_p2` and `prealpha_p3` to run other pieces

**Comment by climbfuji** [comment]
This is what I get with hash
```
commit 49b015495e8e86cc19a685c56e8bc8dba790188d (HEAD, origin/ufs-release-v1.1)
Author: uturuncoglu <turuncu@ucar.edu>
Date:   Wed Sep 30 11:52:33 2020 -0600

    fix issue related with NCEPLIBS
```
of the fv3gfs cime interface using your command above:
```
...
Finished SHAREDLIB_BUILD for test SMS_Lh3_D.C96.GFSv16beta.stampede2-skx_intel in 3.246279 seconds (FAIL). [COMPLETED 4 of 6]
    Case dir: /scratch/06146/tg854455/SMS_Lh3_D.C96.GFSv16beta.stampede2-skx_intel.20200930_141114_31bh9m
    Errors were:
        Building test for SMS in directory /scratch/06146/tg854455/SMS_Lh3_D.C96.GFSv16beta.stampede2-skx_intel.20200930_141114_31bh9m
        ERROR: nceplibs_dir environment variable need to be set to process raw input data!

Starting SHAREDLIB_BUILD for test ERS_Lh11.C96.GFSv15p2.stampede2-skx_intel with 1 procs
Finished SHAREDLIB_BUILD for test ERS_Lh11.C96.GFSv15p2.stampede2-skx_intel in 3.326184 seconds (FAIL). [COMPLETED 5 of 6]
    Case dir: /scratch/06146/tg854455/ERS_Lh11.C96.GFSv15p2.stampede2-skx_intel.20200930_141114_31bh9m
    Errors were:
        Building test for ERS in directory /scratch/06146/tg854455/ERS_Lh11.C96.GFSv15p2.stampede2-skx_intel.20200930_141114_31bh9m
        ERROR: nceplibs_dir environment variable need to be set to process raw input data!

Starting SHAREDLIB_BUILD for test ERS_Lh11.C96.GFSv16beta.stampede2-skx_intel with 1 procs
Finished SHAREDLIB_BUILD for test ERS_Lh11.C96.GFSv16beta.stampede2-skx_intel in 3.834698 seconds (FAIL). [COMPLETED 6 of 6]
    Case dir: /scratch/06146/tg854455/ERS_Lh11.C96.GFSv16beta.stampede2-skx_intel.20200930_141114_31bh9m
    Errors were:
        Building test for ERS in directory /scratch/06146/tg854455/ERS_Lh11.C96.GFSv16beta.stampede2-skx_intel.20200930_141114_31bh9m
        ERROR: nceplibs_dir environment variable need to be set to process raw input data!

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL SMS_Lh3.C96.GFSv15p2.stampede2-skx_intel (phase SHAREDLIB_BUILD)
    Case dir: /scratch/06146/tg854455/SMS_Lh3.C96.GFSv15p2.stampede2-skx_intel.20200930_141114_31bh9m
FAIL SMS_Lh3.C96.GFSv16beta.stampede2-skx_intel (phase SHAREDLIB_BUILD)
    Case dir: /scratch/06146/tg854455/SMS_Lh3.C96.GFSv16beta.stampede2-skx_intel.20200930_141114_31bh9m
FAIL SMS_Lh3_D.C96.GFSv15p2.stampede2-skx_intel (phase SHAREDLIB_BUILD)
    Case dir: /scratch/06146/tg854455/SMS_Lh3_D.C96.GFSv15p2.stampede2-skx_intel.20200930_141114_31bh9m
FAIL SMS_Lh3_D.C96.GFSv16beta.stampede2-skx_intel (phase SHAREDLIB_BUILD)
    Case dir: /scratch/06146/tg854455/SMS_Lh3_D.C96.GFSv16beta.stampede2-skx_intel.20200930_141114_31bh9m
FAIL ERS_Lh11.C96.GFSv15p2.stampede2-skx_intel (phase SHAREDLIB_BUILD)
    Case dir: /scratch/06146/tg854455/ERS_Lh11.C96.GFSv15p2.stampede2-skx_intel.20200930_141114_31bh9m
FAIL ERS_Lh11.C96.GFSv16beta.stampede2-skx_intel (phase SHAREDLIB_BUILD)
    Case dir: /scratch/06146/tg854455/ERS_Lh11.C96.GFSv16beta.stampede2-skx_intel.20200930_141114_31bh9m
```
I have:
```
login3.stampede2(1132)$ export | grep -ie nceplibs_dir
declare -x NCEPLIBS_DIR="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0"
```

**Comment by uturuncoglu** [comment]
@climbfuji So, you have NCEPLIBS_DIR defined but you are still getting error. Right?

**Comment by uturuncoglu** [comment]
@climbfuji could you pull that branch again and test it. I found a typo issue and fix it.

**Comment by uturuncoglu** [comment]
Sorry, I closed and opened again. Let me know if it fix the problem.

**Comment by climbfuji** [comment]
Thanks, finally getting around to test this. It looks better, but I'll wait until part 1 finishes before giving green light.

**Comment by climbfuji** [comment]
Yes, I think this is correct now. Should I close this PR, given that you already updated the branch in the fv3gfs interface?

**Comment by climbfuji** [comment]
Glad I didn't close the PR. The next error is now:
```
login3.stampede2(1146)$ cat /scratch/06146/tg854455/SMS_Lh3.C96.GFSv16beta.stampede2-skx_intel.20200930_161748_jvr4yj/test.SMS_Lh3.C96.GFSv16beta.stampede2-skx_intel.20200930_161748_jvr4yj
Running test for SMS
WARNING: Found difference in test HIST_N: case: $STOP_N original value -999
doing an 3 nhours startup test, no restarts written
ERROR: Undefined env var 'UFS_INPUT'
```
and, as before, I did set `UFS_INPUT` and `UFS_SCRATCH` as required.
```
login3.stampede2(1147)$ export | grep UFS
declare -x UFS_DRIVER="nems"
declare -x UFS_INPUT="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-input"
declare -x UFS_SCRATCH="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch"
```

**Comment by uturuncoglu** [comment]
@climbfuji i am not sure why you are getting this error. Could you create a fresh case and try again? If it happens again, please let me know the commands that you use. I could try to reproduce on Stampede.

**Comment by climbfuji** [comment]
@uturuncoglu We may not need this anymore (see below), but this is the exact sequence of what I did on stampede, and it is still not working (latest version of the app, additionally I checked out the head of origin/ufs-release-v1.1 in src/model/FV3/cime to make sure I have all the latest code).
```
export UFS_SCRATCH=/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch
export UFS_INPUT=/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-input
export UFS_DRIVER=nems
export CIME_MODEL=ufs
export PROJECT=TG-MCA95C006

. /work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0/bin/setenv_nceplibs.sh

cd cime/scripts
./create_test --xml-testlist ../../src/model/FV3/cime/cime_config/testlist.xml --xml-machine stampede2-skx --workflow ufs-mrweather_wo_post -j 4 --walltime 01:00:00 --xml-category prealpha_p1
```
In any case, we decided to give up on running the regression tests on Stampede. Instead, we will manually run C96, C384 and C786 tests (if we get the larger jobs through with our tiny allocations). We will also do the GST at C96 resolution. If those pass, we consider stampede as good to go. After all, it is a level-2 (configurable, limited testing) and not a level-1 (pre-configured, fully regression testing) platform.

**Comment by climbfuji** [comment]
It turns out that this problem does not only afect the regression tests, but also regular end-to-end runs of the app. I have the following in my environment:
```
login2.stampede2(1046)$ export | grep UFS
declare -x UFS_DRIVER="nems"
declare -x UFS_INPUT="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-input"
declare -x UFS_SCRATCH="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch"
```
and while `chgres` works, the model run fails with
```
login2.stampede2(1045)$ cat run.ufs-mrweather-app-workflow.c96
ERROR: Undefined env var 'UFS_INPUT'
```
I remember vaguely that there is something in the documentation to add stuff to `.bashrc`. For testing, I added
```
export UFS_INPUT="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-input"
export UFS_SCRATCH="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch"
```
to my `.bashrc` and submitted another job. This will take several hours to get through the queue.

Hopefully this works, but nobody should ever have to add anything to `.bashrc` to make an application work.

**Comment by climbfuji** [comment]
> It turns out that this problem does not only afect the regression tests, but also regular end-to-end runs of the app. I have the following in my environment:
> 
> ```
> login2.stampede2(1046)$ export | grep UFS
> declare -x UFS_DRIVER="nems"
> declare -x UFS_INPUT="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-input"
> declare -x UFS_SCRATCH="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch"
> ```
> 
> and while `chgres` works, the model run fails with
> 
> ```
> login2.stampede2(1045)$ cat run.ufs-mrweather-app-workflow.c96
> ERROR: Undefined env var 'UFS_INPUT'
> ```
> 
> I remember vaguely that there is something in the documentation to add stuff to `.bashrc`. For testing, I added
> 
> ```
> export UFS_INPUT="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-input"
> export UFS_SCRATCH="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch"
> ```
> 
> to my `.bashrc` and submitted another job. This will take several hours to get through the queue.
> 
> Hopefully this works, but nobody should ever have to add anything to `.bashrc` to make an application work.

Update. I just realized that chgres also failed (silently), complaining about `NCEPLIBS_DIR` not being set. Of course it is set in my environment. I added it to my `.bashrc` as well and started another round of tests.

**Comment by ligiabernardet** [comment]
Maybe this helps?
Doc says:

On some systems (Stampede2, for example), you MUST source this file in your
.bashrc or equivalent script in order for compute nodes to find it. For
example, you would add the following to your .bashrc:

$ source $WORK/NCEPLIBS-ufs-v1.1.0/bin/setenv_nceplibs.sh

**Comment by climbfuji** [comment]
Ok, when I add
```
export UFS_INPUT="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-input"
export UFS_SCRATCH="/work/06146/tg854455/stampede2/ufs-mrweather-app/ufs-scratch"
export NCEPLIBS_DIR="/work/06146/tg854455/stampede2/NCEPLIBS-ufs-v1.1.0"
```
to my `.bashrc`, I get past chgres and the model run, post is still queued.

This is not how it should be, but I guess we have to live with it for this release.

I strongly oppose this statement in our documentation:
```
The recommended best practice to set the $UFS_SCRATCH and $UFS_INPUT environment variables and source the NCEPLIBS provided shell script setenv_nceplibs.sh|.csh is to add the above commands to a startup script such as $HOME/.bashrc (Bash shell) or $HOME/.tcshrc (Tcsh shell). These files are executed automatically when you start a new shell so that you do not need to re-define them during each login.
```
This is *not* the recommended practice - it is completely against the recommended practice! If every application I am running on an HPC forces me to add junk to my `.bashrc`, then it's only a question of time when something gets screwed up. User should set environment variables, and the job submission script should use the built-in Slurm/PBS/... functions to pass environment variables through the schedule (e.g. for slurm, `srun --export=...`).

I don't want to change the way this works for the release, but can we please rewrite the documentation to say that the recommended practice is to set environment variables as described above, but that unfortunately on certain systems the app requires to add x, y and z to `.bashrc`? @ligiabernardet @uturuncoglu @jedwards4b

**Comment by uturuncoglu** [comment]
@climbfuji @ligiabernardet i am not sure the source of the problem but stampede has lots of restrictions and if you want to remove that part of the documentation, it could be added as known issues. What do you think?

**Comment by climbfuji** [comment]
> @climbfuji @ligiabernardet i am not sure the source of the problem but stampede has lots of restrictions and if you want to remove that part of the documentation, it could be added as known issues. What do you think?

I can suggest a rewording of the offending paragraph. I'll also try to find the text that Ligia quoted and add that UFS_INPUT and UFS_SCRATCH are also required in `.bashrc`.

**Comment by climbfuji** [comment]
Documentation update was merged (https://github.com/ufs-community/ufs-mrweather-app/pull/217), problem solved.
