### ISSUE TITLE
Question (not yet an issue): gfortran-10 flags in CIME?

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#215]
For supporting gfortran-10, we had to add the following code in ufs-weather-model's `cmake/GNU.cmake`.
```
# For gfortran-10+ backward compatibility
if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "GNU" AND ${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER 9.9)
  set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -w -fallow-argument-mismatch -fallow-invalid-boz")
endif()
```
I don't see these flags anywhere in the CIME config:
```
heinzeller-lt:ufs-mrweather-app-release-public-v1 dom.heinzeller$ grep -Rie 'fallow-argument-mismatch' *
src/post/sorc/ncep_post.fd/CMakeLists.txt:  set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -w -fallow-argument-mismatch")
src/model/cmake/GNU.cmake:  set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -w -fallow-argument-mismatch -fallow-invalid-boz")
src/model/FV3/ccpp/CMakeLists.txt:    set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -w -fallow-argument-mismatch -fallow-invalid-boz")
```
The trouble is that we can't just add them to the GNU flags as default, because these flags are not recognized by gfortran 9.x and earlier.

Question: I believe we need to add them somewhere in the CIME config, and only if gfortran-10+ is used (auto-detect!), but I may be wrong. And certainly more than happy to be corrected.

**Comment by rsdunlapiv** [comment]
@climbfuji another option here is to list gfortran-10 as an unsupported compiler

**Comment by jedwards4b** [comment]
@climbfuji we don't have a way to distinguish between compiler versions unless we define a new compiler, we currently define compiler "gnu" we could introduce a new compiler "gnu10".

**Comment by ligiabernardet** [comment]
I would be glad to add to the documentation to explain how to patch the CIME config_compilers.xml file

**Comment by jedwards4b** [comment]
I think maybe the lines at 58-60 are what allows those variables to be resolved, can you try moving them to be above 
line 33?

**Comment by climbfuji** [comment]
It works if I make the following change to the top-level CMakeLists.txt in the ufs-weather-model:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b35eb44..c06d686 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -21,6 +21,11 @@ find_package(ESMF REQUIRED)
 
 include(${PROJECT_SOURCE_DIR}/cmake/configure_${CMAKE_Platform}.cmake)
 
+if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "GNU" AND ${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER 9.9)
+  set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -w -fallow-argument-mismatch -fallow-invalid-boz")
+  message(STATUS "Adjusting CMAKE_Fortran_FLAGS for gfortran-10 compatibility: '${CMAKE_Fortran_FLAGS}'")
+endif()
+
 if(NOT DEFINED PHYS)
   set(PHYS gfs)
 endif()
```
I don't think this code should be committed, because it's totally against the structure of the build system. It should really go into `configure_cime.cmake`, I don't understand why this is parsed differently (twice maybe, and it's the first time that fails because it is not the actual cmake build call?)

**Comment by climbfuji** [comment]
Hmm I am confused by your line numbers, hopefully I am looking at the same files. I see the following in the top-level CMakeLists.txt:
```
set(CMAKE_C_COMPILER $ENV{CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER $ENV{CMAKE_CXX_COMPILER})
set(CMAKE_Fortran_COMPILER $ENV{CMAKE_Fortran_COMPILER})
set(CMAKE_Platform $ENV{CMAKE_Platform})

project(NEMSfv3gfs C CXX Fortran)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)
find_package(MPI REQUIRED)
find_package(ESMF REQUIRED)

include(${PROJECT_SOURCE_DIR}/cmake/configure_${CMAKE_Platform}.cmake)
```
This is line 22. Are you looking at the release/public-v1 code?

This suggests that `CMAKE_Fortran_COMPILER` etc is defined before `configure_cime.cmake` is imported.

**Comment by climbfuji** [comment]
I understand it now. The culprit is right here:
```
Calling cmake  -DCOMPILER=gnu  -DMPILIB=mpich  -DDEBUG=FALSE  -DCCPP=ON -DSUITES=FV3_GFS_v15p2,FV3_GFS_v15p2_no_nsst  -DMPI=ON  -DSTATIC=ON  -DOPENMP=OFF  -DNETCDF_DIR=/usr/local/ufs-release-v1.1.0/llvm  -C /Users/dom/scratch/ufs-mrweather-app/UFS_SCRATCH/ufs-mrweather-app-workflow.c96.llvm/bld/atm/obj/cmake/configure_cime.cmake /Users/dom/scratch/ufs-mrweather-app/UFS_SCRATCH/ufs-mrweather-app-workflow.c96.llvm/bld/atm/obj
```
The `-C` means, according to the `cmake` help, means:
```
  -C <initial-cache>           = Pre-load a script to populate the cache.
```
So this file is parsed before cmake ever looks at the top-level `CMakeLists.txt` (which then parses it again). Why is this done?

**Comment by jedwards4b** [comment]
Probably a stab in the dark in early development,  try removing it.

**Comment by climbfuji** [comment]
gfortran-10 support is already in v1.1 of NCEPLIBS-external, NCEPLIBS and ufs-weather-model. Just not yet in CIME. But I think removing the `-C` line in buildlib solves the problem.

**Comment by climbfuji** [comment]
Remember v2 is for the December UFS Short-Range Weather App v1.0 release.

v1.1 (using the release/public-v1 branches for development, tags ufs-v1.1.0) is for the MRW App release v1.1.

**Comment by uturuncoglu** [comment]
@climbfuji do you want to close this issue?

**Comment by climbfuji** [comment]
Closed via https://github.com/ESCOMP/FV3GFS_interface/pull/15 - thanks @uturuncoglu and @jedwards4b for your help.
