### ISSUE TITLE
Finalize CCPP Technical Documentation for the MR Weather app release

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#22]
The CCPP Technical Documentation is in good shape for the release but will need updates [https://github.com/NCAR/ccpp-doc/tree/master/CCPPtechnical].  In particular, the following aspects need to be updated:

- Reduce/remove information regarding the UFS Weather Model since it will be covered elsewhere for this release
- Update list of parameterizations and suites for release
- Add documentation about automatic unit conversions

@ligiabernardet @JulieSchramm

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet  Since CCPP is marked complete and tagged. Can we close this?

**Comment by ligiabernardet** [comment]
We cannot close this.
CCPP Tch Doc still needs minor updates.
FYI It is a separate repo called ccpp-doc (not ccpp-physics or
ccpp-framework). This separate repo is not part of the Weather Model, so it
will not slow down the tag creation.

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet status of this?

**Comment by ligiabernardet** [comment]
It is on my Sunday to-do list.

**Comment by ligiabernardet** [comment]
The CCPP TechDoc has been finalized and a PR has been submitted (https://github.com/NCAR/ccpp-doc/pull/18). Awaiting review and plan to merge on Monday 3/9.

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet status? Are we satisfied?

**Comment by ligiabernardet** [comment]
The PR has been reviewed/accepted. I will update the RTD next.

**Comment by ligiabernardet** [comment]
The documentation is in place now at https://ccpp-techdoc.readthedocs.io/en/v4.0/.
