### ISSUE TITLE
Clean up branches and update master from release/public-v1

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#220]
Do we still need branches `documentation`, `ufs-release-v1.0`, `ufs-release-v1.1` ?

I understand that the release branch for the MRW 1.x.y releases is release/public-v1.

Also, the documentation in release/public-v1 is up to date and must be brought back to master. Should I take care of that?

**Comment by uturuncoglu** [comment]
@climbfuji I think we don't need them.

**Comment by climbfuji** [comment]
> @climbfuji I think we don't need them.

Thanks. I'll delete `documentation`, `ufs-release-v1.0`, `ufs-release-v1.1`.

I'll also create a PR to update `master` from `release/publicc-v1`.

**Comment by ligiabernardet** [comment]
Dom, your course of action sounds good to me.

**Comment by climbfuji** [comment]
The PR is ready and straightforward: https://github.com/ufs-community/ufs-mrweather-app/pull/221

**Comment by climbfuji** [comment]
All done.
