### ISSUE TITLE
missing co2 fixed file for 2021

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-mrweather-app#225]
There is an error message related to downloading co2 fixed file for 2021 when running MRW APP 1.1 on stampede:

Trying to download file: 'global/fix/fix_am.v20191213/fix_co2_proj/global_co2historicaldata_2021.txt' to path '/scratch/07859/tg871583/inputs/ufs_inputdata/global/fix/fix_am.v20191213/fix_co2_proj/global_co2historicaldata_2021.txt' using FTP protocol.
ERROR from ftp server, trying next server
Checking server None with protocol None
Setting Environment OMP_STACKSIZE=256M
Setting Environment ESMF_RUNTIME_PROFILE=ON
Setting Environment ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
Client protocol None not enabled
ERROR: Could not find all inputdata on any server
login4.stampede2(858)$

**Comment by ligiabernardet** [comment]
@KateFriedman-NOAA @arunchawla-NOAA Can someone from EMC update the ftp site that contains the files needed for the UFS MRW App public release with the content for 2021?

**Comment by KateFriedman-NOAA** [comment]
@ligiabernardet Certainly! Done:

https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/MRW/fix/fix_am/co2dat_4a/global_co2historicaldata_2019.txt
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/MRW/fix/fix_am/co2dat_4a/global_co2historicaldata_2020.txt_proj_u
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/MRW/fix/fix_am/co2dat_4a/global_co2historicaldata_2021.txt_proj
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/MRW/fix/fix_am/fix_co2_proj/global_co2historicaldata_2021.txt
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/MRW/fix/fix_am/fix_co2_update/global_co2historicaldata_2020.txt

**Comment by ligiabernardet** [comment]
Thanks!
@panll  Let us know if this solves the problem and the issue can be closed.

**Comment by panll** [comment]
Thanks! @ligiabernardet 
@KateFriedman-NOAA 
Is it possible put the co2 2021 file at
https://ftp.emc.ncep.noaa.gov/EIB/UFS/global/fix/fix_am.v20191213/fix_co2_proj/

MRW v1.1 uses this directory to download the co2 files in cime.

Thanks!

**Comment by KateFriedman-NOAA** [comment]
@panll Certainly but I'll mention first that those fix folders have a timestamp attached to them so technically I shouldn't add fix files created after those dates to that set. But since these are entirely new files they won't change existing files so I guess it's ok. Anywho, I'll go ahead and add them to that set too. Will confirm when they are there.

**Comment by KateFriedman-NOAA** [comment]
@panll The 2021 co2 fix files are now in that set as well:

https://ftp.emc.ncep.noaa.gov/EIB/UFS/global/fix/fix_am.v20191213/co2dat_4a/global_co2historicaldata_2019.txt
https://ftp.emc.ncep.noaa.gov/EIB/UFS/global/fix/fix_am.v20191213/co2dat_4a/global_co2historicaldata_2020.txt_proj_u
https://ftp.emc.ncep.noaa.gov/EIB/UFS/global/fix/fix_am.v20191213/co2dat_4a/global_co2historicaldata_2021.txt_proj
https://ftp.emc.ncep.noaa.gov/EIB/UFS/global/fix/fix_am.v20191213/fix_co2_proj/global_co2historicaldata_2021.txt
https://ftp.emc.ncep.noaa.gov/EIB/UFS/global/fix/fix_am.v20191213/fix_co2_update/global_co2historicaldata_2020.txt

**Comment by panll** [comment]
I saw the file. Thanks! @KateFriedman-NOAA 
It's tested on Stampede and works fine.
Thanks!

**Comment by KateFriedman-NOAA** [comment]
@ligiabernardet @panll There is an effort going on to clean up the EMC FTP server. May the following folder now be removed?

https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/MRW/

Let me know, thanks!

**Comment by ligiabernardet** [comment]
Yes. Thanks for asking.

**Comment by KateFriedman-NOAA** [comment]
Great, I have now removed that folder. Thanks for the quick reply @ligiabernardet !
