### ISSUE TITLE
Need to finalize the UFS Weather Model User's Guide

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#23]
The UFS Weather Model User's Guide is being developed as a set of Google Docs in folder [https://drive.google.com/drive/folders/1l1wQORiL8jhJPHUqQOdfeFdWNeD-gqIj]. This will be transitioned to Sphinx once it is more fleshed out - the Sphinx framework is here [https://github.com/ufs-community/ufs-weather-model/tree/documentation/doc/UsersGuide].

The UFS Weather Model User's Guide is a component of the UFS Medium-Range Weather App documentation.

Current status of the various chapters:

- Introduction (done, no changes requested at this time) @ligiabernardet 
- Platform support (not started) @climbfuji 
- Code overview (started, needs revision) @llpcarson @julieschramm
- Inputs and Outputs (started, needs additions and revisions) @llpcarson @julieschramm @climbfuji @KateFriedman-NOAA 
- SDF and namelist (not started) @llpcarson @julieschramm
- FAQ  (not started) @climbfuji 
- Contributing development (not started but there are a lot of materials around) @junwang-noaa @DusanJovic-NOAA 
-  Compiling the WM code without an application done, no changes requested at this time) @DusanJovic-NOAA @junwang-noaa 
– Regression tests for contributing code (not started but there are a lot of materials around) @junwang-noaa @DusanJovic-NOAA 
- GIt/GitHub  (not started but there are a lot of materials around) @junwang-noaa @DusanJovic-NOAA 
- Transitioning from VLab  (not started but there are a lot of materials around) @junwang-noaa @DusanJovic-NOAA 
- Glossary (draft complete; needs update once other chapters are available) @ligiabernardet 
- Acronyms (draft complete; needs update once other chapters are available) @ligiabernardet 

Note: There will be no CIME-related information in this User's Guide. All CIME-related information will be in the UFS MR Weather App UG because not all applications that use the UFS Weather Model use CIME.

**Comment by ligiabernardet** [comment]
The WM UG is in good shape. Source code is at https://github.com/ufs-community/ufs-weather-model/blob/documentation/doc/UsersGuide and the display is at https://ufs-mr-weather-app.readthedocs.io/projects/ufs-weather-model/en/latest/index.html. Still to do:

- Decide how versioning of NCEP Libraries and the UFS WM will be described.
- Add chapters on "contributing development" and "regression tests" (EMC is developing this under @valbonakunkel-noaa coordination). A PR is already under review.
- Add content to the FAQ (there is flexibility on how much/what to add).
- Go thru a more extensive collective review,
- Merge from current location (documentation branch) onto ufs_public_release branch

**Comment by ligiabernardet** [comment]
The UFS WM is ready for an initial review (even though there are still placeholders). PLEASE TAKE A LOOK AND SEND US FEEDBACK. 

Source code is at https://github.com/ufs-community/ufs-weather-model/blob/documentation/doc/UsersGuide and the display is at https://ufs-mr-weather-app.readthedocs.io/projects/ufs-weather-model/en/latest/index.html. Still to do:

- Add chapters on "contributing development" and "regression tests" (EMC is developing this under @valbonakunkel-noaa coordination). A PR is already under review (https://github.com/ufs-community/ufs-weather-model/pull/32).
- Add content to the FAQ (there is flexibility on how much/what to add).
- Go thru a more extensive collective review
- Merge from current location (documentation branch) onto ufs_public_release branch

**Comment by ceceliadid** [comment]
@ligiabernardet @llpcarson There are a number of issues that are still present in the WM UG. The focus here is on the pages about the build.

I don't think section 6.1 "Prerequisite libraries" makes sense under "Contributing Development." I think it should be moved into a section that includes 7, Compiling the Code without an Application.

It looks like section 6.1 and section 7 both need to be updated to reflect the current terminiology and platforms in Supported Platforms.

It would be helpful if the section Compiling Code without an Application could either indicate or point users to a page that told them which compilers were supported/tested on which platforms so they knew how to set the COMPILE variable and CMAKE_Platform var.

It also appears that users must set CMAKE_Platform (at least I had to on Stampede2). If that's the case it should probably be mentioned next to the COMPILE var as something the user needs to set, not an optional thing.

The code section that shows all the CMAKE variables should probably be shown in the same format as setting the other variables, e.g. export CMAKE_Platform=<if not set the default is linux.${COMPILER}> 
Right now it looks like a code section since it's in green but it isn't actually a code section that people can copy.

I can probably do some of this if you agree to the changes.

**Comment by ceceliadid** [comment]
Sorry, one more thing - it looks like Section 5 should either be filled in or removed.

**Comment by ceceliadid** [comment]
And the WM UG should be clear about which tag of NCEPLIBS and NCEPLIBS-external should be used with the v1.0.0 version of the WM.

**Comment by climbfuji** [comment]
This will be version 1.0.0 of both - we will make this match.

**Comment by ligiabernardet** [comment]
@ceceliadid Your proposed updates are okay with me. I want to go ahead and remove Section 5; we may fill it for later releases. We would be glad to make the proposed updates, but since you offered, please go ahead and propose the changes. That chapter was written by @DusanJovic-NOAA, so he may want to review it as well. Or just let us know and we can make the changes. 
Also, Laurie has setup a Google Doc to collect feedback about the documentation. So, if it is easier, you can put any additional feedback here: https://docs.google.com/document/d/1QhXBCOUjDDmU40K1liimgSkkMUtjOHUswY1nYAD9kgg/edit#heading=h.151p9nafxhti

**Comment by ceceliadid** [comment]
@ligiabernardet Okay. I will put together a new section that includes both 6.1 and 7. I would suggest putting it right after section 2. If you think there's reason for it to go later, it could also be just before Contributing Development. I'll do it in a google doc , I would rather not do the PR.

**Comment by ligiabernardet** [comment]
To me it seems better for the new section to go before "Contributing
Development".
Let me know how far you get and I can do the PR.
Ligia

**Comment by ceceliadid** [comment]
Okay, here it is:
https://docs.google.com/document/d/16nISxaAj_jnXTK2xu9HwOkV7E2N4-TXCMfeQIZuqLWk/edit?usp=sharing

I'd feel better if @kgerheiser or @mark-a-potts or @climbfuji or @DusanJovic-NOAA 
could review it.

**Comment by ligiabernardet** [comment]
There is an open PR for the UFS WM User's Guide. It incorporates all feedback received so far. This User's Guide is ready for a final review.
