### ISSUE TITLE
Read The Docs "latest" does not point to HEAD of master branch

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-mrweather-app#236]
The MRW App documentation on ReadTheDocs is not pointing to the HEAD of the master branch (and therefore is not showing the changes from my most recent doc PR). 
I can fix the problem easily if I'm granted RTD account access. Otherwise, an account administrator needs to go into the MRW App RTD account/project --> Admin --> Advanced Settings. Then, change the Default Version and Default Branch to master.

**Comment by ligiabernardet** [comment]
I added EPIC-AUS as a maintainer for this project in RTD.
