### ISSUE TITLE
Determine a layout for the UFS user support forum page

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-mrweather-app#25]
- [Draft document on Drive](https://docs.google.com/document/d/1WC3RRfwDsTwCaEIeVHT67pXQPNAQ85CTL5AGxcW0y4I/edit)

**Comment by jwolff-ncar** [comment]
For reference:
CESM forum: https://xenforo.cgd.ucar.edu/cesm/
WRF forum: http://wrfforum.com/index.php

**Comment by jwolff-ncar** [comment]
To start, the following subforums will be created:

**Announcements**
 - Check here for announcements regarding upcoming releases, tutorials, workshops, meetings, or relevant conferences
**Getting Started**
 - Check here for links to other documentation and Github wikis. For user support, please post your question to the most appropriate forum topic below.
**Medium-range Weather Application**
 - The Medium Range Weather Application user support forum is focused on...and has a user-friendly workflow [Common Infrastructure for Modeling Earth (CIME) Case Control System (CCS)] and a portable build system
**Initialization**
 - This user support forum encompasses topics related to input data sets (ICs/BCs), pre-processing (using chgres_cube), etc.
**Atmosphere** 
 - Forum focused on support for the prognostic model based on the UFS global atmosphere with the Finite Volume Cubed Sphere (FV3) dynamical core. Interoperable atmospheric physics are supported through the use of the Common Community Physics Package (CCPP). 
**Postprocessing**
 - User support for the Unified Post Processor (link to existing help page)  

**Bug Reporting?**
 - Should this be done through github issues?
**Software Development Process**
 - (links to github wikis)

POCs on the subforum topics should feel free to suggest what they would like their "information" tag line to say to direct users to the best place to post their questions.

**Comment by mvertens** [comment]
@Jamie Wolff <jwolff@ucar.edu> - thanks this is really helpful to put it in
the issues.

**Comment by jwolff-ncar** [comment]
@ceceliadid Is the C&O team willing to add a tab at the top of the ufscommunity.org page to point directly to the support forums: forums.ufscommunity.org (not live yet but should be any day now)?

**Comment by ceceliadid** [comment]
Hi Jamie, we will make the support link either one of the top tabs or a support button that is highly visible on the landing page, or both. If it is a button it would be part of a new section on the website, probably right below the scrolling header, about the release. Bhavana is out for a couple of weeks and with limited time we will need to minimize her effort. We can talk about options when she is back, the week of the 17th.
In the longer term, we may want to think about a top tab that is not just a link out to the forum but has a submenu with other user resources like tutorials.

**Comment by ceceliadid** [comment]
@jwolff-ncar please look at this page which shows how we could include a button for the support forum on the wikis. I think many people will be accessing support from GitHub:
https://github.com/ufs-community/ufs-weather-model/wiki
What do you think?

**Comment by jwolff-ncar** [comment]
@ceceliadid That looks good -thanks for including that. I sent another inquiry this morning on when it will be live - should be any time now...

**Comment by ceceliadid** [comment]
@jwolff-ncar Sounds good. I also put a button for the mrw app support forum on that wiki. I can put a button for the build forum on the NCEPLIBS wiki if that makes sense to you and @climbfuji and anyone else who should weigh in.

**Comment by jwolff-ncar** [comment]
@ceceliadid Link folks to the forum from multiple locations makes a lot of sense to me. Thanks for setting that up.

**Comment by jwolff-ncar** [comment]
The support forum is now live! 
https://forums.ufscommunity.org/

Users must create a login to be able to post or answer questions. A few moderators will be given elevated permissions to move/tag questions as needed (I will work with a subset of people to set that up).

There will be a feedback page on the site soon (later today if not already). This will be monitored so feel free to post suggestions through that mechanism. Or, contact me directly.

**Comment by ceceliadid** [comment]
This is great! All the wiki buttons are pointed to the correct forums now.

**Comment by ceceliadid** [comment]
Hi @jwolff-ncar I noticed that some of the forums don't have any messages on them at all yet. Do you think it would be good to make sure that each one has at least a welcome message? People might hesitate to be the very first one to post.

**Comment by jwolff-ncar** [comment]
Each forum has a post that directs users to use the "New Topic" button to post a new thread. @ceceliadid Let me know if you do not think that is sufficient. I have not seen any other questions posted. Has the forum site been well communicated to those doing testing? How can I further help with that?

**Comment by jwolff-ncar** [comment]
I wanted to be sure you all knew that the support forum is now live: https://forums.ufscommunity.org/. Please have a look. 

We need to determine a list of SMEs that will be responsible for monitoring the forums. I have started a document that I would be most appreciative if others could have a look at and start filling in names. (https://docs.google.com/document/d/1GUwFpUIYZzxnUwyGmvqjf6-Ek_BWnvZI7EQssx29ReQ/edit#) Please just add names that you feel are appropriate at this time and I will take care of contacting anyone that is recommended for this role (or the organization contact point) to make sure that is in their scope of responsibilities. I will also follow up with all SMEs/moderators to make sure they know how to interact with the site.

Thanks for your help in this process. It is key to have a good number of SMEs monitoring the forum to ensure a positive experience for users as they spin up on the systems.

**Comment by ceceliadid** [comment]
Hi @jwolff-ncar I do have a few people working on the WM GST on Cheyenne so you may see some questions. I think the WM forum buttons are pretty obvious on the pages they're using and I also mentioned the forum on the questionnaire. Folks currently working on it have until 2/28 to finish the test so nothing may come through for a while. If I can get some testing started on the non-configured platforms that should produce more forum traffic.

I thought the posts you put in directing people to the new topic button looked good, thank you!

**Comment by ceceliadid** [comment]
Hi @jwolff-ncar we have a first look at the Support tab, here:
http://ufs-dev.rap.ucar.edu/
That's the dev site for the Portal. 

We'll go live with the Portal change next week when the release comes out. (The other changes on the page are still very much a work in progress.)

Do you think it's okay to close this ticket?

**Comment by arunchawla-NOAA** [comment]
@jwolff-ncar have the issues with subscribing to the portal been taken care of? And yes can this ticket be closed?

**Comment by jwolff-ncar** [comment]
Thanks @ceceliadid for adding the support tab and link to the forum. Looks good!

Just to be clear: there is no problem registering for the forum, which allows you to post/respond to questions on the forum. Everyone should do this! The subscription feature to "watch" a particular forum and receive an email message when something new is posted is what is not working as hoped. It functions in Drupal7 but not Drupal8. I will be presenting an alternative at the release meeting today. 

Since the forum is up and running, it is fine with me to close the ticket and keep tweaking the site as we move forward.
