### ISSUE TITLE
Add description of capabilities to pre-processing section of release two-pager

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#29]
@LarissaReames-NOAA 

Hi Larissa, could you please add information to the Input Files and Pre-Processing section of the release description here: 
https://docs.google.com/document/d/1e9XaF2snfV1j_HBDCQ9T2TNVNWY0uWFr-R8r6jCm_bE/edit#
along with any information you have about what case studies or examples will be included?

Thanks,
Cecelia

cc
@ligiabernardet 
@rsdunlapiv

**Comment by arunchawla-NOAA** [comment]
@LarissaReames-NOAA can you provide some information to this document. I know the information will not be final.

**Comment by ceceliadid** [comment]
@arunchawla-NOAA @LarissaReames-NOAA This task is complete as far as the two-pager goes, so I am closing. Since there is still ambiuity about what examples will be included in the release I will open another ticket for that.
