### ISSUE TITLE
CIME compset names for release 

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-mrweather-app#31]
Currently we have a single compset: UFS_Weather which uses the ccppv15 physics

We need to come up with names for two compsets - one for ccppv15 and one for ccppv16 and we need to think about a naming convention that will extend to other physics configurations.
I also think UFS_Weather is too long for an alias name.
How about:
FV3ccpp15
FV3ccpp16

**Comment by climbfuji** [comment]
In my opinion, the "ccpp" part of it is not important, because we are not providing ways to run the "ipd" version. Instead, I would prefer to have FV3v15p2 (or FV3GFSv15p2) and FV3v16beta (or FV3GFSv16beta). But the documentation team should also have a say here.

**Comment by ligiabernardet** [comment]
Please use GFSv15p2 and GFSv16beta to refer to the suites. It is important
not to use "GFS v16" because what we have today may not be what is
implemented operationally in GFS v16 in 2021.

Will the on/off of stochastic physics be configured through compsets? Or
will that be just instructions to users to change the namelist values?

**Comment by jedwards4b** [comment]
Which physics we use as well as whether we use stochastic physics can be toggled in a particular case.  Including them in a compset name is just a convenience for the user and for testing.  We could just have a single compset name and then the user would switch options in the case with
xmlchange commands.   Or we can have a new compset name for each combination of physics options (4 total at this time).   How about GFSv15p2, GFSv15p2sto, GFSv16beta, GFSv16betasto ?  To be clear - in any of these cases the user can still make changes to use a different ccpp or toggle stochastic physics.  Having separate names just allows the user to avoid a couple of steps in getting the configuration they desire.

**Comment by ligiabernardet** [comment]
@pjpegion Do you have any preference/input on how the stochastic is turned on (via CompSet or not) and the names proposed by @jedwards4b?

**Comment by jedwards4b** [comment]
@ligiabernardet is the toggle on/off of stochastic physics just a namelist change or is there also a build change involved?

**Comment by ligiabernardet** [comment]
It is a set of namelist changes. No build changes.

**Comment by jedwards4b** [comment]
In that case I propose that we have only two compsets and provide instructions to the user on how to toggle stochastic physics - should the default be on or off?

**Comment by pjpegion** [comment]
@jedwards4b @ligiabernardet I suggest instructions on how to modify the namelist for stochastic physics, not a separate compset, and the default should be off.

**Comment by arunchawla-NOAA** [comment]
I second @ligiabernardet suggestion of GFSv15 and GFSv16BETA as the two names (FV3 is only the dycore we are removing FV3GFS name where we can)

**Comment by rsdunlapiv** [comment]
@uturuncoglu needs to turn off stochastic physics as the default for all resolutions.

**Comment by uturuncoglu** [comment]
@rsdunlapiv I changed the default value of following options to **FALSE** to turn off stochastic physics but we still need to do [this](https://github.com/ufs-community/ufs-mrweather-app/issues/40#issuecomment-571330959) modification in buildnml in case of using stochastic physics and restart together.

**Comment by rsdunlapiv** [comment]
@uturuncoglu what do you mean by "update the model source?"  Update the version, or make code changes? 

@jedwards4b have the compset names been finalized?

**Comment by uturuncoglu** [comment]
@rsdunlapiv we need to update the model source but those changes are not the ufs_release branch yet. I am waiting for @pjpegion to merge those changes with ufs_release branch .

**Comment by rsdunlapiv** [comment]
The compset naming convention is complete.  The issue here about stochastic physics restarts is a separate issue that will not be addressed now.

**Comment by rsdunlapiv** [comment]
Merged with https://github.com/ufs-community/ufs-mrweather-app/pull/57
