### ISSUE TITLE
Some pre-release communication with university/external users about examples

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#32]
@arunchawla-NOAA @LarissaReames-NOAA @ligiabernardet The C&O team would like to gather some pre-release input on the kinds of examples most valuable to university/external users. We can provide a draft of that communication.

**Comment by arunchawla-NOAA** [comment]
@ceceliadid will this be different from the two pager?

**Comment by ceceliadid** [comment]
Yes.

**Comment by arunchawla-NOAA** [comment]
@ceceliadid what is the action item for this issue?

**Comment by ceceliadid** [comment]
@arunchawla-NOAA @LarissaReames-NOAA @ligiabernardet 1) understand what kinds of examples or case studies are currently planned to go out with the release; 2) finalize a questionnaire for some external folks about what is most useful to them example-wise  and distribute and 3) provide responses as feedback to the release team.  This week is mainly getting ready for AMS so I'm thinking of picking this task up again next week. It shouldn't hold anybody else up.

**Comment by arunchawla-NOAA** [comment]
@ceceliadid did this get done? Can we close this issue?

**Comment by ceceliadid** [comment]
@arunchawla-NOAA It can be closed. Not enough time to do anything but the minimum.
