### ISSUE TITLE
Complete Getting Started and GST pages on MRW app wiki

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#33]
@arunchawla-NOAA This needs to wait until the code base and documentation is ready, and a test is defined.

**Comment by ceceliadid** [comment]
@mvertens @rsdunlapiv @uturuncoglu On the WM GitHub wiki we have a Getting Started section that enables users to run a simple test. Is there a similar Getting Started page or guide that someone is already working on for the MR weather app, and if so is it somewhere where it can be looked at?

**Comment by ligiabernardet** [comment]
Under development:
https://ufs-mrapp.readthedocs.io/en/latest/quickstart/index.html

**Comment by ceceliadid** [comment]
Thanks @ligiabernardet So for the app there will be no Getting Started documentation on the wiki, it is all in the UG, is that right? 
For the initial app graduate student test, if we are going to do the CCN concentration change test to start, would it make sense to set up a C96 run for 24 hours with the 15p2 physics by just pointing people to the getting started MRW app documentation? Or would it make sense to set up a more canned case with those options already set?

**Comment by ceceliadid** [comment]
@LarissaReames-NOAA @ligiabernardet @junwang-noaa @mvertens @rsdunlapiv @arunchawla-NOAA
After discussion at the last Thurs documentation call, the following is the proposed plan for the app wiki pages and GST:
1. The app wiki will have a Getting Started section much like the WM Getting Started section, that will lead people through a specific example run and give them some images against which they can visually check results. I am assuming if the Dorian example is all set up that might be the best case to use, for say a 5-day run. I am thinking this content will be specific to the wiki.
2. The app wiki will have a GST section, again much like the WM GST page, that will build on the Getting Started area. It will begin with the person running the Getting Started example, and can then lead them through 1) changing the resolution and 2) changing the physics package. Any recommendations for specifics for the case would be appreciated. The students can re-run after each of these changes and compare results with the control.  In this way the test can demonstrate the additional flexibility that results from using the workflow. Again, I am thinking this content will be specific to the wiki.

I will start setting up the wiki based on above, unless there are any objections. I plan to pull from the app UG, but the instructions here can be simpler since they don't have to explain all options.

Is there documentation on how to set up the Dorian case?

**Comment by rsdunlapiv** [comment]
@ceceliadid what is the relationship of the documentation on the app wiki and the documentation on readthedocs?, e.g.:
https://ufs-mrapp.readthedocs.io/en/latest/quickstart.html

Will the wiki be used for specific tests cases, such as the GST, and readthedocs for general documentation?  It would be good to understand the "rule of thumb" for this distinction so we don't have a proliferation of documentation appearing in two different places.

**Comment by ceceliadid** [comment]
@rsdunlapiv Yes, the idea is that the wikis will be for a specific example that gets people running, described in a Getting Started section, GST pages, policies, and current developer information. The UG would be for more general information, and would describe all options. So there shouldn't be much overlap between the UGs and the wikis. That's the way things are set up for the WM and it seems like a pretty logical split.
- Cecelia

**Comment by arunchawla-NOAA** [comment]
@ceceliadid what do we want to do with this issue? We do not have enough time for GST for weather app. We can review during documentation sprint if anything is needed

**Comment by ceceliadid** [comment]
@arunchawla-NOAA I'm going to do it today and we can look at it tomorrow. I wanted to get the WM and build squared away first and did.

**Comment by arunchawla-NOAA** [comment]
@ceceliadid are we happy with this?

**Comment by arunchawla-NOAA** [comment]
@ceceliadid just went to the GST and the figure at the end is a broken link

https://github.com/ufs-community/ufs-mrweather-app/wiki/Graduate-Student-Test%3A-MR-Weather-App-CCN-Experiment

**Comment by ceceliadid** [comment]
@arunchawla-NOAA The app GST pages won't be ready until Monday. Had trouble getting image files off Stampede2 and just managed to do that this afternoon. Seems like kind of a weirdly configured machine. So both app viz sections, in Getting Started and GST, don't have those done yet.

**Comment by ceceliadid** [comment]
This is done now.
