### ISSUE TITLE
Write a two page description of the release

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#35]
@arunchawla-NOAA Write a two-pager describing the release. This should be useful for both internal and external release team communication.

**Comment by ceceliadid** [comment]
Here is the draft: https://docs.google.com/document/d/1e9XaF2snfV1j_HBDCQ9T2TNVNWY0uWFr-R8r6jCm_bE/edit#

**Comment by arunchawla-NOAA** [comment]
Can we close this issue?

**Comment by arunchawla-NOAA** [comment]
@ceceliadid if this is resolved to satisfaction then can we close this issue?

**Comment by ceceliadid** [comment]
@arunchawla-NOAA yes it can be closed now thanks.
