### ISSUE TITLE
Create a public schedule with major milestones for the release

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#36]
The schedule can be posted on the Portal. There are already milestones here that are important to acknowledge. Draft is here: https://drive.google.com/open?id=1bbT8kcxgagkTu4xmsU0zLLr64R561Do8B93VCnBJWWU

**Comment by arunchawla-NOAA** [comment]
We will make the first attempt at this and document it here

**Comment by arunchawla-NOAA** [comment]
An initial attempt at milestones has been created. These milestones have been connected to the different issues

**Comment by mvertens** [comment]
@Arun Chawla - NOAA Federal <arun.chawla@noaa.gov> @Louisa Nance
<nance@ucar.edu> - Thanks! This looks good to me.
