### ISSUE TITLE
Need documentation for NCEP Libs SuperProject

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#38]
We need to create documentation about how get the code and build it.
I suggest this is a standalone documentation and not part of the MR Weather User's Guide because it will be used by other apps.

**Comment by mvertens** [comment]
Here is my recommendation:
- getting the code should be in the quick start guide.
- building it on supported platforms should also be in the quick start
guide.
- porting it should be a pointer to the CIME documentation or another MR
Weather App specific documentation describing how to port and validate.
The CIME build is going to be used by the S2S app if they go with CIME -
but not by other apps. I am concerned about causing confusion with
different builds for the stand-alone versus the app.
This needs to be discussed with the release team leads in my opinion.

**Comment by kgerheiser** [comment]
I have created an initial Wiki page that describes how to build NCEPLIBS here: https://github.com/NOAA-EMC/NCEPLIBS/wiki/Cloning-and-Compiling-NCEPLIBS

**Comment by arunchawla-NOAA** [comment]
Thank you for this! Can we add a list of all the libraries that are being built here ?

**Comment by arunchawla-NOAA** [comment]
@mvertens just to clear up any confusion, this documentation is for all the libraries builds

**Comment by climbfuji** [comment]
Have a look, please, and correct as needed: https://github.com/NOAA-EMC/NCEPLIBS/wiki/Cloning-and-Compiling-NCEPLIBS
