### ISSUE TITLE
Need documentation for file model_configure

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#39]
@RatkoVasic-NOAA @DusanJovic-NOAA Would you be able to point us to existing documentation (or provide us with documentation) on file _model_configure_?

**Comment by ligiabernardet** [comment]
Thank you @DusanJovic-NOAA A trove of information!
@llpcarson @julieschramm

**Comment by ligiabernardet** [comment]
Here is what Dusan sent (for those that have access to VLab):
https://vlab.ncep.noaa.gov/redmine/projects/comfv3/wiki/_parameters_in_model_configure_

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet do you have someone to assign this to ?

**Comment by ligiabernardet** [comment]
@Dusan Jovic - NOAA Affiliate <dusan.jovic@noaa.gov> has provided
information.
@llpcarson Do we have all we need? If so, please close this issue.

**Comment by ligiabernardet** [comment]
@Dusan Jovic - NOAA Affiliate <dusan.jovic@noaa.gov>
We reviewed the documentation you provided about file model_configure. It
was very informative, but I am wondering if we can an extra step.
The documentation describes an example of model_configure but does not
describe all the options available.
For example, for variable output_grid, only one option is listed
(gaussian_grid). Are there other options that we should mention?
I left a list of questions for you in this Google Doc
<https://docs.google.com/document/d/1D7aupwMAjIdv_8eHiRtdkyad_o_f_eGmpGFIvBeZXcg/edit?usp=sharing>,
please scroll down to the model_configure section. Tks.

**Comment by ligiabernardet** [comment]
Documentation for file model_configure has been added to the UFS WM User's Guide.
