### ISSUE TITLE
Implement workflow error checking when user runs only part of the workflow

### ISSUE THREAD

**Issue by rsdunlapiv** [ufs-community/ufs-mrweather-app#41]
CIME has been extended to run only part of the workflow by either choosing a starting task in the middle of the workflow or by running only a single job.  This may lead the user into an inconsistent state, for example, if the user chooses to only run the forecast job, but chgres has not yet been run to produce initial conditions.

Explore how the CIME workflow XML can be extended to support special constraints, e.g., task X is dependent on the existence of a certain file in the run directory (or filename pattern).  Or, task Y can only be run if task Z has been run at least once previously.

**Comment by rsdunlapiv** [comment]
If user decides to explicitly run forecast without chgres, this is considered a user error.  The model should give an error that the input files are not there.

**Comment by ligiabernardet** [comment]
What about if the user previously ran chgres, and now he/she just wants to
run the model over and over? That should not be considered an error.
What about if the user got the (chgres-generated) ICs from a colleague
and he/she just wants to run the model? This is a realistic use case (if we
cannot support it this release, put it in the wish list).

**Comment by jedwards4b** [comment]
@ligiabernardet This is supported, we will need to provide documentation on the expected location and names of input files for the model.
