### ISSUE TITLE
Ensure CIME supports duplicate namelist variables

### ISSUE THREAD

**Issue by rsdunlapiv** [ufs-community/ufs-mrweather-app#44]
CIME must support duplicate namelist variables in XML since the same variable name can be used in different namelist groups.  @mvertens said that this is already done in CIME with an @notation in the XML file.  This needs to be verified before closing this issue.

**Comment by uturuncoglu** [comment]
I tested it and it is working.

**Comment by mvertens** [comment]
@Ufuk Turuncoglu <turuncu@ucar.edu> - can this issue be closed?

**Comment by uturuncoglu** [comment]
@mvertens yes. i am closing it.
