### ISSUE TITLE
NCEPLIBS: consistency of environment variables with UFS weather model

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#48]
We need to ensure consistency between the NCEPLIBS and the UFS weather model wrt environment variables used to detect/configure prerequisites and the libraries themselves.

Examples (please use the discussion below to add to the list):

**ESMF**

`ESMFMKFILE` is used for configuring the ESMF installation. The ESMF source code contains a file `cmake/findESMF.cmake` that parses this `esmf.mk` file and sets cmake environment variables.

Note that his is not a 100% match, since `esmf.mk` contains items like `CFLAGS=-Idir1 -Idir2 ...`, while cmake expects a list of directories to pass to `include_directories(...)`. We need to work around this and get in touch with the ESMF team to improve on this in future releases.

**netCDF**

The common (standard?) way is to set the environment variable `NETCDF` to point to the installation directory of netCDF. (There is also the option to call `nc-config`, but this requires having the netCDF bin directory in the `PATH` variable).

The UFS weather model expects `NETCDF` to be set, but currently has workarounds for platforms that set NETCDF_DIR instead (and these inconsistencies need to be addressed in the future together with the sysadmins).

For the UFS release, we should use `NETCDF` for both NCEPLIBS and ufs-weather-model.

**Comment by climbfuji** [comment]
Update: with https://github.com/NOAA-EMC/NCEPLIBS/pull/12, the NCEPLIBS umbrella build is looking for environment variables `NETCDF` and `ESMFMKFILE`, consistent with what the ufs-weather-model expects. I don't want to close the ticket at this point, because we may want to check a few more things (especially on NOAA machines that set the netCDF environment variables differently).

**Comment by arunchawla-NOAA** [comment]
@climbfuji @mark-a-potts and @kgerheiser what is the status of this?

**Comment by kgerheiser** [comment]
I think this is fixed. We look for `NETCDF` and `ESMFMKFILE`

**Comment by climbfuji** [comment]
Yes, the build looks for NETCDF, optionally NETCDF_FORTRAN (not sure if this is used anywhere), and ESMFMKFILE. Nothing else.
