### ISSUE TITLE
Creating a unified build for NCEPLIBS

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-mrweather-app#5]

**Comment by climbfuji** [comment]
Aye, will get in touch with Mark Potts & Co asap to have this ready.

**Comment by arunchawla-NOAA** [comment]
@climbfuji @mark-a-potts . Can this ticket be closed as the issues are being addressed in other tickets?

**Comment by climbfuji** [comment]
Ok with me!
