### ISSUE TITLE
Take down obsolete documentation/sites before this release to avoid confusion

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#50]
@arunchawla-NOAA @ligiabernardet @junwang-noaa @KateFriedman-NOAA 
There are a bunch of sites that should be scrubbed of out of date/misleading documentation before this release:
- the FV3GFS site on Vlab
- the main EMC website
- the UFS community site on Vlab
- the NGGPS community site
I can start identifying issues. If anyone else wants to start cleaning this up that's good too.

**Comment by ceceliadid** [comment]
As part of this task, make sure that any relevant material under documentation from the FV3GFS Vlab site is moved to current wiki or UG documentation.

**Comment by ligiabernardet** [comment]
@ceceliadid @llpcarson @KateFriedman-NOAA @arunchawla-NOAA @valbonakunkel-noaa I started a [Google Doc](https://docs.google.com/document/d/1hGhnoIMtAH5I0QeyAMNfH7RXL7zwiopjL3_Nh5cKFU8/edit#) to collect a list of documents that we may want to deprecate, along with some recommendations. Who   can help wrt removing some pages from VLab?

**Comment by KateFriedman-NOAA** [comment]
I can help with the fv3gfs VLab community pages (web & group) and likely some of the documents listed but I'll need to discuss that with Vijay and others at EMC before doing so.

Anything on the EMC website will need to be handled by @EricRogers-NOAA and Crystal Logan.

**Comment by EricRogers-NOAA** [comment]
We will be happy to remove or archive any obsolete global documentation on the EMC web site, provided that the responsible experts inside EMC provide new content to replace it. Crystal is the technical web expert and I am the Federal oversight manager for her, but obviously I am not an expert on everything that runs in the NCEP Production Suite

**Comment by ceceliadid** [comment]
Thanks @ligiabernardet  for putting the list together. I added an addiitonal site to the list, the EMC community site. I will contact @KateFriedman-NOAA  and @EricRogers-NOAA to take down pages that are not needed now.

**Comment by ligiabernardet** [comment]
@KateFriedman-NOAA Have you been able to discuss with Vijay and others at EMC about whether we can take down outdated VLab documentation listed in this [Google Doc]([url](https://docs.google.com/document/d/1hGhnoIMtAH5I0QeyAMNfH7RXL7zwiopjL3_Nh5cKFU8/edit#))?
@EricRogers-NOAA @ceceliadid Do you have any update on the possibility of updating some of the EMC pages? Or should we schedule this as a post-release activity?

**Comment by KateFriedman-NOAA** [comment]
@ligiabernardet Yes, I cleaned up the fv3gfs community pages on VLab and took the now-outdated documentation off the front pages. That info is now on pages for past releases.

Please see these pages now:

https://vlab.ncep.noaa.gov/web/fv3gfs/home
https://vlab.ncep.noaa.gov/group/fv3gfs

**Comment by EricRogers-NOAA** [comment]
Will this one be updated?

https://vlab.ncep.noaa.gov/web/gfs/home

Eric

**Comment by rsdunlapiv** [comment]
@KateFriedman-NOAA and @ligiabernardet is the term "FV3GFS" still meaningful (from the links Kate sent?)  Or is it UFS Atmosphere?

**Comment by arunchawla-NOAA** [comment]
ufs weather model and ufs mrweather app

Let us stick to that
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Comment by KateFriedman-NOAA** [comment]
Forgot about the GFS page, I'll update it too.

Kate Friedman (formerly Howard)
NOAA/NWS/NCEP/EMC Engineering and Implementation Branch

**Comment by arunchawla-NOAA** [comment]
@KateFriedman-NOAA @EricRogers-NOAA @ceceliadid @ligiabernardet 

Are we done with this scrub?

**Comment by KateFriedman-NOAA** [comment]
I cleaned the VLab pages for FV3GFS and GFS to remove (or relabel) out-dated info.

**Comment by arunchawla-NOAA** [comment]
@ceceliadid and @ligiabernardet can you confirm this is completed to satisfaction and there are no left over stragglers ? If all is good can you then close this issue?

**Comment by ceceliadid** [comment]
There are a few pages I want to take down today and then I will close.

**Comment by ceceliadid** [comment]
I am done. I took down some old NEMS and architecture pages on the EMC community site on Vlab.
