### ISSUE TITLE
Should model name be "FV3" or "FV3GFS" in CIME?  Proposed "UFSATM"

### ISSUE THREAD

**Issue by rsdunlapiv** [ufs-community/ufs-mrweather-app#51]
CIME has a short name for every model component and it is used in several places visible to the user.  The name is currently "FV3GFS".  There was discussion about whether it should be "FV3" although that does not seem accurate since FV3 is just the dycore.

**Comment by ligiabernardet** [comment]
We have been using "UFS Atmosphere" to refer to the atmospheric component
of the UFS (dycore, physics, infrastructure).

**Comment by rsdunlapiv** [comment]
@ligiabernardet this is a short name used in CIME, usually only several letters like MOM, POP, CAM, etc.

**Comment by ligiabernardet** [comment]
In this case I suggest UFSATM.
FV3 is not so good since it is only the dycore and not the entire model.
FV3GFS is not good either since GFS is a particular operational
implementation. The GFS could be a coupled model in the future, so it is
not a good name to represent the atmospheric component.

**Comment by rsdunlapiv** [comment]
@arunchawla-NOAA any objection to using "UFSATM" within CIME to describe the atmosphere model? This will mainly be used by people who are making changes to CIME.  The user namelist file will be called user_nl_ufsatm.

**Comment by rsdunlapiv** [comment]
This is complete.  Waiting for PR.

**Comment by rsdunlapiv** [comment]
Closed via https://github.com/ufs-community/ufs-mrweather-app/pull/57
