### ISSUE TITLE
Finalize and communicate the file outputs that will be supported for the release.  

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#52]
@fossell @mvertens @arunchawla-NOAA @rsdunlapiv  @jedwards4b @ligiabernardet   It is unclear what file outputs will be supported to users with this release. There are a few different aspects of this: horizontal grid, vertical grid, and file format (NetCDF or GRIB2).

It appears that at least the following will be supported:
- NetCDF, Gaussian horizontal grid, model levels in the vertical - as output from the model
- GRIB2, regular latitude-longitude horizontal grid, standard isobaric levels in the vertical - after postprocessing with UPP and a grib utility for horizontal interpolation.

Jun asked whether it would make more sense to have the model write out latitude-longitude grids in NetCDF (the model write component interpolates during run-time to get to the Gaussian grid, and it could just aas easily go to lat-lon), but Hui-ya wasn't comfortable with that. Evan and Kate noted that other types of vertical interpolation are possible with the GRIB2 output (e.g. height above ground), but it isn't clear which options will be considered supported.

There really should be a discussion about this that includes Hui-ya, Jun, and other folks so the decisions are clear.

**Comment by arunchawla-NOAA** [comment]
The model can only do Gaussian or regular grid not both. If we do regular grid output then the UPP will fail. 

Our decision is to only support Gaussian grid netcdf output on model levels from the model and gaussian grid grib2 output on isobaric levels through UPP. Note UPP also provides additional diagnostic outputs.

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet once this is added to the documentation on what types of output we are supporting let us know so we can close this ticket

**Comment by ligiabernardet** [comment]
This aspect will definitely be captured in the UG for the MR W App. The documentation is under development, currently in Google Doc https://docs.google.com/document/d/1_MhfFIc_ON-XE9rSNhlBrYm-4kpAhWV_Jxt7WoNb_QA/edit.

**Comment by ligiabernardet** [comment]
@uturuncoglu Some testers are reporting that the model is outputting NEMSIO instead of NetCDF. Have you encountered that in your tests? Do we need a namelist change?

**Comment by uturuncoglu** [comment]
We set it nemsio format by default but we could make it netcdf easily. The tests uses netcdf. You could also modify output format by using user_nl_ufsatm file.

**Comment by ligiabernardet** [comment]
My understanding is that the default model output will be NetCDF. At least
this is what we are saying in the documentation. I would suggest that you
change the default to NetCDF. If not, I need to know so this can be
reflected in the documentation. Tks

**Comment by jedwards4b** [comment]
We set default namelist parameters based on the docs in 

https://docs.google.com/document/d/1EKc2mAld5VsrNjTRgqUcTVG1ZcEIkllA-NrAKUs4DWI/edit
https://docs.google.com/document/d/1bLbVdWgEIknDQZgTuOZ6IPVEGv5jUgOrCm4GrR96oBU/edit

Please update these docs if they do not reflect the desired defaults.   There was also a questioned raised about the default timestep for C96.

**Comment by arunchawla-NOAA** [comment]
these are based on operational settings. These are not formal documents.
Please change output format to netcdf in cime. Thanks
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Comment by ligiabernardet** [comment]
@jedwards4b Regarding the 450s timestep for C96, indeed Phil said we could
use a longer timestep. Kate Friedman and I consulted with Fanglin Yang of
EMC and his recommendation was to keep the timestep as is because a longer
timestep sometimes results in instabilities. So my current understanding is
that we are going forward with 450s for C96.

**Comment by uturuncoglu** [comment]
@arunchawla-NOAA okay we will change the output format. @ligiabernardet if you make changes on those document please highlight them and we could update the defaults without checking all the namelist options.

**Comment by ligiabernardet** [comment]
@arunchawla-NOAA @jedwards4b @uturuncoglu @pjpegion  I have changed variable _output_file_ the Google Docs from _nemsio_ to _netcdf_. I am not sure if variable _write_nemsioflip_ is needed or whether it matters what it is set to. I have not tested these changes.

**Comment by jedwards4b** [comment]
@ligiabernardet thank you!

**Comment by uturuncoglu** [comment]
The default output format is set to NetCDF. It is in the FV3 interface and once we update the app, it will be available to all the users.

**Comment by ligiabernardet** [comment]
@junwang-noaa In the Google Doc with the namelist you have a comment that says that if the model outputs in NetCDF format "the post processing code needs to be updated to the version that can handle S->N scan mode.".  Can you elaborate on this? Thanks

**Comment by climbfuji** [comment]
I can say that we merged a commit from Dusan that had to do with S->N scanning into EMC_post a a week or two back.

**Comment by uturuncoglu** [comment]
I confirm that post is working with netcdf output but I did not look at the grid files that is produced by NCEP post. So, I you have some tool that I could use to quickly visualize the variables I could check the NCEP post output to be sure it is working without any problem.

**Comment by junwang-noaa** [comment]
I checked with Wen, she said the scanning mode code change is in the public
release. So it is OK not to set write_emsioflip in model configuration file.

Jun

**Comment by ligiabernardet** [comment]
Thanks. Closing this one.
