### ISSUE TITLE
List of differences between release and code in operations

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#53]
@arunchawla-NOAA @junwang-noaa @ligiabernardet During preparation of the two-pager Ricky Rood requested a list of differences between the release code and code in operations, presumably for both the physics updates and non-physics updates.

**Comment by arunchawla-NOAA** [comment]
@ceceliadid this was asked in the two pager. Is this still needed as part of communication and / or part of documentation?

**Comment by ceceliadid** [comment]
@arunchawla-NOAA  This is still needed.

**Comment by arunchawla-NOAA** [comment]
We will have this done prior to public release

**Comment by arunchawla-NOAA** [comment]
We have identified this as a gap in the to do document for the document code sprint

**Comment by ceceliadid** [comment]
@arunchawla-NOAA can we please leave this open? I don't think we should close these tickets until they're actually done.

**Comment by ligiabernardet** [comment]
The following text was added to the Weather Model User's Guide:
Even when using physics suite GFS_v15p2, the UFS WM v1 differs from the operational GFS v15.2 in a few ways. First, the public release code reflects the state of development as of the fall of 2019, and therefore the parameterizations contain innovations beyond what is in GFSv15.2 operations. For example, the GFDL microphysics distributed for use in GFS v15.2 and GFS v16beta is the same scheme and contains development beyond what was transitioned to operations for GFS v15 in June 2019. Second, the public release code uses the CCPP as the interface for calling physics, while in operations the Interoperable Physics Driver (IPD) is used. NOAA is currently working toward phasing out the IPD from UFS applications. Validation tests demonstrated that CCPP and IPD give bit-for-bit identical results when the same physics is employed and selected performance flags are excluded at compilation time. When performance compiler flags employed in operational production are used, runs with CCPP and IPD for the same physics suite yield differences comparable to running the model in different computational platforms. Finally, the operational GFS runs in NOAA Central Operations computational platforms. When users run the model in different platforms, the results will differ.

If that looks okay we can close this ticket.

**Comment by arunchawla-NOAA** [comment]
This works for me. @junwang-noaa anything else you want to add?

**Comment by junwang-noaa** [comment]
The description looks good to me.
