### ISSUE TITLE
NCEP Post and its possible usage examples

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-mrweather-app#54]
Currently, the NCEP Post script that is defined under CIME runs over 12, 24, 36 cycles. I just wonder about the possible workflows to extend the current implementation. My specific questions are the followings,

- Do we need to run the NCEP Post for different cycles?
- What about restarting model and running NCEP Post again. I think we need to change the dates in the namelist file and also we need to change cycles because those are used to define the file names. Right?

```
nemsfile
binarynemsiompiio
grib2
2019-09-11_00:00:00
GFS
flxfile
&nampgb
  kpo = 50
  po = 1000., 975., 950., 925., 900., 875., 850., 825., 800., 775., 750., 725.,
      700., 675., 650., 625., 600., 575., 550., 525., 500., 475., 450., 425.,
      400., 375., 350., 325., 300., 275., 250., 225., 200., 175., 150., 125.,
      100., 70., 50., 40., 30., 20., 15., 10., 7., 5., 3., 2., 1., 0.4
/
``` 

- I think naming those namelist files are not important because we are linking them as **itaga**

Please let me know about the possible usage examples of NCEP Post and i will try to extend the current script as much as possible. I am also attaching current script defined under CIME as reference.

```
#!/bin/bash
{{ batchdirectives }}

# Query run directory 
rundir=`./xmlquery --value RUNDIR`
echo "run dir is $rundir"
cd $rundir

# Query build directory
blddir="$rundir/../bld"

# Set environment variables
export LD_LIBRARY_PATH=$NCEP_LIBS/lib:$NCEP_LIBS/lib64:$LD_LIBRARY_PATH

# Copy executable to build directory
cp $NCEP_LIBS/bin/ncep_post $blddir/.

# Query mpirun command 
runcmd='{{ mpirun }}'
mpirun=`echo $runcmd | awk '{print $1}'`

# Query file prefixes
dyn_prefix=`cat model_configure | grep filename_base | awk -F: '{print $2}' | awk '{print $1}'`
phy_prefix=`cat model_configure | grep filename_base | awk -F: '{print $2}' | awk '{print $2}'`

# Query output format
file_ext=`cat model_configure | grep output_file | awk -F: '{print $2}' | tr -d " "`
if [ "$file_ext" == 'netcdf' ];then
   file_ext="nc"
fi
if [ "$file_ext" == 'netcdf_esmf' ];then
   file_ext="nc"
fi

# Run ncep_post
for f in 012 024 036
do
  export T1=$SECONDS
  cp ${dyn_prefix}f${f}.${file_ext} nemsfile
  echo "cp ${dyn_prefix}f${f}.${file_ext} nemsfile"
  cp ${phy_prefix}f${f}.${file_ext} flxfile
  echo "cp ${phy_prefix}f${f}.${file_ext} flxfile"
  cp itaga.$f itag
  eval "time $mpirun $blddir/ncep_post >oi.$f 2>ei.$f"
  export T2=$SECONDS
  let dff=$T2'-'$T1
  echo ran $DECOMP on `date` in $dff seconds >>TIMES
  echo done >>DONEOUT
done
```
```

**Comment by junwang-noaa** [comment]
Please ask post group, Hui-ya.chuang@noaa.gov and Wen.meng@noaa.gov, for help.

**Comment by rsdunlapiv** [comment]
I asked Hui-ya and Wen to send their GitHub IDs so we can keep this discussion here.

**Comment by WenMeng-NOAA** [comment]
Wen's githubid: WenMeng-NOAA.
Huiya's githubid: HuiyaChuang-NOAA.

**Comment by HuiyaChuang-NOAA** [comment]
Rocky, I'm a bit confused about your questions.  Feel free to call me and we can discuss:
301-683-3716

I do have several meetings this afternoon.  My available time:
3-3:30 pm
4-5 pm

**Comment by WenMeng-NOAA** [comment]
@uturuncoglu looks your NCEP post configuration is for processing model output in nemsio, right?

**Comment by uturuncoglu** [comment]
@WenMeng-NOAA Yes, it uses nemsio by default. it also supports netcdf based on the **output_file** namelist option defined in model_configure. I just wonder that do we nned to support different cycles other than 12, 24 and 36. This part of the script is still hard coded. There might a possibility to have also more than 3 cycles but i am not sure about it is the case of regular workflow. So, i am just trying to get feeling about the possible application of NCEP Post and try to generalize the script.

**Comment by WenMeng-NOAA** [comment]
@uturuncoglu and @rsdunlapiv  I just talked with Jun. Here are some clarification for NCEP post:
1) right now, NCEP POST (executable) has only capability for processing fv3 global model at gaussian grid and output GRIB2 file at gaussian grid.
2) The grib2 file generated in 1) can be regridded into lat-lon grid via utility wgrib2. The wgrib2 is portable utility can be downloaded at https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/
3) The procedure of converting gaussian grid into lat-lon grid can be found in UPP workflow script ush/fv3gfs_downstream_nems.sh.  (see https://github.com/NOAA-EMC/EMC_post/blob/ufs_release_v1.0/ush/fv3gfs_downstream_nems.sh)

**Comment by uturuncoglu** [comment]
@WenMeng-NOAA Thanks for the clarification. If i remember correctly i could also process netCDF output but i am not sure and i need to double check. So, because of it, i add support for different output formats. I think that converting NCEP Post output to different format is not the part of the UFS Release workflow but it would be nice to double check.

**Comment by WenMeng-NOAA** [comment]
@uturuncoglu Yes, NCEP POST can process model output in netcdf.  The configuration of itaga would be different for netcdf. You may change "binarynemsiompiio" into "netcdf" for processing netcdf.

**Comment by arunchawla-NOAA** [comment]
@uturuncoglu and @rsdunlapiv Just checking to see if your questions have been answered

**Comment by uturuncoglu** [comment]
@arunchawla-NOAA I have some idea but in case of having more question let's keep it open. i am plaining to make cycle count and their interval dynamic and user could change them.

**Comment by rsdunlapiv** [comment]
@uturuncoglu to update workflow post processing script to call ncep_post on ALL output files, instead of looking for certain cycles.

**Comment by rsdunlapiv** [comment]
Post-processing script was updated to process all output files.  This still needs to be merged in by @uturuncoglu.

**Comment by uturuncoglu** [comment]
@rsdunlapiv It is done!

**Comment by arunchawla-NOAA** [comment]
@rsdunlapiv and @uturuncoglu can this ticket be closed

**Comment by uturuncoglu** [comment]
We are processing all the output file now. I am closing this.
