### ISSUE TITLE
Doc must explain two types of RT (CIME-based and rt.sh)

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#55]
The ufs-weather-model code management depends on rt.sh, which executes the regression tests (RTs) in Tier 1 and Tier 2 platforms (currently NOAA machines and NCAR Cheyenne). Those are executed on latest development up-to-date with main development branches prior to commits. With the public release, CIME will have RTs for all release supported platforms, but limited to the supported configurations. The ufs-mrw-app UG introduction should mention and clarify this.

**Comment by ligiabernardet** [comment]
The UFS WM UG now includes the following explanation: _It should be noted that the regression tests described here are mandatory for committing code back to the ufs-weather-model authoritative code repository. These regressions tests differ from those distributed with the workflows for UFS applications, which are intended for application users and developers to assess the quality of their installations and the impact of their code changes._ 
A similar explanation will be added to the UFS MR W App UG.

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet, @llpcarson and @rsdunlapiv . Has this been addressed? Can this be closed?

**Comment by ligiabernardet** [comment]
Yes. It has been addressed in the App User's Guide.
