### ISSUE TITLE
Finalize FV3 dycore documentation

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#56]
The FV3 dycore documentation must be finalized and committed to https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/tree/ufs_public_release/docs

By looking at HTML available at [https://noaa-emc.github.io/FV3_Dycore/html/index.html], it seems a few namelist variables are not described (see list below). If possible, please add documentation for all relevant variables. It also seems that some namelist variables may not be relevant/available for use with UFS, so it may be good to flag those.

List of variables that do not appear to be documented:
namelist /fv_core_nml/
m_split, 
do_sat_adj, 
do_f3d, 
read_increment, 
use_new_ncep, 
use_ncep_phy, 
scale_z, 
w_max, 
z_min, 
lim_fac, 
trdm2, 
non_ortho, 
ke_bg, 
use_old_omega, 
do_reed_physics, 
reed_cond_only, 
filter_phys, 
fill_wz, 
RF_fast, 
full_zs_filter, 
deglon_start, 
deglon_stop, 
deglat_start, 
deglat_stop, 
old_divg_damp, 
nestbctype, 
nsponge, 
s_weight, 
ioffset, 
joffset, 
gfs_phil, 
adj_mass_vmr, 
fac_n_spl, 
fhouri, 
regional, 
bc_update_interval

**Comment by arunchawla-NOAA** [comment]
@bensonr can we get some help here?

**Comment by bensonr** [comment]
Sure.  Please have the extended documentation team look at the doxygen documentation in the source file model/fv_arrays.F90.  I believe most, if not all, entries are defined there.

**Comment by valbonakunkel-noaa** [comment]
I have this response from Lucas.

Some of these variables are undocumented and unsupported features and are not recommended for general use. The only ones that are recommended are those for the regional model (regional, bc_update_interval), and the read_increment which handles the DA interface. do_sat_adj enables the fast component of the GFDL microphysics; it must have the same value as fast_sat_adj in gfdl_cloud_microphysics_nml.

The nesting-related variables are being depreciated in favor of a new nesting namelist in the upcoming FV3 update and will be explained in the technical note that accompanies it.

**Comment by ligiabernardet** [comment]
Thank you @valbonakunkel-noaa and @bensonr 

@valbonakunkel-noaa, could you please add documentation for the variables recommended by Lucas (regional, bc_update_interval, read_increment, and do_sat_adj. You can refer to the source code mentioned by Rusty for information.

@valbonakunkel-noaa My understanding is that this documentation is 95% ready. Can you please commit it to  https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/tree/ufs_public_release/docs? We continue updating afterwards, Thanks!

**Comment by ligiabernardet** [comment]
@valbonakunkel-noaa @junwang-noaa My understanding is that this documentation is 95% ready. Are we waiting for anything? Can you please commit it to https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/tree/ufs_public_release/docs? We continue updating afterwards, Thanks!

**Comment by climbfuji** [comment]
We submitted a PR to ufs_public_release last week that contained scientific documentation for the dycore. Was this something else?

**Comment by ligiabernardet** [comment]
Thank you. I see the PR to ufs_public_release submitted last week already contains the  documentation for the variables we requested. Display is at https://noaa-emc.github.io/FV3_Dycore/html/index.html.
 In this case, do you still need this PR to the dev/emc branch https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/10?

**Comment by climbfuji** [comment]
At some point we will have to bring back selected commits/changes from ufs_public_release to the authoritative branches. We (in particular I) have been fairly inconsistent in either saving this for later or doing it right away.

**Comment by ligiabernardet** [comment]
OK, let's consider this done.

**Comment by ligiabernardet** [comment]
@valbonakunkel-noaa @junwang-noaa This issue should not have been closed. 
We still need the *.md files from this PR https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/10 to show up in the release branch of GFDL_atmos_cubed_sphere. Can the code managers advise how to get it there? Tks

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet can we close this now that you have it marked done?

**Comment by climbfuji** [comment]
In Ligia's absence, I will close this issue - the fv3dycore documentation has been merged.
