### ISSUE TITLE
Problem with chgres_cube

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-mrweather-app#61]
In #58 we found that the problem appears to be in the initial condition.
We are using the nemsio files found in 
ftp.emc.ncep.noaa.gov:/EIB/UFS/inputdata/prod/gfs.20190909/00
We need someone to determine if there is a problem in these initial conditions or
if there is a problem in chgres_cube.

**Comment by arunchawla-NOAA** [comment]
@jedwards4b 

Can you point to the exact chgres you used? There have been some bug fixes to chgres.

**Comment by uturuncoglu** [comment]
@arunchawla-NOAA On Cheyyene: The last commit on superbuild is following

```
commit 4eb0b72461e8e07bbf407ea7e13f02f0d4286091
Author: Kyle Gerheiser <kgerheiser@icloud.com>
Date:   Mon Dec 16 10:56:15 2019 -0500

    Fixes #3. Use CMAKE_SHARED_LIBRARY_SUFFIX for portability across macOS and Linux
```

I'll try to install the latest version of the super build (ufs_release branch) and test with it also. What do you think?

**Comment by uturuncoglu** [comment]
Is NCEPLIBS (particularly chgres_cube) tested outside in CIME using regular workflow in NOAA/EMC side to prove it is working.

**Comment by arunchawla-NOAA** [comment]
@GeorgeGayno-NOAA 

Can we update the release/ufs_release_v1.0 to sync up with develop so the latest bug fixes can be included. I believe the NCEPLIBS super build is using this branch

@kgerheiser and @Hang-Lei-NOAA can confirm. We can then test with that.

**Comment by uturuncoglu** [comment]
BTW, the chgres does not create **sfc_ctrl.nc** file. This file exists in some directories of regression tests (it think). Is it possible to create that file because it includes date information (idate variable). The main problem is that the files generated by chgres has no any attributes even global one to indicate the source of the files and dates.

**Comment by uturuncoglu** [comment]
> BTW, the chgres does not create sfc_ctrl.nc file. This file exists in some directories of regression tests (it think). Is it possible to create that file because it includes date information (idate variable). The main problem is that the files generated by chgres has no any attributes even global one to indicate the source of the files and dates.

I'll create another new issue related with it https://github.com/ufs-community/ufs-mrweather-app/issues/63

**Comment by jedwards4b** [comment]
chgres ufs_release_v1.0 branch was updated to latest develop.  This fixed the problem with initial files in debug runs.
