### ISSUE TITLE
Heads-up: Cheyenne outage for system updates February 25-29

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#64]
CISL is planning an extended outage of Cheyenne Feb 25-29, see announcement here: https://dailyb.cisl.ucar.edu/bulletins/cheyenne-maintenance-downtime-scheduled-february-25-29

The outage will include "system software updates". In the past, this has often led to significant changes, updates of compiler versions, ..., that required recompiling the dependent software stack.

Unless we shift the ufs-release to after the outage (which we don't want to as far as I understand), this means that (a) any testing and documentation based on the current system configuration will need to be finished before Feb 25, and we need to be prepared for a way to provide updates to the code (Cheyenne configuration, baseline) and the documentation.

**Comment by llpcarson** [comment]
I checked with NCAR/CISL, and they are still finalizing the software stack for the upgrade.  It will likely include at least a new MPT version.

CISL has agreed to give our team access to their test system ahead of the upgrade.  I will provide usernames once the test system is ready - Dom, Ufuk, Mike K.,  myself, others?

**Comment by arunchawla-NOAA** [comment]
We have raised this issue with UFS leadership. Stay tuned
