### ISSUE TITLE
Decide on a tag convention

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#70]
This is a proposal a few people discussed yesterday. Any comments or objections?

Beta tags:
ufs_v1.0.0_beta0x for tags on the weather model, mr weather app, and associated User Guides.
nceplibs_v1.0.0_beta0x for nceplibs.

This would NOT mean that the code itself will be announced as UFS v1.0. 
The app would still be the MR Weather App 1.0, the Weather Model the WM 1.0.

Final tags:
ufs_v1.0.0 for the wm and app
nceplibs_v1.0.0

This is consistent with a UFS versioning document from Arun:
https://github.com/ufs-community/ufs/wiki/Conventions#versioning

People on the call did NOT want to tag all submodules with these tags if the submodules were libraries that already had version numbers.

**Comment by arunchawla-NOAA** [comment]
This is the naming convention that we are following

https://docs.google.com/document/d/15hc7cKU9n2joiJJ-xXSPF3G70gNHLhdMqAnzj2CeP0U/edit?ts=5e331979
