### ISSUE TITLE
Decide on a branch naming convention 

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#71]
Proposal below.

For ncep_libs, the weather model, and mr weather app, code associated with the release would live on a  branch called ufs_release_v1.0 This is already what the nceplibs release branch is called.

A branch would be created for each release. If a fix or patch is needed to a previous release it can be made on the branch for the release.

Per the versioning convention, the third place in tags is designated for bugfixes/patches. For example, a patch to the app release ufs_v.1.0.0 on branch ufs_release_v1.0 would be tagged as ufs_v1.0.1

**Comment by ceceliadid** [comment]
Just to clarify, this branch convention is not needed to start external testing but we do need a tag, so the tag convention would be nice to settle soon.

**Comment by arunchawla-NOAA** [comment]
Naming convention here

https://docs.google.com/document/d/15hc7cKU9n2joiJJ-xXSPF3G70gNHLhdMqAnzj2CeP0U/edit?ts=5e331979
