### ISSUE TITLE
Beta tag on NCEPLIBS for use with the WM GST

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#73]
This is a request for a beta tag on NCEPLIBS by Feb 3 for use with the first GST. The testing here will be pretty limited, so whatever's on the head of the release branch should be fine.

**Comment by ceceliadid** [comment]
Hi @climbfuji , any sense of the ETA for a tag?

**Comment by climbfuji** [comment]
@ceceliadid we should have something for you later today. It will be an alpha tag, not a beta tag, to make sure that people understand that this is still in the early testing phase.

**Comment by ceceliadid** [comment]
That's awesome @climbfuji thanks! Understood it's alpha.

**Comment by arunchawla-NOAA** [comment]
Tag has been created
