### ISSUE TITLE
Review and update WM GST questionnaire 

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#74]
The draft questionnaire looks like this:
https://docs.google.com/forms/d/1yEgYalN4LNOZuG9GNIRq7V9NTU1ZVtnhsUtplok-G40/edit

@jwolff-ncar please let me know if you think you might be ready with a forum URL by Feb 3 and w can replace the support email contact with that.

@ligiabernardet and @junwang-noaa let me know if there are any things you'd like the testers to look at or questions you want to ask about any sections of the weather model documentation.

**Comment by ligiabernardet** [comment]
Looks good, thanks for putting this together. A few comments:

   - Should Theia be substituted with Hera?
   - Could add a question about ease of building the code.
   - We are not asking the user to make code changes (just namelist
   changes), so that question is not applicable.

**Comment by uturuncoglu** [comment]
The image in the following link is not seen. It could be a broken link.

https://github.com/ufs-community/ufs-weather-model/wiki/Graduate-Student-Test%3A-Increasing-the-Number-of-Cloud-Condensation-Nuclei

Also, in the prerequisite section it is only mentioning "- Access to Cheyenne (NCAR) or Stampede2 (XSEDE) computers." but in the list there is Theia as @ligiabernardet is pointed. I think that these two part needs to be consistent.

**Comment by ceceliadid** [comment]
@uturuncoglu Thank you very much for the comments! The Getting Started and GST wiki pages are not ready for review yet, just the questionnaire itself. The wiki should be ready in the next day or so. Sorry, I should have made that clearer!

**Comment by ceceliadid** [comment]
This was done and can be closed.
