### ISSUE TITLE
Finalize UFS MR Weather App Users Guide

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#75]
@mvertens @rsdunlapiv @uturuncoglu Thank you for providing a great start for the User's Guide, which can be viewed at https://ufs-mrapp.readthedocs.io/en/latest/. Several at the DTC started using it and our limited tests have been successful.  I would like to suggest a re-organization and augmentation of the material, and I have a few request for changes. We can meet to discuss, might be easier.

**Re-organization with the following chapters**
(Numbers refer to https://ufs-mrapp.readthedocs.io/en/latest/index.html 01/29/2020)

- Introduction (DTC)
-- Replaces and augments content from 1.1.1, 1.1.3)
--  Rough draft [here](https://docs.google.com/document/d/1_MhfFIc_ON-XE9rSNhlBrYm-4kpAhWV_Jxt7WoNb_QA/edit#) 
- Quick Start for configured platforms  (currently 1.2) (CGD)
- Configuring a new platform (DTC)
-- Include content from 1.1.2 and details of the software stack requirements (compiler vendor, versions, etc)
- Download and build the source code (currently 1.1.4) (CGD)
-- Confirm tag name for ufs-mrweather-app
-- Add how one finds the tags for the individual components from manage externals conf file
- Code repository and directory structure (DTC)
- Inputs and output files 
-- Directory structure (DTC)
-- Downloading input data (currently 1.1.5) (CGD)
- Preconfigured platforms (with content from 1.1.6)
- Adding and porting CIME to a new machine (currently 1.1.7)
- Model configurations (currently 1.1.8) (CGD)
- Testing (currently 1.3) (CGD)
- FAQ (currently 1.4) (CGD)

**Requests for changes (all minor stuff) based on user experiences**
- Do we need this add on the front page.
- Change name of section from “Model Workflow Quick Start” to “Application workflow Quick Start”
- CCPP cannot run with Python 3
- PGI is not supported (remove from ./query_config --machines)
- When mentioning specific releases, use one that exists for example (not 0.1)
- GFS description is inaccurate. Not coupled. Res not 28 km but 13.
- Data for 2019 is not “also” available in ftp site bcs is not available in NOMADS.
- Why mention “cpl” in Section 1.2.3? Does it pertain to this app?
- Explain what short-term archive is
- Remove Brief CIME Overview from App guide (this is not UFS-specific)
- Can a user run the workflow without pre-processing if they already have the ICs?
- Can the workflow run more than one initialization with a single command? If not, how can a user automate the workflow to do that?
- Besides NOMADS, that only provides ICs for the last 10 days, where can user find GFS analyses? E.g., NCAR archives?
- Add to FAQ: How do I change a namelist option for the model, pre- and post? Suggested example: stochastic physics

**Comment by mvertens** [comment]
@Ligia Bernardet - NOAA Affiliate <ligia.bernardet@noaa.gov> Thanks for the
feedback and your suggestions. Lets definitely meet to discuss. I think
that would be most helpful. Friday morning is open for me.

**Comment by llpcarson** [comment]
DTC contributed some re-organization and updates; CIME group is continuing to update as other components are finalized.  Status changed to "in progress".

**Comment by llpcarson** [comment]
@rsdunlapiv @uturuncoglu Could you add a quick status for this documentation - are your contributions ready for review, or is there more content to add?  Thanks!

**Comment by uturuncoglu** [comment]
It is mostly ready but I need to modify couple of section (especially Inputs and Outputs section) because we did couple of changes related with input types (nemsio -> grib2). I'll do it today or tomorrow.

**Comment by ligiabernardet** [comment]
Hello @uturuncoglu Can you please give us an update on the App User's Guide? Have you been able to make the changes you mentioned? We have a few other changes to make, and would like to do those on top of yours. Tks
