### ISSUE TITLE
Configuration needed for Mac/Linux generic systems

### ISSUE THREAD

**Issue by rsdunlapiv** [ufs-community/ufs-mrweather-app#76]
The CIME team needs to information about the system configuration for generic Mac and Linux systems.

**Comment by jedwards4b** [comment]
Continued from https://github.com/ufs-community/ufs-mrweather-app/issues/7

**Comment by rsdunlapiv** [comment]
This discussion is happening on:
https://github.com/ufs-community/ufs-mrweather-app/issues/67

This issue should be closed with the one above after the MacOS installation is finalized.
