### ISSUE TITLE
Create the first ufs-mrweather-app beta tag 

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-mrweather-app#78]
We will create the first beta tag for this repo when we have the following tags:

- FV3_interface tag **is created**
- NEMS_interface tag **is created**
- cime 
- ufs-weather-model

**Comment by rsdunlapiv** [comment]
@jedwards4b are the tags in place for FV3_interface, NEMS_interface, and cime?

**Comment by jedwards4b** [comment]
Tag status is noted here https://docs.google.com/document/d/15hc7cKU9n2joiJJ-xXSPF3G70gNHLhdMqAnzj2CeP0U/

**Comment by arunchawla-NOAA** [comment]
@jedwards4b and @rsdunlapiv all the other tags have been created. Only the app and CIME (if it has not been created yet are left)

**Comment by arunchawla-NOAA** [comment]
@jedwards4b now that we have started running tests are we ready to create tags and close this ticket?

**Comment by jedwards4b** [comment]
I think that we are very close - there are some new problems cropping up with the change of initial conditions, but I hope to close this tomorrow.

**Comment by arunchawla-NOAA** [comment]
@rsdunlapiv and @jedwards4b can we close this now that we have tags? I know we are still addressing some issues in testing periods but the tags are there, right?

**Comment by jedwards4b** [comment]
Yes
