### ISSUE TITLE
NCDC GRIB2 datasets for initializing App

### ISSUE THREAD

**Issue by ligiabernardet** [ufs-community/ufs-mrweather-app#79]
My understanding is that will support three sources of ICs for initializing the App, always GRIB2 GFS analyses. What is the grid resolution(s) of the data we are supporting (e.g., 0.5 degree? 0.25 degree? multiple options?)

1) Canned 2019-09-09 00 case. The CIME workflow can retrieve this.
2) NOMADS (last 10 days of GFS analyses are available). The CIME workflow can retrieve this.
3) NCDC archives (CIME cannot retrieve this now, but users can download and stage the data. CIME could be augment to retrieve this). Can someone let me know what is the URL for this data? For example, is it the 0.5 deg at ftp://nomads.ncdc.noaa.gov/GFS/analysis_only?

In addition, can users with access to NOAA platforms get the ICs from NOAA HPSS? If so, can someone tell me where?

Thanks,
Ligia

**Comment by ligiabernardet** [comment]
@llpcarson @LarissaReames-NOAA @uturuncoglu @arunchawla-NOAA

**Comment by LarissaReames-NOAA** [comment]
The main page I used when retrieving archived data from NCEI (formerly NCDC) is : 

https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs

This has various ways listed to access the data (https, FTP, HAS, etc.). Online GFS4 (0.5 deg) data is only available back to the January 2019:

https://nomads.ncdc.noaa.gov/data/gfs4/

But data back to 2006 can be requested from HAS:

https://www.ncdc.noaa.gov/has/HAS.FileAppRouter?datasetname=GFSGRB24&subqueryby=STATION&applname=&outdest=FILE

**Comment by LarissaReames-NOAA** [comment]
Also, I believe the plan was to support 0.25, 0.5, and 1.0 degree.

**Comment by uturuncoglu** [comment]
> Canned 2019-09-09 00 case. The CIME workflow can retrieve this.

Yes. The data is retrieved from NOMADS server and it process gfs.t00z.atmanl.nemsio and gfs.t00z.sfcanl.nemsio files using CHGRES to create input.

> NOMADS (last 10 days of GFS analyses are available). The CIME workflow can retrieve this.

If the data is not in the input folder. CIME gets the data from https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/ and process it same way with (1). Again, we are only supporting gfs.t00z.*anl.nemsio files at this point.

> NCDC archives (CIME cannot retrieve this now, but users can download and stage the data. CIME could be augment to retrieve this). Can someone let me know what is the URL for this data? For example, is it the 0.5 deg at ftp://nomads.ncdc.noaa.gov/GFS/analysis_only?

I think there is no specific namelist variable for chgres for the input data resolution. Right? It is also possible to add support for archived files using 

https://nomads.ncdc.noaa.gov/data/gfsanl/

but in here the data format is grb2 (I know that CHGRES supports it now) and I think we need to make some change in the namelist file. Please let me know the example namelist file to process this data and I could make required changes in the CIME side to automatically generate it and test it.

**Comment by arunchawla-NOAA** [comment]
please wait till the library build and ufs-utils release branches are
updated for that. We plan to test grib2 data next week
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Comment by uturuncoglu** [comment]
@arunchawla-NOAA Sure. Just let me know, when it is ready.

**Comment by ligiabernardet** [comment]
Thank you for the information. It has been captured in the App UG and later we can review it.

**Comment by arunchawla-NOAA** [comment]
@ligiabernardet can we close this ?

**Comment by ligiabernardet** [comment]
We need to decide if CIME will be augmented to retrieve data from NCEI
archives. Per Ufuk: CIME cannot retrieve this now, but users can download
and stage the data. CIME could be augment to retrieve this. If CIME will
not be augmented, we need to understand where/how a user should stage the
data on disk so CIME can find it. And test it. The documentation is
currently incomplete in this aspect.

**Comment by rsdunlapiv** [comment]
@uturuncoglu What would be required to add the NCEI NOMADS download option to CIME? 

Per @LarissaReames-NOAA :

> This has various ways listed to access the data (https, FTP, HAS, etc.). Online GFS4 (0.5 deg) data is only available back to the January 2019:
> 
> https://nomads.ncdc.noaa.gov/data/gfs4/
>

**Comment by mvertens** [comment]
This is already being supported in CIME for NEMSio files. where do we get
GRIB?

**Comment by uturuncoglu** [comment]
@mvertens @rsdunlapiv We need,

- a version of CHGRES that supports Grib2 as an input format. I think this part is not fully ready and tested. @arunchawla-NOAA could make comment about it. 

- http or ftp link that files are stored.

- buildnml need to be extended to support the new data type. In this case, if user configures the model with a start date and NOMADS has no data for that particular date, then we could try to find it on NCEI NOMADS.

**Comment by rsdunlapiv** [comment]
@uturuncoglu does this link provided by @LarissaReames-NOAA work?
https://nomads.ncdc.noaa.gov/data/gfs4/

**Comment by uturuncoglu** [comment]
It has data but it goes back to 2019 and I did not try to process it. We need an example chores_cube namelist file to test chgres standalone.

**Comment by uturuncoglu** [comment]
I could able to process grib2 data with chgres and now I'll make required changes in the CIME side to make it automatic and test the model. 

@KateFriedman-NOAA If you don't mind could you put UFS_UTILS/parm/varmap_tables/GFSphys_var_map.txt file to the FTP.

**Comment by KateFriedman-NOAA** [comment]
@uturuncoglu Sure, I just need to know which UFS_UTILS tag/branch to grab that file from. @GeorgeGayno-NOAA Can you point me to the UFS_UTILS copy for the release? Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> 
> 
> I could able to process grib2 data with chgres and now I'll make required changes in the CIME side to make it automatic and test the model.
> 
> @KateFriedman-NOAA If you don't mind could you put UFS_UTILS/parm/varmap_tables/GFSphys_var_map.txt file to the FTP.

The GFSphys_var_map.txt file is part of the release branch: https://github.com/NOAA-EMC/UFS_UTILS/tree/release/public-v1/parm/varmap_tables

**Comment by KateFriedman-NOAA** [comment]
Thanks @GeorgeGayno-NOAA ! @uturuncoglu You can now find that parm file here:

https://ftp.emc.ncep.noaa.gov/EIB/UFS/parm/GFSphys_var_map.txt

**Comment by rsdunlapiv** [comment]
Here is an update on CIME support for automatic downloading of initial conditions for chgres:

- We initially were automatically downloading _nemsio_ format but we are planning to disable that approach and instead only automatically download _grib2_ format.  The _nemsio_ files are very large, so it makes sense to only download _grib2_ automatically.  @uturuncoglu is working on this functionality.

- The user can manually stage _nemsio_ input data (and _grib2_) instead of using the automatic download option.  This is helpful if the uses already has data locally and does not want to download new datasets or if the data is coming from a custom location that CIME does not know about.  @uturuncoglu plans to write a FAQ describing the steps to manually download input data and point CIME to the new location.  There is an [existing FAQ](https://ufs-mrapp.readthedocs.io/en/latest/faq.html#how-do-i-download-new-initial-condition-from-nomads-server), but it is about automatic downloading.

- A caveat is that the hosted _grib2_ data is lower resolution than the _nemsio_, so there could be issues when running the high res model with the _grib2_ data interpolated to the model grid.  We will need to run the CIME regression tests to see if the C768 runs complete without error.

- Our current plan is to get grib2 data from here:  https://nomads.ncdc.noaa.gov/data/.  However, @arunchawla-NOAA also pointed out: https://www.ncei.noaa.gov/data/global-forecast-system/access/grid-004-0.5-degree/forecast/.  The first one says it will go offline 5-15-2020 and the second has very limited data.  A complete solution is needed for a reliable, supported, authoritative, and complete set of _grib2_ inputs.

@jedwards4b and @uturuncoglu should please review and correct any issues with the above.

**Comment by arunchawla-NOAA** [comment]
My recommendation is to disable the automatic download of grib2 data. While this is an attractive feature it does force you to rely on two things

1. The data feed being available on said website and 
2. If the website for any reason is blocked at the user end then this will show up as a CIME failure

It may be better to provide detailed documentation on where data can be obtained from and let the user directly interact with website(s) to download the data sets.

**Comment by arunchawla-NOAA** [comment]
@rsdunlapiv @jedwards4b @GeorgeGayno-NOAA @LarissaReames-NOAA 

I checked out the different ways to get data from here

https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs

The only complete set was through their HAS system (I was getting 0.5 deg grib2 fields for dorian test case) and that is an interactive approach. Their NOMADS server has holes in the data sets.
