### ISSUE TITLE
Gitflow description of UFS development

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#88]
@arunchawla-NOAA This is a relatively minor thing, but it would be good to make sure that the Gitflow discussion here, intended to apply to UFS overall, is something people actually want to say about UFS development:
https://github.com/ufs-community/ufs/wiki/Development-Processes#Developing-with-Gitflow
It could probably use a look over.

**Comment by arunchawla-NOAA** [comment]
OK will look at it. The code management paradigm has shifted a bit from
this initial idea so good to go over
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Comment by arunchawla-NOAA** [comment]
I have updated this. Reaching out to code managers to review and make changes as they see fit

@junwang-noaa 
@DusanJovic-NOAA 
@pjpegion 
@kgerheiser 
@Hang-Lei-NOAA 
@climbfuji

**Comment by DusanJovic-NOAA** [comment]
I am not sure about other repositories but in ufs_weather_model and fv3atm we do not use Gitflow development process, we use Forking Workflow.

**Comment by Hang-Lei-NOAA** [comment]
Both gitflow and forking are not conflicting.
As the global_workflow, we use both. Repo management is based on gitflow.
developer management is based on forking workflow.

**Comment by arunchawla-NOAA** [comment]
Label is not important. Process is. Are we ok with the process as written ? Remember these are general guidelines the exact procedures are determined by the individual code managers.

**Comment by Hang-Lei-NOAA** [comment]
I am ok with this.

**Comment by pjpegion** [comment]
@arunchawla-NOAA This description looks good to me.

**Comment by climbfuji** [comment]
This reads good to me, too. Thanks for writing it up.
