### ISSUE TITLE
"fv3gfs_interface": reference "ufs-v1.0.0.beta07" does not appear to be a valid tag

### ISSUE THREAD

**Issue by JulieSchramm** [ufs-community/ufs-mrweather-app#90]
I think there is a typo either in the tag name or Externals.cfg, depending on how many zeros you want.

**Comment by jedwards4b** [comment]
I forgot to push the tag - this is corrected now.  https://github.com/ESCOMP/FV3GFS_interface/releases/tag/ufs-v1.0.0.beta07
