### ISSUE TITLE
All release materials need to be updated to reflect the updated definitions of support levels.

### ISSUE THREAD

**Issue by ceceliadid** [ufs-community/ufs-mrweather-app#94]
@llpcarson Noticing that the WM User's Guide is using the Tier 1 / Tier 2 terminology in some places (e.g. the compiling without an app section). This should be changed to the support levels on this page:
 https://github.com/ufs-community/ufs/wiki/Supported-Platforms-and-Compilers

**Comment by arunchawla-NOAA** [comment]
@ceceliadid @llpcarson @ligiabernardet . Are we satisfied? Can this be closed now?

**Comment by ligiabernardet** [comment]
I am satisfied with the user's guides.
Ligia

**Comment by ceceliadid** [comment]
Okay for me if it's okay for @ligiabernardet .
