### ISSUE TITLE
Review the module files for Public Release

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-mrweather-app#96]
We need to do a review of the module files for the Public Release. These should reflect the work done with the builds. Should only the module files for supported platforms be there?

**Comment by junwang-noaa** [comment]
I looked at the ufs-mrweather-app code and did not find where chgres or post are checked out, they are not in the Externals.cfg, also ufs-mrweather-app wiki does not have any information on that. So we only need to review the module files in the ufs-weather-model? I am curious if the CIME uses unified module files for ufs-weather-model, chgres and post, or load separate module  files for each one.

**Comment by uturuncoglu** [comment]
We are not checking out nceplibs and those are provided as external module files. All the information is in Externals.cfg

**Comment by rsdunlapiv** [comment]
@junwang-noaa yes on platforms like Hera and Cheyenne, a unified module file sets up the nceplibs environment variables, and those are used to determine the location of chgres and post executables.

**Comment by junwang-noaa** [comment]
Rocky,

So where does CIME code check out chgres and ncep_post? I did not see them
in:

https://github.com/ufs-community/ufs-mrweather-app/blob/master/Externals.cfg


Is there any document on how the unified  module file is used by model,
chgres and post?

**Comment by rsdunlapiv** [comment]
@junwang-noaa CIME does not check out chgres and ncep_post - they are already installed.  Note the module loaded in the CIME config_machines.xml:

https://github.com/ESMCI/cime/blob/ufs_release_v1.0/config/ufs/machines/config_machines.xml#L299

It does:
```
module use /scratch1/BMC/gmtb/software/modulefiles/intel-18.0.5.274/impi-2018.0.4
module load NCEPlibs/1.0.0alpha01
```
You will see the chgres and ncep_post are built with the nceplibs in the location specified by the module.  Easiest thing is probably for you to examine that module file.

**Comment by junwang-noaa** [comment]
OK, I saw in CIME code, the nceplibs module ( https://github.com/ESMCI/cime/blob/ufs_release_v1.0/config/ufs/machines/config_machines.xml#L299 ) has following:

setenv NEMSIO_LIB   ${NCEPLIBS_DIR}/lib/libnemsio_v2.2.3.a
setenv BACIO_LIB4   ${NCEPLIBS_DIR}/lib/libbacio_v2.1.0_4.a
setenv SP_LIBd      ${NCEPLIBS_DIR}/lib/libsp_v2.0.2_d.a
setenv W3EMC_LIBd   ${NCEPLIBS_DIR}/lib/libw3emc_v2.2.0_d.a
setenv W3NCO_LIBd   ${NCEPLIBS_DIR}/lib/libw3nco_v2.0.6_d.a

while in the model release/public-v1 branch, we have:

module load bacio/2.0.3
module load nemsio/2.2.4
module load sp/2.0.3
module load w3emc/2.3.1
module load w3nco/2.0.7

Not sure what are the differences between these versions.

**Comment by rsdunlapiv** [comment]
@junwang-noaa for this release we are okay with these different versions - the build team did a lot of work to make sure that you can build the whole stack with a few commands, so everything is together in one place with a unified module.  Of course, this is different than the current practice on NOAA machines and for NCO.  Longer term, I suspect that we will want these to somehow converge as much as possible so that what is available more broadly is pretty much the same thing that is being used for development on NOAA machines.

**Comment by jedwards4b** [comment]
If there is a newer install of NCEPLIBS module on hera we can update to the latest.

**Comment by climbfuji** [comment]
Update on this topic. I updated the module files for cheyenne + intel and gnu and for hera + intel, e.g.
```
diff --git a/modulefiles/hera.intel/fv3 b/modulefiles/hera.intel/fv3
index a1d3cc7..b7f4e41 100644
--- a/modulefiles/hera.intel/fv3
+++ b/modulefiles/hera.intel/fv3
@@ -26,36 +26,16 @@ module load impi/2018.0.4
 module load netcdf/4.7.0

 ##
-## NCEP libraries (temporary version to match the CCPP requirements)
-##
-module use -a /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles
-module load bacio/2.0.3
-module load ip/3.0.2
-module load nemsio/2.2.4
-module load sp/2.0.3
-module load w3emc/2.3.1
-module load w3nco/2.0.7
-module load g2/3.1.1
-module load g2tmpl/1.5.1
-module load crtm/2.2.6
-module load jasper/1.900.1
-module load png/1.2.44
-module load z/1.2.11
-## load modules for nceppost grib
-module load post/8.0.0
-
-##
-## load ESMF library for above compiler / MPI combination
-## use pre-compiled EMSF library for above compiler / MPI combination
+## use pre-compiled EMSF library and NCEP libraries for above compiler / MPI combination
 ##
-module use -a /scratch1/NCEPDEV/nems/emc.nemspara/soft/modulefiles
-module load esmf/8.0.0
+module use -a /scratch1/BMC/gmtb/software/modulefiles/intel-18.0.5.274/impi-2018.0.4
+module load NCEPlibs/1.0.0beta02

 ##
 ## load cmake
 ##
-module use /contrib/modulefiles
-module load cmake/3.9.0
+module use -a /scratch1/BMC/gmtb/software/modulefiles/generic
+module load cmake/3.16.3
 setenv CMAKE_C_COMPILER mpiicc
 setenv CMAKE_CXX_COMPILER mpiicpc
 setenv CMAKE_Fortran_COMPILER mpiifort
```
On Hera, all tests in `rt.conf` pass against the existing baseline. On Cheyenne, they fail for both GNU and Intel for all tests. Looking at the results, all `dynf???.nc` and `phyf???.nc` are identical, only the files `RESTART/*.nc` are different. `ncdump` shows no difference of those. `h5dump` shows the differences in the attached screenshot, but no others.

Hence, the "differences" in these files are metadata updates stemming from the hdf5/netcdf version upgrade (this is not a new issue, we had the same a while ago on the NOAA platforms). It is thus safe to update the modulefiles and recreate the baseline on Cheyenne / copy the existing baseline on hera to a new date tag.

<img width="1096" alt="Screen Shot 2020-02-24 at 9 21 30 AM" src="https://user-images.githubusercontent.com/8006981/75170252-0fc19380-56e7-11ea-8ef5-df16b38946f4.png">

**Comment by climbfuji** [comment]
> If there is a newer install of NCEPLIBS module on hera we can update to the latest.

Currently the latest installed version is beta02 - as described in the various documents (Test plan, Supported platforms). beta03 will come later today or tomorrow.

**Comment by arunchawla-NOAA** [comment]
@climbfuji @junwang-noaa @DusanJovic-NOAA the module files in the ufs-weather-model/modulefiles directory has been updated by Dom for Cheyenne, hera and gaea. Does jet also need to be updated? We should remove the ones referring to phase 1 and phase 2. What about the other ones? Do we only keep module files for the supported platforms?

**Comment by climbfuji** [comment]
If we want to be consistent, we remove the modulefiles and cmake/make configuration files for platforms that are not preconfigured or supported. BUT: we cannot have modulefiles for supported platforms that do not have alternative NCEPLIBS installations (e.g. production NCEPLIBS), because we do not have a central location for the libraries. These modulefiles and cmake/make config files are only used when calling build.sh or running the regression tests.

**Comment by junwang-noaa** [comment]
Dom,

I thought we do have a central location for the libraries, at least on jet,
gaea, hera besides wcoss.

**Comment by climbfuji** [comment]
Yes, hera, jet, gaea, cheyenne have the nceplibs umbrella libraries in central locations. wcoss has the production libraries in central locations. stampede, orion and other suspects don't have. Shall we just update the jet modulefile and not worry about the rest for the moment?

When we do that, we should also change the submodule pointer for NEMS (documentation) and regtest on hera (cheyenne is down).

**Comment by junwang-noaa** [comment]
Dom,

I think we just need to update the jet modulefile on jet. Do we still need
to make changes in NEMS if we are using cmake build (without using
NEMSAppBuild or NEMSCompsetRun)?

**Comment by arunchawla-NOAA** [comment]
module files have been updated in weather model by @climbfuji to point to the final libraries on the configured platforms
